# language: zh-TW
# Generated by sa-expert
# Source: pm/features/daily_crawl.feature
# Project scan date: 2026-05-08
# Module type: Console App (Tender.Crawler) + Storage Layer (Tender.Storage)
# Architecture: Tender.Crawler.exe → ICrawler + ITenderParser → ITenderRepository → JSON 檔案
# Step Definitions: tests/Tender.AcceptanceTests/Steps/DailyCrawlSteps.cs

Feature: 每日標案爬蟲（自動排程與手動更新）
  業務模組：Bounded Context 1 - Daily Crawl
  主要協調者：Tender.Crawler.Application.ICrawlerOrchestrator
  寫入端：Tender.Storage.Repositories.ITenderRepository / IDailySummaryRepository / ICrawlRunLogRepository
  錯誤記錄：Tender.Storage.Repositories.IErrorLogWriter

  Background:
    Given 已在測試目錄下初始化資料根目錄 "${TEST_DATA_ROOT}/TenderSearch/data/"
    And IDataPaths.DataRoot 指向 "${TEST_DATA_ROOT}/TenderSearch/data/"
    And IAppSettingsRepository.LoadAsync() 回傳預設值，targetTenderMethods 為 ["公開招標", "公開取得報價單或企劃書", "經公開評選或公開徵求之限制性招標"]
    And 系統時區固定為 "Asia/Taipei" (UTC+8)
    And ICrawler 已被 Mock，可由測試控制回傳的 FetchedPage[]

  # ----------------------------------------------------------
  # 自動排程 Happy path
  # ----------------------------------------------------------
  Scenario: 每日 17:00 排程準時執行並成功擷取當天標案
    # 對應 Step Definition：Given_當前時間為 / When_執行ICrawlerOrchestrator
    Given IClock.Now 回傳 "2026-05-08T17:00:00+08:00"
    And ICrawler Mock 回傳 5 筆標案，sourcePk 分別為 "PK001"~"PK005"
    When 執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate = 2026-05-08 })
    Then ICrawler.FetchAsync 應被呼叫，targetDate 參數為 "2026-05-08"
    And ICrawler.FetchAsync 的 tenderMethods 參數應為 ["公開招標", "公開取得報價單或企劃書", "經公開評選或公開徵求之限制性招標"]
    And 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/tenders.json" 應存在
    And tenders.json 反序列化後 DailyTenderSnapshot.Date 應為 "2026-05-08"
    And tenders.json 的 Items 每筆都應包含非空的 SourcePk、AgencyName、TenderName、TenderMethod、AnnouncementDate、DetailUrl
    And 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/summary.json" 應存在，DailySummary.LastRunStatus 應為 RunStatus.Success
    And 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/crawl-runs.json" 應存在
    And CrawlRunLog.Runs 應包含 1 筆紀錄，TriggerSource 為 Scheduled，Status 為 Success

  # ----------------------------------------------------------
  # 手動立即更新 Happy path
  # ----------------------------------------------------------
  Scenario: 使用者按下「立即更新」按鈕成功擷取當天標案
    # 對應 Step Definition：When_執行ICrawlerOrchestrator with Manual mode
    Given IClock.Now 回傳 "2026-05-08T10:30:00+08:00"
    And ICrawler Mock 回傳 3 筆標案
    When 執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Manual, TargetDate = 2026-05-08 })
    Then summary.json 的 LastRunAt 應為 ICrawlerOrchestrator 完成時的 IClock.Now 值
    And crawl-runs.json 最後一筆 Run 的 TriggerSource 應為 Manual

  # ----------------------------------------------------------
  # 補跑情境
  # ----------------------------------------------------------
  Scenario: 17:00 排程因關機未執行，開機後自動補跑一次
    # 對應 Step Definition：When_呼叫IMissedRunDetector
    Given IClock.Now 回傳 "2026-05-08T22:30:00+08:00"
    And 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/summary.json" 不存在
    And ICrawlerLauncher 已被 Mock，呼叫時回傳 exit code 0
    When 呼叫 IMissedRunDetector.CheckAndCatchupAsync()
    Then ICrawlerLauncher.LaunchAsync 應被呼叫一次，CrawlerMode 為 Catchup，TargetDate 為 2026-05-08
    And 補跑完成後 ICrawlerOrchestrator 寫入的 CrawlRun.TriggerSource 應為 Catchup

  Scenario: 17:00 排程已成功執行，使用者開機後不重複補跑
    Given IClock.Now 回傳 "2026-05-08T22:30:00+08:00"
    And 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/summary.json" 已存在，LastRunStatus 為 Success
    When 呼叫 IMissedRunDetector.CheckAndCatchupAsync()
    Then ICrawlerLauncher.LaunchAsync 不應被呼叫
    And 回傳的 MissedRunResult.WasMissed 應為 false

  # ----------------------------------------------------------
  # 重新抓取指定日（補抓）
  # ----------------------------------------------------------
  Scenario: 使用者對過去日期執行「重新抓取此日」
    Given IClock.Now 回傳 "2026-05-08T14:00:00+08:00"
    And 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-05/tenders.json" 已存在，Items 含 sourcePk "EXISTING-001"
    And ICrawler Mock 對 targetDate "2026-05-05" 回傳 4 筆標案，其中 1 筆 sourcePk 為 "EXISTING-001"
    When 執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = ManualRedo, TargetDate = 2026-05-05 })
    Then ICrawler.FetchAsync 的 targetDate 參數應為 "2026-05-05"
    And 寫入路徑應為 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-05/tenders.json"，非當天資料夾
    And crawl-runs.json 最後一筆 Run 的 TriggerSource 應為 ManualRedo
    And tenders.json 中 sourcePk "EXISTING-001" 應只出現 1 次（不重複）

  # ----------------------------------------------------------
  # 同日重複執行的去重
  # ----------------------------------------------------------
  Scenario: 同一天內重複執行爬蟲不可產生重複標案
    # 對應 Step Definition：驗證 ITenderRepository.MergeDailySnapshotAsync 的回傳 MergeResult
    Given IClock.Now 回傳 "2026-05-08T18:30:00+08:00"
    And 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/tenders.json" 已存在，含 50 筆標案 sourcePk "PK001"~"PK050"
    And ICrawler Mock 回傳 7 筆標案：
      | sourcePk | 是否新（既有檔案中存在） |
      | PK001    | 是（既有，內容更新）      |
      | PK002    | 是（既有，內容更新）      |
      | PK051    | 否（全新）                |
      | PK052    | 否（全新）                |
      | PK053    | 否（全新）                |
      | PK048    | 是（既有，無變更）        |
      | PK049    | 是（既有，無變更）        |
    When 執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Manual, TargetDate = 2026-05-08 })
    Then tenders.json 的 Items 總筆數應為 53
    And 同一個 SourcePk 在 Items 中只能出現一次
    And SourcePk 為 "PK001"、"PK002" 的兩筆 LastSeenAt 應為本次 IClock.Now 值，CreatedAt 不變
    And crawl-runs.json 最後一筆 Run 應記錄 InsertedCount=3、UpdatedCount=2、SkippedCount=2

  # ----------------------------------------------------------
  # 跨日資料
  # ----------------------------------------------------------
  Scenario: 同一標案在連續兩天的查詢結果都出現，應分別保留於兩日的快照
    Given ICrawler Mock 對 targetDate "2026-05-07" 回傳含 sourcePk "ABC123" 的標案
    And ICrawler Mock 對 targetDate "2026-05-08" 同樣回傳含 sourcePk "ABC123" 的標案
    When 依序執行 ICrawlerOrchestrator.RunAsync(Scheduled, 2026-05-07) 與 ICrawlerOrchestrator.RunAsync(Scheduled, 2026-05-08)
    Then 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-07/tenders.json" 的 Items 應含 SourcePk "ABC123"
    And 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/tenders.json" 的 Items 應含 SourcePk "ABC123"
    And 兩日的資料夾各自獨立保存，互不影響

  # ----------------------------------------------------------
  # 錯誤情境
  # ----------------------------------------------------------
  Scenario: 政府電子採購網無法連線時，爬蟲執行失敗並記錄錯誤
    Given IClock.Now 回傳 "2026-05-08T17:00:00+08:00"
    And ICrawler Mock 在所有重試（含預設 maxRetries=3）皆拋 CrawlNetworkException
    When 執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate = 2026-05-08 })
    Then summary.json 的 LastRunStatus 應為 RunStatus.Failed
    And summary.json 的 ErrorMessage 應包含子字串 "CrawlNetworkException" 或網路錯誤摘要
    And crawl-runs.json 最後一筆 Run 的 Status 應為 Failed
    And errors.log 應至少含一行 ErrorLogEntry，Severity 為 "error"，Source 為 "crawler"

  Scenario: 政府電子採購網單頁解析失敗，整批任務不應中斷
    Given ICrawler Mock 回傳 5 個 FetchedPage：
      | PageNumber | Html 是否有效 |
      | 1          | 是           |
      | 2          | 是           |
      | 3          | 否（觸發 ITenderParser 拋 ParseException） |
      | 4          | 是           |
      | 5          | 是           |
    And 第 1、2、4、5 頁各回傳 4 筆標案
    When 執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate = 2026-05-08 })
    Then tenders.json 的 Items 筆數應為 16（4 頁 × 4 筆，第 3 頁略過）
    And errors.log 應含一行 Severity 為 "warning"、Page 為 3 的 ErrorLogEntry
    And summary.json 的 LastRunStatus 應為 RunStatus.Success
    And summary.json 的 ErrorMessage 應包含子字串 "部分頁面解析失敗"

  Scenario: JSON 寫入過程中斷，既有檔案不可被破壞
    # 對應 Step Definition：模擬 IAtomicJsonWriter 在 .tmp 寫入後、File.Move 前拋例外
    Given 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/tenders.json" 已存在且內容完整可解析
    And 將 IAtomicJsonWriter 換為 FaultyAtomicJsonWriter，於 File.Move 前拋 IOException
    When 執行 ITenderRepository.MergeDailySnapshotAsync(2026-05-08, 任意 incomingItems, IClock.Now)
    Then 應拋出 IOException
    And 既有 tenders.json 檔案大小與內容應與寫入前一致（hash 相同）
    And errors.log 應記錄該次 IOException

  Scenario: 寫入磁碟失敗（例如磁碟已滿）時應記錄錯誤
    Given IAtomicJsonWriter 模擬磁碟已滿，寫入 .tmp 即拋 IOException
    When 執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate = 2026-05-08 })
    Then errors.log 應含 Severity 為 "error" 的 IOException 紀錄
    And summary.json 若能寫入則 LastRunStatus 應為 Failed；若 summary.json 寫入也失敗則應在 errors.log 額外記錄
    And crawl-runs.json 最後一筆 Run 的 Status 應為 Failed
