# language: zh-TW
# Generated by sa-expert
# Source: pm/features/export_excel.feature
# Project scan date: 2026-05-08
# Module type: WPF Desktop (Tender.Desktop) - Excel Export
# Architecture: DailyQueryViewModel.Export → ISaveFileDialogService → IExcelExporter (ClosedXML)
# Step Definitions: tests/Tender.AcceptanceTests/Steps/ExportExcelSteps.cs

Feature: 匯出 Excel
  業務模組：Bounded Context 5 - Export
  匯出器：Tender.Desktop.Services.IExcelExporter（實作：ClosedXmlExcelExporter）
  另存對話框：Tender.Desktop.Services.ISaveFileDialogService（已決議：另存新檔對話框）
  資料來源：DailyQueryViewModel.FilteredItems

  Background:
    Given IClock.Now 回傳 "2026-05-08T09:00:00+08:00"
    And 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/tenders.json" 存在，Items 共 55 筆
    And DailyQueryViewModel 已載入 Date = 2026-05-08
    And ISaveFileDialogService 已被 Mock

  # ----------------------------------------------------------
  # Happy path
  # ----------------------------------------------------------
  Scenario: 匯出當前日期的全部標案
    Given DailyQueryViewModel.FilteredItems.Count 為 55（未套用任何篩選）
    And ISaveFileDialogService.ShowSaveAsXlsx 回傳 "${TEST_OUTPUT}/標案_20260508.xlsx"
    When 呼叫 DailyQueryViewModel.ExportCommand.Execute(null)
    Then 檔案 "${TEST_OUTPUT}/標案_20260508.xlsx" 應存在
    And 用 ClosedXML 開啟該檔案，第一張工作表的資料列數（不含表頭）應為 55
    And 第一張工作表的表頭（第 1 列）應至少包含：標案名稱、招標方式、採購性質、公告日期、截止投標、預算金額、機關名稱、檢視連結
    And 「標案名稱」或「檢視連結」欄的儲存格應具備可點擊超連結（IXLCell.HasHyperlink == true）

  Scenario: 匯出套用篩選後的結果
    Given 已呼叫 ToggleKeywordButtonCommand.Execute("AI")，FilteredItems.Count 為 8
    And ISaveFileDialogService.ShowSaveAsXlsx 回傳 "${TEST_OUTPUT}/標案_20260508_AI.xlsx"
    When 呼叫 ExportCommand.Execute(null)
    Then 匯出檔案的資料列數（不含表頭）應為 8
    And 每筆「標案名稱」或「檢視連結」欄的超連結應指向對應 TenderItem.DetailUrl

  Scenario: 匯出檔案格式適合再用 Excel 篩選
    When 呼叫 ExportCommand.Execute(null) 並完成匯出
    Then 匯出檔案副檔名應為 .xlsx
    And 表頭列應在第 1 列
    And 「預算金額」欄的儲存格資料型別應為 XLDataType.Number
    And 「公告日期」與「截止投標」欄的儲存格應為文字格式（保留民國年原文，例 "115/05/08"）

  # ----------------------------------------------------------
  # 篩選結果合併文字（取代 Excel 「篩選」工作表）
  # ----------------------------------------------------------
  Scenario: 匯出結果具備「機關名稱：標案名稱」合併文字以取代 Excel 篩選工作表
    Given FilteredItems[0].AgencyName 為 "經濟部水利署"
    And FilteredItems[0].TenderName 為 "智慧水利監測系統建置案"
    And FilteredItems[0].DetailUrl 為 "https://web.pcc.gov.tw/prkms/urlSelector/common/tpam?pk=ABC"
    When 呼叫 ExportCommand.Execute(null) 並完成匯出
    Then 匯出檔案應包含一欄表頭為「機關名稱：標案名稱」
    And 該欄第一筆資料儲存格的文字應為 "經濟部水利署：智慧水利監測系統建置案"
    And 該儲存格的 Hyperlink.ExternalAddress 應為 "https://web.pcc.gov.tw/prkms/urlSelector/common/tpam?pk=ABC"

  # ----------------------------------------------------------
  # 邊界情境
  # ----------------------------------------------------------
  Scenario: 匯出時沒有任何資料
    Given DailyQueryViewModel.FilteredItems.Count 為 0
    When 呼叫 ExportCommand.Execute(null)
    Then ISaveFileDialogService.ShowSaveAsXlsx 不應被呼叫
    And IExcelExporter.ExportAsync 不應被呼叫
    And DailyQueryViewModel.LastUserMessage 應包含「目前沒有可匯出的資料」
    And 不應產生任何 .xlsx 檔案

  Scenario: 匯出包含特殊字元的標案資料
    Given FilteredItems 中某筆 TenderName 為 "「智慧」（永續）＆ESG％專案"
    And ISaveFileDialogService.ShowSaveAsXlsx 回傳 "${TEST_OUTPUT}/special.xlsx"
    When 呼叫 ExportCommand.Execute(null)
    Then 用 ClosedXML 重新讀回該儲存格的字串應完全等於 "「智慧」（永續）＆ESG％專案"

  # ----------------------------------------------------------
  # 錯誤情境
  # ----------------------------------------------------------
  Scenario: 寫入匯出檔失敗（檔案被使用者開啟中）
    Given ISaveFileDialogService.ShowSaveAsXlsx 回傳 "${TEST_OUTPUT}/locked.xlsx"
    And 檔案 "${TEST_OUTPUT}/locked.xlsx" 已被另一個程序以獨佔模式開啟
    When 呼叫 ExportCommand.Execute(null)
    Then 不應拋出未處理例外
    And DailyQueryViewModel.LastUserMessage 應包含「目標檔案正被其他程式使用」
    And errors.log 應記錄該次 IOException

  Scenario: 匯出過程被使用者取消
    Given ISaveFileDialogService.ShowSaveAsXlsx 回傳 null（使用者取消）
    When 呼叫 ExportCommand.Execute(null)
    Then IExcelExporter.ExportAsync 不應被呼叫
    And 不應產生任何 .xlsx 檔案
    And DailyQueryViewModel 狀態應與匯出前相同
