# language: zh-TW
# Generated by sa-expert
# Source: pm/features/installation.feature
# Project scan date: 2026-05-08
# Module type: WiX MSI Installer (Tender.Installer) + Custom Actions
# Architecture: WiX bundle → DataDirectoryActions / TaskSchedulerActions → 檔案系統 + Task Scheduler
# Step Definitions: tests/Tender.AcceptanceTests/Steps/InstallationSteps.cs

Feature: 安裝與排程任務建立
  業務模組：Bounded Context 6 - Installation
  安裝器：Tender.Installer (WiX MSI)
  Custom Actions：Tender.Installer.CustomActions.DataDirectoryActions / TaskSchedulerActions
  排程權限：Per-user task（已決議，不需系統管理員權限）

  # 測試實作備註：
  # - Installation 的 BDD 測試難以在 CI 上執行真正的 MSI 安裝。建議分兩層：
  #   1. 對 DataDirectoryActions / TaskSchedulerActions 的 C# 方法做單元測試（這也是 Reqnroll 的主要範圍）
  #   2. MSI 端到端測試以手動 QA 為主，文件化 acceptance criteria
  # - 以下 Scenario 多以 Custom Action 方法呼叫為驗證點

  Background:
    Given 測試環境變數 ${TEST_LOCAL_APP_DATA} 指向臨時目錄取代 %LocalAppData%
    And 測試使用 ITaskSchedulerAdapter 的 InMemory Mock 取代真實 Windows Task Scheduler

  # ----------------------------------------------------------
  # Happy path
  # ----------------------------------------------------------
  Scenario: 全新安裝完成，建立資料根目錄、捷徑與排程任務
    # 對應 Step Definition：When_執行Custom Action / Then_驗證檔案系統與排程
    Given ${TEST_LOCAL_APP_DATA}/TenderSearch/ 目錄不存在
    And ITaskSchedulerAdapter 中沒有名為 "TenderSearch.DailyCrawl" 的任務
    When 執行 DataDirectoryActions.EnsureDataRoot()
    And 執行 TaskSchedulerActions.CreateDailyTask()
    Then 目錄 "${TEST_LOCAL_APP_DATA}/TenderSearch/data/" 應存在
    And 目錄 "${TEST_LOCAL_APP_DATA}/TenderSearch/data/settings/" 應存在
    And 檔案 "${TEST_LOCAL_APP_DATA}/TenderSearch/data/settings/keywords.json" 應存在，且可被反序列化為 KeywordSet
    And ITaskSchedulerAdapter 應含名為 "TenderSearch.DailyCrawl" 的任務
    And 該任務的 ScheduledTime 應為 "17:00"
    And 該任務的 StartWhenAvailable 旗標應為 true
    And 該任務的 RunLevel 應為 LeastPrivilege（per-user）
    # 桌面/開始捷徑由 WiX File element 處理，於 MSI 端到端測試驗證

  Scenario: 安裝完成後排程可實際執行
    # 此 Scenario 為整合測試，驗證 Task Scheduler 觸發路徑
    Given 已成功執行 EnsureDataRoot 與 CreateDailyTask
    And ITaskSchedulerAdapter Mock 設定為「在指定時間立即觸發 Action」
    And IClock.Now 設定為 "2026-05-08T17:00:00+08:00"
    When ITaskSchedulerAdapter 觸發 "TenderSearch.DailyCrawl" 對應的 Action
    Then ICrawlerLauncher 應接收到 (Mode = Scheduled, TargetDate = 2026-05-08) 的呼叫
    And 桌面程式可未開啟，仍應在 "${TEST_LOCAL_APP_DATA}/TenderSearch/data/2026-05/2026-05-08/" 產生 tenders.json

  # ----------------------------------------------------------
  # 重複安裝
  # ----------------------------------------------------------
  Scenario: 重新安裝時不可覆蓋已存在的資料目錄
    Given 目錄 "${TEST_LOCAL_APP_DATA}/TenderSearch/data/2026-04-15/" 已存在，含 tenders.json 與 summary.json
    When 再次執行 DataDirectoryActions.EnsureDataRoot()
    Then 既有檔案 "${TEST_LOCAL_APP_DATA}/TenderSearch/data/2026-04-15/tenders.json" 內容與時間戳應與安裝前一致
    And 不應有任何既有檔案被刪除或覆寫

  Scenario: 重新安裝時若排程任務已存在不應重複建立
    Given ITaskSchedulerAdapter 已含名為 "TenderSearch.DailyCrawl" 的任務，ScheduledTime 為 "17:00"
    When 再次執行 TaskSchedulerActions.CreateDailyTask()
    Then ITaskSchedulerAdapter 中名為 "TenderSearch.DailyCrawl" 的任務只應有 1 個
    And 該任務的 ScheduledTime 應仍為 "17:00"

  # ----------------------------------------------------------
  # 錯誤情境
  # ----------------------------------------------------------
  Scenario: 沒有權限建立排程任務
    Given ITaskSchedulerAdapter Mock 設定為「呼叫 RegisterTaskAsync 時拋 UnauthorizedAccessException」
    When 執行 TaskSchedulerActions.CreateDailyTask()
    Then 回傳的 ActionResult 應為 ActionResult.NotExecuted（或自訂 PartialSuccess）
    And InstallationOutcome.ScheduledTaskCreated 應為 false
    And 安裝結果摘要應包含「排程任務未建立，請手動於 Task Scheduler 設定每日 17:00」字樣
    # 桌面捷徑與資料目錄仍應建立（由 WiX File element + EnsureDataRoot 完成）

  Scenario: 資料根目錄無法建立
    Given ${TEST_LOCAL_APP_DATA}/TenderSearch/ 路徑被測試環境設為無寫入權限
    When 執行 DataDirectoryActions.EnsureDataRoot()
    Then 回傳的 ActionResult 應為 ActionResult.Failure
    And 不應呼叫後續的 TaskSchedulerActions.CreateDailyTask
    And 安裝程序應中止，不應留下任何捷徑或排程任務

  Scenario: 安裝過程中使用者取消
    # MSI 端到端情境，由 WiX 內建的 Rollback 機制處理
    Given 已執行 EnsureDataRoot（資料目錄已建立）
    When 使用者於安裝精靈點選「取消」
    Then WiX Rollback 應移除本次安裝建立的捷徑檔案
    And ITaskSchedulerAdapter 不應含名為 "TenderSearch.DailyCrawl" 的任務
    And 既有的資料根目錄（若安裝前已存在）應保留
    # 此情境由 WiX msi 的 Rollback Custom Action 機制處理，C# 端只需確保 EnsureDataRoot/CreateDailyTask 都實作對應的 Rollback action

  # ----------------------------------------------------------
  # 解除安裝
  # ----------------------------------------------------------
  Scenario: 解除安裝時保留使用者既有資料
    Given 目錄 "${TEST_LOCAL_APP_DATA}/TenderSearch/data/2026-04-15/" 含使用者歷史資料
    And ITaskSchedulerAdapter 含名為 "TenderSearch.DailyCrawl" 的任務
    When 執行 TaskSchedulerActions.RemoveDailyTask()
    And 執行 WiX 的 Uninstall 流程（移除捷徑與安裝目錄程式檔）
    Then ITaskSchedulerAdapter 不應含名為 "TenderSearch.DailyCrawl" 的任務
    And 目錄 "${TEST_LOCAL_APP_DATA}/TenderSearch/data/" 與其下的歷史資料應完整保留
