// Auto-generated by sa-expert
// Feature: 每日標案爬蟲（自動排程與手動更新）
// Source: sa/engineer_features/daily_crawl.feature
// Module type: Console App + Storage Layer
// BDD Framework: Reqnroll

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Reqnroll;
using Tender.Core.Models;

namespace Tender.AcceptanceTests.Steps;

[Binding]
public sealed class DailyCrawlSteps
{
    private readonly ScenarioContext _scenarioContext;

    public DailyCrawlSteps(ScenarioContext scenarioContext)
    {
        _scenarioContext = scenarioContext;
    }

    // -------------------------------------------------------------
    // Given：環境與 Mock 設定
    // -------------------------------------------------------------

    [Given(@"ICrawler Mock 回傳 (\d+) 筆標案，sourcePk 分別為 ""(.*)""~""(.*)""")]
    public void Given_CrawlerReturnsItemsRange(int count, string fromPk, string toPk)
    {
        throw new NotImplementedException(
            "TODO: 產生 count 筆 TenderItem（SourcePk 由 fromPk 數值範圍生成），" +
            "Mock<ICrawler>.Setup(x => x.FetchAsync(It.IsAny<DateOnly>(), It.IsAny<IReadOnlyList<string>>(), It.IsAny<CancellationToken>())).ReturnsAsync(IEnumerable of FetchedPage)；" +
            "FetchedPage.Html 可以是 placeholder，因為 ITenderParser 在此測試也應 Mock 為直接回傳預設 TenderItem 集合。");
    }

    [Given(@"ICrawler Mock 回傳 (\d+) 筆標案")]
    public void Given_CrawlerReturnsItems(int count)
    {
        throw new NotImplementedException("TODO: 同上，但不指定具體 SourcePk，自動生成。");
    }

    [Given(@"ICrawler Mock 對 targetDate ""(.*)"" 回傳 (\d+) 筆標案，其中 (\d+) 筆 sourcePk 為 ""(.*)""")]
    public void Given_CrawlerReturnsForDateWithExisting(string targetDate, int total, int existingCount, string existingPk)
    {
        throw new NotImplementedException(
            "TODO: Mock<ICrawler>.Setup 對 DateOnly.Parse(targetDate) 回傳 total 筆，其中第 0~existingCount-1 筆 SourcePk 為 existingPk。");
    }

    [Given(@"ICrawler Mock 對 targetDate ""(.*)"" 回傳含 sourcePk ""(.*)"" 的標案")]
    public void Given_CrawlerReturnsForDateContainingPk(string targetDate, string sourcePk)
    {
        throw new NotImplementedException("TODO: 同上，僅驗證指定 SourcePk 的存在。");
    }

    [Given(@"ICrawler Mock 同樣回傳含 sourcePk ""(.*)"" 的標案")]
    public void Given_CrawlerAlsoReturnsContainingPk(string sourcePk)
    {
        throw new NotImplementedException("TODO: 對另一個 targetDate 設定同樣含此 SourcePk 的回傳。");
    }

    [Given(@"檔案 ""(.*)"" 已存在，Items 含 sourcePk ""(.*)""")]
    public void Given_TendersFileExistsWithPk(string filePath, string sourcePk)
    {
        throw new NotImplementedException(
            "TODO: 解析 ${TEST_DATA_ROOT} → 實際路徑，產生 DailyTenderSnapshot 含一筆指定 SourcePk 的 TenderItem，序列化為 JSON 寫入該路徑。");
    }

    [Given(@"檔案 ""(.*)"" 已存在，含 (\d+) 筆標案 sourcePk ""(.*)""~""(.*)""")]
    public void Given_TendersFileExistsWithPkRange(string filePath, int count, string fromPk, string toPk)
    {
        throw new NotImplementedException("TODO: 產生 count 筆 SourcePk 從 fromPk 到 toPk 的 TenderItem 陣列並寫入 JSON。");
    }

    [Given(@"ICrawler Mock 回傳 (\d+) 筆標案：")]
    public void Given_CrawlerReturnsItemsTable(int count, Table table)
    {
        throw new NotImplementedException(
            "TODO: 解析 Table，每行含 sourcePk 與「是否新」標示；既有者複用測試初始 TenderItem，新者另行建立。");
    }

    [Given(@"檔案 ""(.*)"" 不存在")]
    public void Given_FileDoesNotExist(string filePath)
    {
        throw new NotImplementedException("TODO: ResolvePath 後若檔案存在則刪除。");
    }

    [Given(@"檔案 ""(.*)"" 已存在，LastRunStatus 為 (\w+)")]
    public void Given_SummaryFileExistsWithStatus(string filePath, string status)
    {
        throw new NotImplementedException(
            "TODO: 寫入 DailySummary JSON，LastRunStatus 設為對應 RunStatus enum。");
    }

    [Given(@"ICrawlerLauncher 已被 Mock，呼叫時回傳 exit code (\d+)")]
    public void Given_CrawlerLauncherMockedReturnsExitCode(int exitCode)
    {
        throw new NotImplementedException(
            "TODO: Mock<ICrawlerLauncher>.Setup(x => x.LaunchAsync(...)).ReturnsAsync(exitCode)。");
    }

    [Given(@"ICrawler Mock 在所有重試（含預設 maxRetries=3）皆拋 CrawlNetworkException")]
    public void Given_CrawlerThrowsNetworkExceptionAlways()
    {
        throw new NotImplementedException("TODO: Mock<ICrawler>.Setup(...).ThrowsAsync(new CrawlNetworkException(...))。");
    }

    [Given(@"ICrawler Mock 在所有重試（maxRetries=3）皆拋 CrawlNetworkException\(message = ""(.*)""\)")]
    public void Given_CrawlerThrowsNetworkExceptionWithMessage(string message)
    {
        throw new NotImplementedException("TODO: 同上但訊息指定。");
    }

    [Given(@"ICrawler Mock 回傳 (\d+) 個 FetchedPage：")]
    public void Given_CrawlerReturnsFetchedPages(int count, Table table)
    {
        throw new NotImplementedException(
            "TODO: 解析 Table，依「Html 是否有效」決定該頁是回傳有效 TenderItem 或讓 ITenderParser 拋 ParseException。");
    }

    [Given(@"第 (\d+)、(\d+)、(\d+)、(\d+) 頁各回傳 (\d+) 筆標案")]
    public void Given_PagesReturnItemsCount(int p1, int p2, int p3, int p4, int countPerPage)
    {
        throw new NotImplementedException("TODO: 對指定頁面 Mock 回傳 countPerPage 筆 TenderItem。");
    }

    [Given(@"將 IAtomicJsonWriter 換為 FaultyAtomicJsonWriter，於 File\.Move 前拋 IOException")]
    public void Given_FaultyAtomicJsonWriter()
    {
        throw new NotImplementedException(
            "TODO: 註冊 FaultyAtomicJsonWriter（測試專用）取代正常實作；於 .tmp 寫入後、File.Move 前拋 IOException。");
    }

    [Given(@"IAtomicJsonWriter 模擬磁碟已滿，寫入 \.tmp 即拋 IOException")]
    public void Given_AtomicJsonWriterDiskFull()
    {
        throw new NotImplementedException("TODO: 註冊測試專用 writer，寫 .tmp 即拋 IOException(\"disk full\")。");
    }

    // -------------------------------------------------------------
    // When：執行動作
    // -------------------------------------------------------------

    [When(@"執行 ICrawlerOrchestrator\.RunAsync\(new CrawlerArgs \{ Mode = (\w+), TargetDate = (\d{4}-\d{2}-\d{2}) \}\)")]
    public async Task When_RunCrawlerOrchestrator(string mode, string targetDate)
    {
        throw new NotImplementedException(
            "TODO: 解析 mode 為 CrawlerMode enum、targetDate 為 DateOnly。" +
            "從 ServiceProvider 取得 ICrawlerOrchestrator，呼叫 RunAsync 並把回傳的 CrawlRun 與任何例外存入 ScenarioContext 供 Then 驗證。");
    }

    [When(@"依序執行 ICrawlerOrchestrator\.RunAsync\(Scheduled, (\d{4}-\d{2}-\d{2})\) 與 ICrawlerOrchestrator\.RunAsync\(Scheduled, (\d{4}-\d{2}-\d{2})\)")]
    public async Task When_RunOrchestratorTwiceForDates(string date1, string date2)
    {
        throw new NotImplementedException("TODO: 連續呼叫兩次 RunAsync，分別以 date1、date2 為 TargetDate。");
    }

    [When(@"呼叫 IMissedRunDetector\.CheckAndCatchupAsync\(\)")]
    public async Task When_CallMissedRunDetector()
    {
        throw new NotImplementedException(
            "TODO: 從 ServiceProvider 取得 IMissedRunDetector，呼叫 CheckAndCatchupAsync，把 MissedRunResult 存入 ScenarioContext。");
    }

    [When(@"執行 ITenderRepository\.MergeDailySnapshotAsync\((\d{4}-\d{2}-\d{2}), 任意 incomingItems, IClock\.Now\)")]
    public async Task When_MergeDailySnapshot(string date)
    {
        throw new NotImplementedException(
            "TODO: 用 DateOnly.Parse(date) 與任意 List<TenderItem>（如 1 筆 stub）呼叫 MergeDailySnapshotAsync，捕捉例外存入 ScenarioContext。");
    }

    // -------------------------------------------------------------
    // Then：驗證結果
    // -------------------------------------------------------------

    [Then(@"ICrawler\.FetchAsync 應被呼叫，targetDate 參數為 ""(.*)""")]
    public void Then_CrawlerFetchAsyncCalledWithTargetDate(string expectedDate)
    {
        throw new NotImplementedException(
            "TODO: Mock<ICrawler>.Verify(x => x.FetchAsync(DateOnly.Parse(expectedDate), It.IsAny<...>(), It.IsAny<...>()), Times.AtLeastOnce)。");
    }

    [Then(@"ICrawler\.FetchAsync 的 tenderMethods 參數應為 \[(.+)\]")]
    public void Then_CrawlerFetchAsyncCalledWithTenderMethods(string methodsCsv)
    {
        throw new NotImplementedException("TODO: 解析 methodsCsv，Verify 對應的 IReadOnlyList<string> 參數。");
    }

    [Then(@"ICrawler\.FetchAsync 的 targetDate 參數應為 ""(.*)""")]
    public void Then_CrawlerFetchAsyncTargetDateEquals(string expectedDate)
    {
        throw new NotImplementedException("TODO: Verify Mock<ICrawler>.FetchAsync 的 targetDate 參數。");
    }

    [Then(@"檔案 ""(.*)"" 應存在")]
    public void Then_FileShouldExist(string filePath)
    {
        throw new NotImplementedException("TODO: ResolvePath → File.Exists 應為 true。");
    }

    [Then(@"tenders\.json 反序列化後 DailyTenderSnapshot\.Date 應為 ""(.*)""")]
    public void Then_TendersDateEquals(string expectedDate)
    {
        throw new NotImplementedException("TODO: 讀取 ${TEST_DATA_ROOT}/.../tenders.json，反序列化為 DailyTenderSnapshot，斷言 Date 屬性。");
    }

    [Then(@"tenders\.json 的 Items 每筆都應包含非空的 SourcePk、AgencyName、TenderName、TenderMethod、AnnouncementDate、DetailUrl")]
    public void Then_TendersItemsContainRequiredFields()
    {
        throw new NotImplementedException("TODO: 反序列化後遍歷 Items，斷言指定欄位非空字串。");
    }

    [Then(@"tenders\.json 的 Items 總筆數應為 (\d+)")]
    public void Then_TendersItemsCountEquals(int expected)
    {
        throw new NotImplementedException("TODO: 反序列化後驗證 Items.Count。");
    }

    [Then(@"同一個 SourcePk 在 Items 中只能出現一次")]
    public void Then_SourcePkUnique()
    {
        throw new NotImplementedException("TODO: items.GroupBy(SourcePk).All(g => g.Count() == 1)。");
    }

    [Then(@"SourcePk 為 ""(.*)""、""(.*)"" 的兩筆 LastSeenAt 應為本次 IClock\.Now 值，CreatedAt 不變")]
    public void Then_LastSeenAtUpdated(string pk1, string pk2)
    {
        throw new NotImplementedException(
            "TODO: 對指定 SourcePk 找對應 TenderItem，斷言 LastSeenAt == FakeClock.Now，CreatedAt 與 Background 設定的值相同。");
    }

    [Then(@"檔案 ""(.*)"" 應存在，DailySummary\.LastRunStatus 應為 RunStatus\.(\w+)")]
    public void Then_SummaryFileExistsWithStatus(string filePath, string status)
    {
        throw new NotImplementedException("TODO: 反序列化 summary.json，驗證 LastRunStatus。");
    }

    [Then(@"summary\.json 的 LastRunStatus 應為 RunStatus\.(\w+)")]
    public void Then_SummaryLastRunStatusEquals(string status)
    {
        throw new NotImplementedException("TODO: 反序列化指定日 summary.json 並驗證。");
    }

    [Then(@"summary\.json 的 LastRunAt 應為 ICrawlerOrchestrator 完成時的 IClock\.Now 值")]
    public void Then_SummaryLastRunAtIsClockNow()
    {
        throw new NotImplementedException("TODO: 比對 LastRunAt 與 FakeClock.Now（容忍 1 秒誤差）。");
    }

    [Then(@"summary\.json 的 ErrorMessage 應包含子字串 ""(.*)"" 或網路錯誤摘要")]
    public void Then_SummaryErrorMessageContains(string substring)
    {
        throw new NotImplementedException("TODO: 反序列化後 Assert ErrorMessage.Contains(substring) 或符合錯誤摘要 pattern。");
    }

    [Then(@"summary\.json 的 ErrorMessage 應包含子字串 ""(.*)""")]
    public void Then_SummaryErrorMessageContainsExact(string substring)
    {
        throw new NotImplementedException("TODO: 反序列化後 Assert ErrorMessage.Contains(substring)。");
    }

    [Then(@"檔案 ""(.*)"" 應存在")]
    public void Then_CrawlRunsFileShouldExist(string filePath)
    {
        // Note: Reqnroll 會把這個 Then 與其他「檔案存在」合併，由參數 path 區分。實作時請保留 ResolvePath 邏輯。
        throw new NotImplementedException("TODO: ResolvePath → File.Exists 應為 true。");
    }

    [Then(@"CrawlRunLog\.Runs 應包含 (\d+) 筆紀錄，TriggerSource 為 (\w+)，Status 為 (\w+)")]
    public void Then_CrawlRunLogContainsRun(int count, string trigger, string status)
    {
        throw new NotImplementedException("TODO: 反序列化 crawl-runs.json，斷言 Runs.Count、TriggerSource、Status。");
    }

    [Then(@"crawl-runs\.json 最後一筆 Run 的 TriggerSource 應為 (\w+)")]
    public void Then_LastRunTriggerSourceEquals(string trigger)
    {
        throw new NotImplementedException("TODO: 反序列化後取最後一筆 Run，比對 TriggerSource enum。");
    }

    [Then(@"crawl-runs\.json 最後一筆 Run 的 Status 應為 (\w+)")]
    public void Then_LastRunStatusEquals(string status)
    {
        throw new NotImplementedException("TODO: 反序列化後取最後一筆 Run，比對 Status enum。");
    }

    [Then(@"crawl-runs\.json 最後一筆 Run 應記錄 InsertedCount=(\d+)、UpdatedCount=(\d+)、SkippedCount=(\d+)")]
    public void Then_LastRunCountsEqual(int inserted, int updated, int skipped)
    {
        throw new NotImplementedException("TODO: 取最後一筆 Run，斷言三項計數欄位。");
    }

    [Then(@"ICrawlerLauncher\.LaunchAsync 應被呼叫一次，CrawlerMode 為 (\w+)，TargetDate 為 (\d{4}-\d{2}-\d{2})")]
    public void Then_CrawlerLauncherCalled(string mode, string targetDate)
    {
        throw new NotImplementedException("TODO: Mock<ICrawlerLauncher>.Verify with Times.Once 與參數比對。");
    }

    [Then(@"ICrawlerLauncher\.LaunchAsync 不應被呼叫")]
    public void Then_CrawlerLauncherNotCalled()
    {
        throw new NotImplementedException("TODO: Mock<ICrawlerLauncher>.Verify(..., Times.Never)。");
    }

    [Then(@"回傳的 MissedRunResult\.WasMissed 應為 (true|false)")]
    public void Then_MissedRunResultWasMissed(bool expected)
    {
        throw new NotImplementedException("TODO: 從 ScenarioContext 取出 MissedRunResult，斷言 WasMissed。");
    }

    [Then(@"補跑完成後 ICrawlerOrchestrator 寫入的 CrawlRun\.TriggerSource 應為 (\w+)")]
    public void Then_CatchupRunTriggerSource(string trigger)
    {
        throw new NotImplementedException("TODO: 在 ICrawlerLauncher Mock 內部呼叫真實 Orchestrator 後，驗證寫入的 CrawlRun。或於 Mock 設定 callback 直接驗證。");
    }

    [Then(@"寫入路徑應為 ""(.*)""，非當天資料夾")]
    public void Then_WrittenToSpecificFolder(string filePath)
    {
        throw new NotImplementedException("TODO: 驗證 ResolvePath 後檔案存在，且當天資料夾無新增 tenders.json。");
    }

    [Then(@"tenders\.json 中 sourcePk ""(.*)"" 應只出現 1 次（不重複）")]
    public void Then_SourcePkAppearsOnce(string pk)
    {
        throw new NotImplementedException("TODO: 反序列化後 Count(x => x.SourcePk == pk) == 1。");
    }

    [Then(@"檔案 ""(.*)"" 的 Items 應含 SourcePk ""(.*)""")]
    public void Then_TendersFileContainsPk(string filePath, string pk)
    {
        throw new NotImplementedException("TODO: 反序列化指定路徑 tenders.json，斷言 Items 含該 SourcePk。");
    }

    [Then(@"兩日的資料夾各自獨立保存，互不影響")]
    public void Then_BothDaysIndependent()
    {
        throw new NotImplementedException("TODO: 驗證兩個檔案內容互不混用（GeneratedAt 各自記錄、Items 順序各自獨立）。");
    }

    [Then(@"errors\.log 應至少含一行 ErrorLogEntry，Severity 為 ""(.*)""，Source 為 ""(.*)""")]
    public void Then_ErrorsLogContainsEntry(string severity, string source)
    {
        throw new NotImplementedException("TODO: 讀取 errors.log，逐行解析為 ErrorLogEntry，至少存在一筆符合條件。");
    }

    [Then(@"errors\.log 應含一行 Severity 為 ""(.*)""、Page 為 (\d+) 的 ErrorLogEntry")]
    public void Then_ErrorsLogContainsPageEntry(string severity, int page)
    {
        throw new NotImplementedException("TODO: 解析 errors.log 找 Severity + Page 相符的條目。");
    }

    [Then(@"tenders\.json 的 Items 筆數應為 (\d+)（4 頁 × 4 筆，第 3 頁略過）")]
    public void Then_TendersItemsCountAfterPartialFailure(int expected)
    {
        throw new NotImplementedException("TODO: 同 Then_TendersItemsCountEquals。");
    }

    [Then(@"應拋出 IOException")]
    public void Then_ShouldThrowIOException()
    {
        throw new NotImplementedException("TODO: 從 ScenarioContext 取出 When 期間捕捉的例外，斷言為 IOException。");
    }

    [Then(@"既有 tenders\.json 檔案大小與內容應與寫入前一致（hash 相同）")]
    public void Then_ExistingTendersUnchanged()
    {
        throw new NotImplementedException(
            "TODO: 在 Given 步驟記錄初始檔案的 SHA256；此處重算並比對。");
    }

    [Then(@"errors\.log 應記錄該次 IOException")]
    public void Then_ErrorsLogContainsIOException()
    {
        throw new NotImplementedException("TODO: 解析 errors.log，找 ExceptionDetail 含 'IOException' 的條目。");
    }

    [Then(@"errors\.log 應含 Severity 為 ""(.*)"" 的 IOException 紀錄")]
    public void Then_ErrorsLogContainsIOExceptionWithSeverity(string severity)
    {
        throw new NotImplementedException("TODO: 同上但限定 Severity。");
    }

    [Then(@"summary\.json 若能寫入則 LastRunStatus 應為 Failed；若 summary\.json 寫入也失敗則應在 errors\.log 額外記錄")]
    public void Then_SummaryFailedOrAdditionalErrorLog()
    {
        throw new NotImplementedException(
            "TODO: 若 summary.json 存在 → 驗證 LastRunStatus = Failed；否則 → errors.log 必須含 summary 寫入失敗的條目。");
    }
}
