// Auto-generated by sa-expert
// Feature: 指定日期標案資料查詢
// Source: sa/engineer_features/daily_query.feature
// Module type: WPF Desktop + Core Search
// BDD Framework: Reqnroll

using System;
using System.Threading.Tasks;
using Reqnroll;

namespace Tender.AcceptanceTests.Steps;

[Binding]
public sealed class DailyQuerySteps
{
    private readonly ScenarioContext _scenarioContext;

    public DailyQuerySteps(ScenarioContext scenarioContext)
    {
        _scenarioContext = scenarioContext;
    }

    // -------------------------------------------------------------
    // Given
    // -------------------------------------------------------------

    [Given(@"檔案 ""(.*)"" 存在，Items 共 (\d+) 筆")]
    public void Given_TendersFileExistsWithCount(string filePath, int count)
    {
        throw new NotImplementedException(
            "TODO: ResolvePath，產生 count 筆 TenderItem 的 DailyTenderSnapshot，序列化寫入該路徑。" +
            "TenderItem 內容可由 TestDataBuilder 預先生成，包含後續測試會用到的關鍵字、招標方式分布。");
    }

    [Given(@"已透過 ShellViewModel\.NavigateToDayCommand 載入 DailyQueryViewModel，Date = DateOnly\((\d+), (\d+), (\d+)\)")]
    public void Given_DailyQueryViewModelLoaded(int year, int month, int day)
    {
        throw new NotImplementedException(
            "TODO: 從 DI 取 ShellViewModel，呼叫 NavigateToDayCommand.Execute(new DateOnly(...))，等待 LoadAsync 完成；" +
            "把 DailyQueryViewModel 存入 ScenarioContext。");
    }

    [Given(@"Items 中 TenderName 含 ""(.*)"" 的筆數為 (\d+)")]
    public void Given_ItemsTenderNameContainsCount(string keyword, int count)
    {
        throw new NotImplementedException(
            "TODO: 重新產生 tenders.json，確保 TenderName 含 keyword 的筆數恰為 count。" +
            "其餘標案 TenderName 不含 keyword。");
    }

    [Given(@"Items 中 AgencyName 含 ""(.*)"" 的筆數為 (\d+)")]
    public void Given_ItemsAgencyNameContainsCount(string keyword, int count)
    {
        throw new NotImplementedException("TODO: 同上但作用於 AgencyName。");
    }

    [Given(@"Items 中存在 TenderNo 為 ""(.*)"" 的標案 (\d+) 筆")]
    public void Given_ItemsTenderNoEquals(string tenderNo, int count)
    {
        throw new NotImplementedException("TODO: 為其中 count 筆設定 TenderNo = tenderNo。");
    }

    [Given(@"Items 中 BudgetAmount 介於 (\d+) 與 (\d+) 的筆數為 (\d+)")]
    public void Given_ItemsBudgetRangeCount(long min, long max, int count)
    {
        throw new NotImplementedException("TODO: 重新產生 tenders.json，確保 count 筆 BudgetAmount ∈ [min, max]。");
    }

    [Given(@"Items 中 AnnouncementDate 介於 ""(.*)"" 與 ""(.*)""（含）的筆數為 (\d+)")]
    public void Given_ItemsAnnouncementDateRangeCount(string from, string to, int count)
    {
        throw new NotImplementedException("TODO: 設定 count 筆 AnnouncementDate 落在 [from, to]（民國年字串）。");
    }

    [Given(@"Items 中 BidDeadline 介於 ""(.*)"" 與 ""(.*)""（含）的筆數為 (\d+)")]
    public void Given_ItemsBidDeadlineRangeCount(string from, string to, int count)
    {
        throw new NotImplementedException("TODO: 同上但作用於 BidDeadline。");
    }

    [Given(@"DailyQueryViewModel\.Date 為 DateOnly\((\d+), (\d+), (\d+)\)")]
    public void Given_DailyQueryDateIs(int year, int month, int day)
    {
        throw new NotImplementedException(
            "TODO: 從 ScenarioContext 取 DailyQueryViewModel，斷言 Date 等於 new DateOnly(...)（前置條件斷言而非設值）。");
    }

    [Given(@"FilteredItems\[(\d+)\]\.DetailUrl 為 ""(.*)""")]
    public void Given_FilteredItemDetailUrl(int index, string url)
    {
        throw new NotImplementedException(
            "TODO: 確保 DailyQueryViewModel.FilteredItems[index].DetailUrl 等於 url。" +
            "若不等於可在 Given 步驟中重置該筆。");
    }

    [Given(@"IBrowserLauncher 已被 Mock")]
    public void Given_BrowserLauncherMocked()
    {
        throw new NotImplementedException("TODO: 確認 ServiceProvider 中的 IBrowserLauncher 為 Mock 實例。");
    }

    [Given(@"檔案 ""(.*)"" 內容為 ""(.*)""")]
    public void Given_FileContent(string filePath, string content)
    {
        throw new NotImplementedException("TODO: 同 MonthlyCalendarSteps.Given_FileContentIs。");
    }

    // -------------------------------------------------------------
    // When
    // -------------------------------------------------------------

    [When(@"DailyQueryViewModel\.LoadCommand 執行完成")]
    public async Task When_DailyQueryLoadCompleted()
    {
        throw new NotImplementedException("TODO: await DailyQueryViewModel.LoadCommand.ExecuteAsync(null)。");
    }

    [When(@"DailyQueryViewModel\.Criteria 設定 KeywordQuery = ""(.*)""，並呼叫 ApplySearchCommand")]
    public void When_SetKeywordQueryAndApply(string query)
    {
        throw new NotImplementedException(
            "TODO: 取 DailyQueryViewModel.Criteria（record with init），用 with 表達式產生新 record 並指派回 Criteria 屬性，再呼叫 ApplySearchCommand.Execute(null)。");
    }

    [When(@"設定 DailyQueryViewModel\.Criteria 的屬性 ""(.*)"" 為 ""(.*)""，並呼叫 ApplySearchCommand")]
    public void When_SetCriteriaPropertyAndApply(string property, string value)
    {
        throw new NotImplementedException(
            "TODO: 反射或 switch 對應 SearchCriteria 屬性（TenderMethod / ProcurementType / ShowActiveOnly 等），" +
            "用 with 表達式更新後呼叫 ApplySearchCommand。");
    }

    [When(@"設定 Criteria\.BudgetMin = (\d+)、BudgetMax = (\d+)，並呼叫 ApplySearchCommand")]
    public void When_SetBudgetRangeAndApply(long min, long max)
    {
        throw new NotImplementedException("TODO: 更新 Criteria.BudgetMin/BudgetMax，呼叫 ApplySearchCommand。");
    }

    [When(@"設定 Criteria\.AnnouncementDateFrom = ""(.*)""、AnnouncementDateTo = ""(.*)""，並呼叫 ApplySearchCommand")]
    public void When_SetAnnouncementDateRangeAndApply(string from, string to)
    {
        throw new NotImplementedException("TODO: 同上但作用於 AnnouncementDateFrom/To。");
    }

    [When(@"設定 Criteria\.BidDeadlineFrom = ""(.*)""、BidDeadlineTo = ""(.*)""，並呼叫 ApplySearchCommand")]
    public void When_SetBidDeadlineRangeAndApply(string from, string to)
    {
        throw new NotImplementedException("TODO: 同上但作用於 BidDeadlineFrom/To。");
    }

    [When(@"設定 Criteria\.TenderMethod = ""(.*)""、ProcurementType = ""(.*)""、ShowActiveOnly = (true|false)，並呼叫 ApplySearchCommand")]
    public void When_SetMultipleCriteria(string tenderMethod, string procurementType, bool showActiveOnly)
    {
        throw new NotImplementedException("TODO: 一次更新多個屬性後呼叫 ApplySearchCommand。");
    }

    [When(@"設定 DailyQueryViewModel\.SortKey = (\w+)、SortDirection = (\w+)，並呼叫 ApplySearchCommand")]
    public void When_SetSortAndApply(string sortKey, string direction)
    {
        throw new NotImplementedException(
            "TODO: 設定 SortKey/SortDirection enum，呼叫 ApplySearchCommand。");
    }

    [When(@"設定 Criteria\.KeywordQuery = ""(.*)""，並呼叫 ApplySearchCommand")]
    public void When_SetCriteriaKeywordQueryAndApply(string query)
    {
        throw new NotImplementedException("TODO: 同 When_SetKeywordQueryAndApply。");
    }

    [When(@"呼叫 DailyQueryViewModel\.OpenDetailCommand\.Execute\(FilteredItems\[(\d+)\]\)")]
    public void When_OpenDetail(int index)
    {
        throw new NotImplementedException("TODO: 取 DailyQueryViewModel.FilteredItems[index]，呼叫 OpenDetailCommand.Execute。");
    }

    [When(@"呼叫 DailyQueryViewModel\.GoPreviousDayCommand\.Execute\(null\)")]
    public async Task When_GoPreviousDay()
    {
        throw new NotImplementedException("TODO: await GoPreviousDayCommand.ExecuteAsync(null)。");
    }

    [When(@"呼叫 DailyQueryViewModel\.GoNextDayCommand\.Execute\(null\)")]
    public async Task When_GoNextDay()
    {
        throw new NotImplementedException("TODO: await GoNextDayCommand.ExecuteAsync(null)。");
    }

    [When(@"呼叫 ShellViewModel\.NavigateBackToCalendarCommand\.Execute\(null\)")]
    public void When_NavigateBackToCalendar()
    {
        throw new NotImplementedException("TODO: 取 ShellViewModel，呼叫 NavigateBackToCalendarCommand.Execute(null)。");
    }

    [When(@"建立 DailyQueryViewModel\(date = (\d{4}-\d{2}-\d{2})\) 並呼叫 LoadCommand")]
    public async Task When_CreateAndLoadDailyQueryViewModel(string date)
    {
        throw new NotImplementedException(
            "TODO: 從 DI 容器以 ActivatorUtilities.CreateInstance 建立 DailyQueryViewModel，傳入 DateOnly.Parse(date)，呼叫 LoadCommand。");
    }

    // -------------------------------------------------------------
    // Then
    // -------------------------------------------------------------

    [Then(@"DailyQueryViewModel\.Date 應為 DateOnly\((\d+), (\d+), (\d+)\)")]
    public void Then_DailyQueryDate(int year, int month, int day)
    {
        throw new NotImplementedException("TODO: 斷言 DailyQueryViewModel.Date 等於 new DateOnly(...)。");
    }

    [Then(@"DailyQueryViewModel\.Items\.Count 應為 (\d+)")]
    public void Then_DailyQueryItemsCount(int expected)
    {
        throw new NotImplementedException("TODO: 斷言 Items.Count == expected。");
    }

    [Then(@"DailyQueryViewModel\.Criteria\.KeywordQuery 應為 null 或空字串")]
    public void Then_KeywordQueryEmpty()
    {
        throw new NotImplementedException("TODO: 斷言 Criteria.KeywordQuery 為 null 或 string.IsNullOrEmpty。");
    }

    [Then(@"DailyQueryViewModel\.FilteredItems\.Count 應為 (\d+)")]
    public void Then_FilteredItemsCount(int expected)
    {
        throw new NotImplementedException("TODO: 斷言 FilteredItems.Count == expected。");
    }

    [Then(@"FilteredItems\.Count 應為 (\d+)")]
    public void Then_FilteredItemsCountShort(int expected)
    {
        throw new NotImplementedException("TODO: 同上。");
    }

    [Then(@"FilteredItems 每筆的 TenderName 應包含子字串 ""(.*)""")]
    public void Then_FilteredItemsTenderNameContains(string substring)
    {
        throw new NotImplementedException("TODO: FilteredItems.All(x => x.TenderName.Contains(substring))。");
    }

    [Then(@"FilteredItems 每筆的 AgencyName 應包含 ""(.*)""")]
    public void Then_FilteredItemsAgencyNameContains(string substring)
    {
        throw new NotImplementedException("TODO: 同上但作用於 AgencyName。");
    }

    [Then(@"FilteredItems\[(\d+)\]\.TenderNo 應為 ""(.*)""")]
    public void Then_FilteredItemTenderNo(int index, string expected)
    {
        throw new NotImplementedException("TODO: 斷言 FilteredItems[index].TenderNo == expected。");
    }

    [Then(@"FilteredItems 每筆應符合 ""(.*)""")]
    public void Then_FilteredItemsMatchDescription(string description)
    {
        throw new NotImplementedException(
            "TODO: 解析描述文字（如 'TenderItem.TenderMethod == \"公開招標\"'），" +
            "用 switch 對應到具體斷言（建議在測試專案內維護一個描述-斷言對照表，避免反射）。");
    }

    [Then(@"FilteredItems 每筆的 BudgetAmount 應介於 \[(\d+), (\d+)\]（含端點）")]
    public void Then_FilteredItemsBudgetInRange(long min, long max)
    {
        throw new NotImplementedException("TODO: FilteredItems.All(x => x.BudgetAmount >= min && x.BudgetAmount <= max)。");
    }

    [Then(@"FilteredItems 每筆應同時符合：")]
    public void Then_FilteredItemsMatchAllConditions(Table table)
    {
        throw new NotImplementedException(
            "TODO: 遍歷 Table 中每行條件，逐一對 FilteredItems 全部斷言。" +
            "建議用 switch + lambda 對應條件文字到斷言。");
    }

    [Then(@"FilteredItems 應依 (\w+) 以 (\w+) 排序（null 值排於最後）")]
    public void Then_FilteredItemsSorted(string sortKey, string direction)
    {
        throw new NotImplementedException(
            "TODO: 取對應屬性的 selector（switch on sortKey），" +
            "用 IsOrdered(direction, NullsLast = true) 斷言。" +
            "對 BudgetAmount 等可空欄位，null 應排於最後。");
    }

    [Then(@"IBrowserLauncher\.Open 應被呼叫一次，url 參數為 ""(.*)""")]
    public void Then_BrowserLauncherCalledWithUrl(string url)
    {
        throw new NotImplementedException("TODO: Mock<IBrowserLauncher>.Verify(x => x.Open(url), Times.Once)。");
    }

    [Then(@"DailyQueryViewModel\.IsEmpty 應為 (true|false)")]
    public void Then_DailyQueryIsEmpty(bool expected)
    {
        throw new NotImplementedException("TODO: 斷言 DailyQueryViewModel.IsEmpty == expected。");
    }

    [Then(@"不應拋出任何例外")]
    public void Then_NoExceptionThrownInQuery()
    {
        throw new NotImplementedException("TODO: 從 ScenarioContext 取 When 期間捕捉的例外，斷言為 null。");
    }

    [Then(@"ShellViewModel\.CurrentDailyQueryVm 應為 null")]
    public void Then_CurrentDailyQueryVmNull()
    {
        throw new NotImplementedException("TODO: 取 ShellViewModel，斷言 CurrentDailyQueryVm == null。");
    }

    [Then(@"ShellViewModel\.CalendarVm\.Year 應為 (\d+)，Month 應為 (\d+)")]
    public void Then_ShellCalendarYearMonth(int year, int month)
    {
        throw new NotImplementedException("TODO: 斷言 CalendarVm.Year/Month。");
    }

    [Then(@"DailyQueryViewModel\.LoadError 應不為 null，訊息包含「(.*)」")]
    public void Then_LoadErrorContains(string substring)
    {
        throw new NotImplementedException("TODO: 斷言 LoadError != null 且 LoadError.Message.Contains(substring)。");
    }

    [Then(@"errors\.log 應記錄 CorruptedDataException")]
    public void Then_ErrorsLogContainsCorruptedDataException()
    {
        throw new NotImplementedException("TODO: 解析 errors.log 找 ExceptionDetail 含 'CorruptedDataException' 的條目。");
    }

    [Then(@"DailyQueryViewModel\.LoadError 應為 null（這不是錯誤情境）")]
    public void Then_LoadErrorIsNull()
    {
        throw new NotImplementedException("TODO: 斷言 DailyQueryViewModel.LoadError == null。");
    }
}
