// Auto-generated by sa-expert
// 共用 BeforeScenario / AfterScenario，負責測試環境隔離與 ScenarioContext 初始化
// BDD Framework: Reqnroll

using System;
using System.IO;
using Reqnroll;

namespace Tender.AcceptanceTests.Steps;

/// <summary>
/// 全域 Hook：每個 Scenario 前建立隔離的測試資料目錄；後清理。
/// ScenarioContext keys：
///   "TestDataRoot"   → string  (對應 Gherkin 的 ${TEST_DATA_ROOT})
///   "TestOutput"     → string  (對應 Gherkin 的 ${TEST_OUTPUT}，匯出檔案目錄)
///   "Clock"          → IClock  (FakeClock 實例，由各 Steps 設定 Now)
///   "ServiceProvider"→ IServiceProvider (DI container)
/// </summary>
[Binding]
public sealed class Hooks
{
    private readonly ScenarioContext _scenarioContext;

    public Hooks(ScenarioContext scenarioContext)
    {
        _scenarioContext = scenarioContext;
    }

    /// <summary>
    /// 每個 Scenario 開始前：
    /// 1. 建立臨時資料根目錄與輸出目錄
    /// 2. 註冊 IDataPaths 指向此目錄
    /// 3. 註冊 FakeClock、Mock 化的 ICrawler、IBrowserLauncher、ITaskSchedulerAdapter 等外部依賴
    /// 4. 註冊 Tender.Core / Tender.Storage 的真實實作
    /// </summary>
    [BeforeScenario(Order = 0)]
    public void BeforeScenario_InitializeTestEnvironment()
    {
        throw new NotImplementedException(
            "TODO: " +
            "1) Path.Combine(Path.GetTempPath(), \"tender-tests\", Guid.NewGuid().ToString()) 建立 TestDataRoot；" +
            "2) 同方式建立 TestOutput；" +
            "3) 用 Microsoft.Extensions.DependencyInjection 註冊 IClock=FakeClock、IDataPaths=指向 TestDataRoot 的實作、ITenderRepository、IDailySummaryRepository、ICrawlRunLogRepository、IErrorLogWriter、ISearchService、IKeywordMatcher、ITaiwanDateConverter；" +
            "4) ICrawler、IBrowserLauncher、ICrawlerLauncher、ISaveFileDialogService、IErrorSummaryDialog、ITaskSchedulerAdapter 註冊為 Moq.Mock 並存入 ScenarioContext；" +
            "5) ScenarioContext.Set 上述目錄字串與 ServiceProvider。");
    }

    /// <summary>
    /// 每個 Scenario 結束後：清理臨時目錄。
    /// </summary>
    [AfterScenario(Order = 100)]
    public void AfterScenario_CleanupTestEnvironment()
    {
        throw new NotImplementedException(
            "TODO: 從 ScenarioContext 取出 TestDataRoot 與 TestOutput，try/catch 刪除，避免測試殘留檔案影響後續執行。");
    }

    /// <summary>
    /// Background 共用步驟：「已在測試目錄下初始化資料根目錄 ...」
    /// 由於 BeforeScenario 已建立目錄，此步驟主要驗證並把字串注入 ScenarioContext.
    /// </summary>
    [Given(@"已在測試目錄下初始化資料根目錄 ""(.*)""")]
    public void Given_TestDataRootInitialized(string pathTemplate)
    {
        throw new NotImplementedException(
            "TODO: 用 ResolvePath 把 ${TEST_DATA_ROOT} placeholder 換成實際 ScenarioContext[\"TestDataRoot\"]，並驗證目錄存在。");
    }

    [Given(@"IDataPaths\.DataRoot 指向 ""(.*)""")]
    public void Given_DataPathsDataRootPointsTo(string pathTemplate)
    {
        throw new NotImplementedException(
            "TODO: 從 ServiceProvider 取得 IDataPaths，驗證 DataRoot 屬性等於 ResolvePath(pathTemplate)。");
    }

    [Given(@"系統時區固定為 ""(.*)""")]
    public void Given_TimeZoneFixedTo(string timeZoneId)
    {
        throw new NotImplementedException(
            "TODO: 把 timeZoneId 存入 ScenarioContext，後續 FakeClock 與 IClock.Today 應以此時區計算。" +
            "注意 Windows 上對應名稱為 \"Taipei Standard Time\"。");
    }

    [Given(@"IClock\.Now 回傳 ""(.*)""")]
    public void Given_ClockNowReturns(string isoDateTime)
    {
        throw new NotImplementedException(
            "TODO: ScenarioContext[\"Clock\"] as FakeClock；fakeClock.Now = DateTimeOffset.Parse(isoDateTime)。");
    }

    [Given(@"IAppSettingsRepository\.LoadAsync\(\) 回傳預設值，targetTenderMethods 為 \[(.+)\]")]
    public void Given_AppSettingsTargetTenderMethods(string methodsCsv)
    {
        throw new NotImplementedException(
            "TODO: 解析 methodsCsv 為 string[]，建立 AppSettings 實例，Mock IAppSettingsRepository.LoadAsync 回傳該值。");
    }

    [Given(@"ICrawler 已被 Mock，可由測試控制回傳的 FetchedPage\[\]")]
    public void Given_CrawlerIsMocked()
    {
        throw new NotImplementedException(
            "TODO: 確認 ServiceProvider 中的 ICrawler 是 Mock<ICrawler>，存入 ScenarioContext 供後續 Steps 設定。");
    }

    /// <summary>
    /// 共用工具：把 Gherkin 中的 ${TEST_DATA_ROOT}、${TEST_OUTPUT} 替換為實際路徑。
    /// </summary>
    public static string ResolvePath(string pathTemplate, ScenarioContext ctx)
    {
        throw new NotImplementedException(
            "TODO: pathTemplate.Replace(\"${TEST_DATA_ROOT}\", ctx.Get<string>(\"TestDataRoot\")).Replace(\"${TEST_OUTPUT}\", ctx.Get<string>(\"TestOutput\"))。");
    }
}
