// Auto-generated by sa-expert
// Feature: 關鍵字快速篩選
// Source: sa/engineer_features/keyword_filter.feature
// Module type: WPF Desktop + Core Keywords
// BDD Framework: Reqnroll

using System;
using System.Threading.Tasks;
using Reqnroll;

namespace Tender.AcceptanceTests.Steps;

[Binding]
public sealed class KeywordFilterSteps
{
    private readonly ScenarioContext _scenarioContext;

    public KeywordFilterSteps(ScenarioContext scenarioContext)
    {
        _scenarioContext = scenarioContext;
    }

    // -------------------------------------------------------------
    // Given
    // -------------------------------------------------------------

    [Given(@"IKeywordsRepository\.LoadAsync\(\) 回傳預設 KeywordSet（含資訊系統、XR/AI、資安/無障礙、ESG/碳管理、業務雜項、智慧管考、倉儲自動化、地區、指定機關共 9 個 Group）")]
    public void Given_KeywordsRepositoryReturnsDefaultSet()
    {
        throw new NotImplementedException(
            "TODO: 從 settings/keywords.json 預設模板載入 KeywordSet，Mock IKeywordsRepository.LoadAsync 回傳該值。" +
            "此預設模板可放於 tests/Tender.AcceptanceTests/TestData/default-keywords.json。");
    }

    [Given(@"DailyQueryViewModel 已載入 Date = (\d{4}-\d{2}-\d{2})")]
    public void Given_DailyQueryViewModelLoadedForDate(string date)
    {
        throw new NotImplementedException(
            "TODO: 同 DailyQuerySteps 的對應 Given；確保 DailyQueryViewModel.Items 已載入。");
    }

    [Given(@"Items 中 TenderName 含 ""(.*)"" 的標案有 (\d+) 筆")]
    public void Given_ItemsTenderNameContainsCount(string keyword, int count)
    {
        throw new NotImplementedException("TODO: 同 DailyQuerySteps.Given_ItemsTenderNameContainsCount。");
    }

    [Given(@"Items 中 AgencyName 含 ""(.*)"" 的筆數為 (\d+)")]
    public void Given_ItemsAgencyNameCount(string keyword, int count)
    {
        throw new NotImplementedException("TODO: 同 DailyQuerySteps.Given_ItemsAgencyNameContainsCount。");
    }

    [Given(@"KeywordSet 中 ""(.*)"" 的 TargetField 為 ""(.*)""")]
    public void Given_KeywordTargetField(string keyword, string targetField)
    {
        throw new NotImplementedException(
            "TODO: 確認 KeywordSet 中該 keyword 的 TargetField == targetField，必要時調整 IKeywordsRepository Mock 的回傳。");
    }

    [Given(@"Items 中 \(AgencyName 含 ""(.*)""\) 或 \(TenderName 含 ""(.*)""\) 的筆數為 (\d+)")]
    public void Given_ItemsAgencyOrTenderNameContains(string a, string b, int count)
    {
        throw new NotImplementedException(
            "TODO: 重新產生 tenders.json，確保 (AgencyName 含 a 或 TenderName 含 b) 的筆數恰為 count。");
    }

    [Given(@"上述兩組之中重疊（同時含 AI 與 雲端）的標案有 (\d+) 筆")]
    public void Given_OverlapCount(int count)
    {
        throw new NotImplementedException("TODO: 確保前面兩組標案的交集恰為 count 筆。");
    }

    [Given(@"已呼叫 ToggleKeywordButtonCommand\.Execute\(""(.*)""\)，FilteredItems\.Count 為 (\d+)")]
    public void Given_KeywordButtonToggled(string keyword, int expectedCount)
    {
        throw new NotImplementedException(
            "TODO: 呼叫 ToggleKeywordButtonCommand.Execute(keyword)，斷言 FilteredItems.Count 等於 expectedCount。");
    }

    [Given(@"一個 TenderItem，TenderName = ""(.*)""")]
    public void Given_TenderItemWithName(string name)
    {
        throw new NotImplementedException(
            "TODO: 建立 TenderItem 實例，TenderName = name，其餘必填欄位用預設值；存入 ScenarioContext。");
    }

    [Given(@"Items 中無任何 TenderName 含 ""(.*)"" 的標案")]
    public void Given_NoItemsContainKeyword(string keyword)
    {
        throw new NotImplementedException("TODO: 重新產生 tenders.json，確保 TenderName 全部不含 keyword。");
    }

    [Given(@"Items 中 TenderName 含 ""(.*)"" 且也含 ""(.*)"" 的筆數為 (\d+)")]
    public void Given_ItemsTenderNameContainsBoth(string a, string b, int count)
    {
        throw new NotImplementedException("TODO: 重新產生 tenders.json，確保 TenderName 同時含 a 與 b 的筆數恰為 count。");
    }

    // -------------------------------------------------------------
    // When
    // -------------------------------------------------------------

    [When(@"呼叫 DailyQueryViewModel\.ToggleKeywordButtonCommand\.Execute\(""(.*)""\)")]
    public void When_ToggleKeywordButton(string keyword)
    {
        throw new NotImplementedException(
            "TODO: 取 DailyQueryViewModel，呼叫 ToggleKeywordButtonCommand.Execute(keyword)。");
    }

    [When(@"呼叫 ToggleKeywordButtonCommand\.Execute\(""(.*)""\)")]
    public void When_ToggleKeywordButtonShort(string keyword)
    {
        throw new NotImplementedException("TODO: 同上。");
    }

    [When(@"呼叫 IKeywordMatcher\.Match\(item, predefinedKeywordSet\)")]
    public void When_KeywordMatcherMatch()
    {
        throw new NotImplementedException(
            "TODO: 從 ScenarioContext 取 TenderItem，從 DI 取 IKeywordMatcher，呼叫 Match(item, predefinedKeywordSet)；" +
            "把回傳的 IReadOnlyList<string> 存入 ScenarioContext。");
    }

    [When(@"呼叫 DailyQueryViewModel\.ClearKeywordFilterCommand\.Execute\(null\)")]
    public void When_ClearKeywordFilter()
    {
        throw new NotImplementedException("TODO: 呼叫 ClearKeywordFilterCommand.Execute(null)。");
    }

    [When(@"設定 Criteria\.KeywordQuery = ""(.*)""，並呼叫 ApplySearchCommand")]
    public void When_SetKeywordQueryAndApply(string query)
    {
        throw new NotImplementedException("TODO: 同 DailyQuerySteps 對應 When。");
    }

    // -------------------------------------------------------------
    // Then
    // -------------------------------------------------------------

    [Then(@"DailyQueryViewModel\.Criteria\.ActiveKeywordButtons 應包含 ""(.*)""")]
    public void Then_ActiveKeywordButtonsContains(string keyword)
    {
        throw new NotImplementedException("TODO: 取 DailyQueryViewModel.Criteria.ActiveKeywordButtons，斷言 Contains(keyword)。");
    }

    [Then(@"DailyQueryViewModel\.Criteria\.ActiveKeywordButtons 應為 \[""(.*)"", ""(.*)""\]")]
    public void Then_ActiveKeywordButtonsExactly(string a, string b)
    {
        throw new NotImplementedException("TODO: 斷言 ActiveKeywordButtons 序列恰為 [a, b]（順序不限）。");
    }

    [Then(@"DailyQueryViewModel\.Criteria\.ActiveKeywordButtons 應為空陣列")]
    public void Then_ActiveKeywordButtonsEmpty()
    {
        throw new NotImplementedException("TODO: 斷言 ActiveKeywordButtons.Count == 0。");
    }

    [Then(@"FilteredItems\.Count 應為 (\d+)（(\d+) \+ (\d+) - (\d+)）")]
    public void Then_FilteredItemsCountWithBreakdown(int expected, int a, int b, int overlap)
    {
        throw new NotImplementedException(
            "TODO: 斷言 FilteredItems.Count == expected，且 expected == a + b - overlap（驗算）。");
    }

    [Then(@"FilteredItems\.Count 應為 (\d+)")]
    public void Then_FilteredItemsCount(int expected)
    {
        throw new NotImplementedException("TODO: 斷言 FilteredItems.Count == expected。");
    }

    [Then(@"FilteredItems 每筆的 MatchedKeywords 應包含 ""(.*)""")]
    public void Then_FilteredItemsMatchedKeywordsContains(string keyword)
    {
        throw new NotImplementedException("TODO: FilteredItems.All(x => x.MatchedKeywords.Contains(keyword))。");
    }

    [Then(@"FilteredItems 每筆的 AgencyName 應包含 ""(.*)""")]
    public void Then_FilteredItemsAgencyNameContains(string substring)
    {
        throw new NotImplementedException("TODO: FilteredItems.All(x => x.AgencyName.Contains(substring))。");
    }

    [Then(@"FilteredItems 每筆應符合 \(AgencyName 含 ""(.*)""\) 或 \(TenderName 含 ""(.*)""\)")]
    public void Then_FilteredItemsAnyOf(string a, string b)
    {
        throw new NotImplementedException("TODO: FilteredItems.All(x => x.AgencyName.Contains(a) || x.TenderName.Contains(b))。");
    }

    [Then(@"同時包含兩個關鍵字的那 (\d+) 筆，其 MatchedKeywords 應同時包含 ""(.*)"" 與 ""(.*)""")]
    public void Then_OverlapItemsHaveBothMatched(int count, string a, string b)
    {
        throw new NotImplementedException(
            "TODO: 從 FilteredItems 找 (TenderName 同時含 a 與 b) 的子集，斷言子集大小 == count，且每筆 MatchedKeywords 同時含 a 與 b。");
    }

    [Then(@"回傳的命中清單應包含 ""(.*)""、""(.*)""、""(.*)""、""(.*)""、""(.*)""")]
    public void Then_MatchResultContainsAll(string a, string b, string c, string d, string e)
    {
        throw new NotImplementedException(
            "TODO: 從 ScenarioContext 取 IKeywordMatcher.Match 的回傳清單，斷言含 a、b、c、d、e 五個項目。");
    }

    [Then(@"該 TenderItem 經 ICrawlerOrchestrator 處理後，寫入 tenders\.json 的 MatchedKeywords 應包含上述項目")]
    public void Then_AfterOrchestratorMatchedKeywordsContains()
    {
        throw new NotImplementedException(
            "TODO: 將該 TenderItem 透過 Mock<ICrawler> 注入回傳，呼叫 ICrawlerOrchestrator.RunAsync，" +
            "讀取寫入的 tenders.json，找對應 SourcePk 的 TenderItem，斷言 MatchedKeywords 包含全部關鍵字。");
    }

    [Then(@"FilteredItems 每筆應同時符合：")]
    public void Then_FilteredItemsMatchTable(Table table)
    {
        throw new NotImplementedException("TODO: 同 DailyQuerySteps.Then_FilteredItemsMatchAllConditions。");
    }

    [Then(@"FilteredItems 每筆的 TenderName 或 AgencyName 或 TenderNo 應同時包含子字串 ""(.*)"" 與 ""(.*)""")]
    public void Then_FilteredItemsContainBoth(string a, string b)
    {
        throw new NotImplementedException(
            "TODO: 對每筆 FilteredItems，檢查 (TenderName + AgencyName + TenderNo) 是否同時含 a 與 b。");
    }

    [Then(@"DailyQueryViewModel\.IsEmpty 應為 (true|false)")]
    public void Then_DailyQueryIsEmpty(bool expected)
    {
        throw new NotImplementedException("TODO: 斷言 DailyQueryViewModel.IsEmpty。");
    }

    [Then(@"DailyQueryViewModel\.LoadError 應為 null")]
    public void Then_LoadErrorNull()
    {
        throw new NotImplementedException("TODO: 斷言 DailyQueryViewModel.LoadError == null。");
    }
}
