// Auto-generated by sa-expert
// Feature: 月份行事曆首頁
// Source: sa/engineer_features/monthly_calendar.feature
// Module type: WPF Desktop + Storage
// BDD Framework: Reqnroll

using System;
using System.Threading.Tasks;
using Reqnroll;

namespace Tender.AcceptanceTests.Steps;

[Binding]
public sealed class MonthlyCalendarSteps
{
    private readonly ScenarioContext _scenarioContext;

    public MonthlyCalendarSteps(ScenarioContext scenarioContext)
    {
        _scenarioContext = scenarioContext;
    }

    // -------------------------------------------------------------
    // Given
    // -------------------------------------------------------------

    [Given(@"IDailySummaryRepository 已被注入，讀取真實檔案系統")]
    public void Given_DailySummaryRepositoryUsesRealFs()
    {
        throw new NotImplementedException(
            "TODO: 確認 ServiceProvider 中的 IDailySummaryRepository 是真實實作（非 Mock），讀寫指向 TestDataRoot。");
    }

    [Given(@"檔案 ""(.*)"" 存在，TotalCount 為 (\d+)，LastRunStatus 為 (\w+)")]
    public void Given_SummaryFileWithTotalAndStatus(string filePath, int totalCount, string status)
    {
        throw new NotImplementedException(
            "TODO: ResolvePath → 寫入 DailySummary JSON，TotalCount + LastRunStatus 設為對應值，LastRunAt 預設為 FakeClock.Now。");
    }

    [Given(@"檔案 ""(.*)"" 存在，LastRunStatus 為 (\w+)，ErrorMessage 為 ""(.*)""")]
    public void Given_SummaryFileFailedWithMessage(string filePath, string status, string errorMessage)
    {
        throw new NotImplementedException("TODO: 寫入失敗狀態的 summary.json，含 ErrorMessage。");
    }

    [Given(@"檔案 ""(.*)"" 存在，LastRunStatus 為 (\w+)")]
    public void Given_SummaryFileWithStatus(string filePath, string status)
    {
        throw new NotImplementedException("TODO: 寫入指定狀態的 summary.json。");
    }

    [Given(@"檔案 ""(.*)"" 不存在")]
    public void Given_FileNotExist(string filePath)
    {
        throw new NotImplementedException("TODO: ResolvePath 後若檔案存在則刪除（與 DailyCrawlSteps 共用，重複定義也可由 Reqnroll 自動消歧）。");
    }

    [Given(@"檔案 ""(.*)"" 內容為 ""(.*)""")]
    public void Given_FileContentIs(string filePath, string content)
    {
        throw new NotImplementedException("TODO: ResolvePath → File.WriteAllText(path, content)。");
    }

    [Given(@"MonthlyCalendarView 已載入，Date 為 (\d{4}-\d{2}-\d{2}) 的 Summary\.TotalCount 為 (\d+)")]
    public void Given_CalendarViewLoadedWithDayCount(string date, int totalCount)
    {
        throw new NotImplementedException(
            "TODO: 寫入該日 summary.json，呼叫 IMonthlyCalendarService.LoadMonthAsync 載入後存入 ScenarioContext。");
    }

    [Given(@"MonthlyCalendarViewModel 目前 Year = (\d+)，Month = (\d+)")]
    public void Given_CalendarViewModelAt(int year, int month)
    {
        throw new NotImplementedException(
            "TODO: 從 ServiceProvider 取得 MonthlyCalendarViewModel，設定 Year/Month。");
    }

    [Given(@"2026 年 5 月所有日期的 summary\.json 加總 TotalCount 為 (\d+)")]
    public void Given_MayTotalCount(int total)
    {
        throw new NotImplementedException("TODO: 自動分配 31 日的 TotalCount 加總為指定值，依序寫入 summary.json。");
    }

    [Given(@"全系統最近一次成功爬蟲完成於 (.+)（透過所有 summary\.json 的 LastRunAt 取最大值且 LastRunStatus = Success）")]
    public void Given_GlobalLatestSuccessAt(string isoDateTime)
    {
        throw new NotImplementedException("TODO: 在 5 月某日 summary.json 設定 LastRunAt = isoDateTime, LastRunStatus = Success。");
    }

    [Given(@"資料根目錄 ""(.*)"" 為空，無任何月份資料夾")]
    public void Given_EmptyDataRoot(string pathTemplate)
    {
        throw new NotImplementedException("TODO: ResolvePath，刪除其中所有子目錄，留下空 root。");
    }

    [Given(@"2026 年 5 月所有日期皆有 summary\.json 與 tenders\.json")]
    public void Given_FullMayData()
    {
        throw new NotImplementedException("TODO: 為 2026-05 每一天寫入 summary.json 與 tenders.json（內容可為空 Items）。");
    }

    [Given(@"ITenderRepository 被替換為 SpyTenderRepository（記錄 LoadAsync 呼叫次數）")]
    public void Given_SpyTenderRepository()
    {
        throw new NotImplementedException("TODO: 在 DI 容器中以 SpyTenderRepository 取代真實實作，並把 spy 存入 ScenarioContext。");
    }

    [Given(@"其他日期的 summary\.json 皆正常")]
    public void Given_OtherDaysSummariesNormal()
    {
        throw new NotImplementedException("TODO: 為 5 月其他日期寫入有效 summary.json。");
    }

    [Given(@"IErrorSummaryDialog 已被 Mock")]
    public void Given_ErrorSummaryDialogMocked()
    {
        throw new NotImplementedException("TODO: 確認 ServiceProvider 中的 IErrorSummaryDialog 為 Mock 實例。");
    }

    // -------------------------------------------------------------
    // When
    // -------------------------------------------------------------

    [When(@"建立 ShellViewModel 並呼叫 LoadAsync\(\)")]
    public async Task When_CreateAndLoadShellViewModel()
    {
        throw new NotImplementedException(
            "TODO: 從 DI 取得 ShellViewModel，呼叫 LoadAsync()，將實例存入 ScenarioContext。");
    }

    [When(@"呼叫 ShellViewModel\.LoadAsync\(\)")]
    public async Task When_CallShellViewModelLoad()
    {
        throw new NotImplementedException("TODO: 同上但對既有實例呼叫 LoadAsync。");
    }

    [When(@"呼叫 IMonthlyCalendarService\.LoadMonthAsync\((\d+), (\d+)\)")]
    public async Task When_LoadMonthAsync(int year, int month)
    {
        throw new NotImplementedException(
            "TODO: 從 DI 取得 IMonthlyCalendarService，呼叫 LoadMonthAsync，把回傳的 MonthlyCalendarView 存入 ScenarioContext。");
    }

    [When(@"呼叫 ShellViewModel\.NavigateToDayCommand\.Execute\(DateOnly\((\d+), (\d+), (\d+)\)\)")]
    public void When_NavigateToDay(int year, int month, int day)
    {
        throw new NotImplementedException(
            "TODO: 從 ScenarioContext 取得 ShellViewModel，呼叫 NavigateToDayCommand.Execute(new DateOnly(year, month, day))。");
    }

    [When(@"呼叫 (\w+Command)\.Execute\(null\)")]
    public void When_ExecuteCommand(string commandName)
    {
        throw new NotImplementedException(
            "TODO: 反射或 switch 找到對應 ICommand（GoPreviousMonthCommand、GoNextMonthCommand、GoToCurrentMonthCommand 等），呼叫 Execute(null)。");
    }

    [When(@"呼叫 MonthlyCalendarViewModel\.ShowFailedSummaryCommand\.Execute\(DateOnly\((\d+), (\d+), (\d+)\)\)")]
    public async Task When_ShowFailedSummary(int year, int month, int day)
    {
        throw new NotImplementedException(
            "TODO: 呼叫 ShowFailedSummaryCommand.Execute(new DateOnly(year, month, day))，等待 async 完成。");
    }

    // -------------------------------------------------------------
    // Then
    // -------------------------------------------------------------

    [Then(@"ShellViewModel\.CalendarVm\.Year 應為 (\d+)")]
    public void Then_CalendarVmYear(int expected)
    {
        throw new NotImplementedException("TODO: 從 ScenarioContext 取得 ShellViewModel，斷言 CalendarVm.Year。");
    }

    [Then(@"ShellViewModel\.CalendarVm\.Month 應為 (\d+)")]
    public void Then_CalendarVmMonth(int expected)
    {
        throw new NotImplementedException("TODO: 同上斷言 Month。");
    }

    [Then(@"ShellViewModel\.CalendarVm\.View\.Days 中 Date 為 (\d{4}-\d{2}-\d{2}) 的項目應被標示為今日（測試透過 ViewModel 屬性或 IsToday 判斷）")]
    public void Then_DayMarkedAsToday(string date)
    {
        throw new NotImplementedException("TODO: 找對應 MonthlyCalendarDay 並驗證 IsToday（如有）或比對 FakeClock.Today。");
    }

    [Then(@"回傳的 MonthlyCalendarView\.Days 中 Date 為 (\d{4}-\d{2}-\d{2}) 的 Summary\.TotalCount 應為 (\d+)")]
    public void Then_DaySummaryTotalCount(string date, int expected)
    {
        throw new NotImplementedException(
            "TODO: 從 ScenarioContext 取得 MonthlyCalendarView，找 DateOnly.Parse(date) 對應 Day，斷言 Summary.TotalCount。");
    }

    [Then(@"Days 中 Date 為 (\d{4}-\d{2}-\d{2}) 的 Summary\.TotalCount 應為 (\d+)")]
    public void Then_DaySummaryTotalCountShort(string date, int expected)
    {
        throw new NotImplementedException("TODO: 同上。");
    }

    [Then(@"Days 中 Date 為 (\d{4}-\d{2}-\d{2}) 的 Summary 應為 null")]
    public void Then_DaySummaryNull(string date)
    {
        throw new NotImplementedException("TODO: 找對應 Day，斷言 Summary 為 null。");
    }

    [Then(@"Days 中 Date 為 (\d{4}-\d{2}-\d{2}) 的 Summary\.LastRunStatus 應為 RunStatus\.(\w+)")]
    public void Then_DayLastRunStatus(string date, string status)
    {
        throw new NotImplementedException("TODO: 找對應 Day，斷言 Summary.LastRunStatus 為對應 RunStatus enum。");
    }

    [Then(@"Days 中 Date 為 (\d{4}-\d{2}-\d{2}) 的 IsCorrupted 應為 (true|false)")]
    public void Then_DayIsCorrupted(string date, bool expected)
    {
        throw new NotImplementedException("TODO: 找對應 Day，斷言 IsCorrupted。");
    }

    [Then(@"MonthlyCalendarViewModel 對該日的可點擊狀態應為 (true|false)")]
    public void Then_DayClickable(bool expected)
    {
        throw new NotImplementedException("TODO: 取對應 Day 透過 ViewModel 提供的 IsClickable 屬性驗證。");
    }

    [Then(@"MonthlyCalendarViewModel 對該日的 IsFailed 屬性應為 (true|false)")]
    public void Then_DayIsFailed(bool expected)
    {
        throw new NotImplementedException("TODO: 取對應 Day 的 IsFailed 屬性驗證。");
    }

    [Then(@"ShellViewModel\.CurrentDailyQueryVm 應不為 null")]
    public void Then_CurrentDailyQueryVmNotNull()
    {
        throw new NotImplementedException("TODO: 取 ShellViewModel，斷言 CurrentDailyQueryVm != null。");
    }

    [Then(@"CurrentDailyQueryVm\.Date 應為 DateOnly\((\d+), (\d+), (\d+)\)")]
    public void Then_CurrentDailyQueryVmDate(int year, int month, int day)
    {
        throw new NotImplementedException("TODO: 斷言 ShellViewModel.CurrentDailyQueryVm.Date。");
    }

    [Then(@"SideSummaryViewModel\.MonthlyTotalCount 應為 (\d+)")]
    public void Then_MonthlyTotalCount(int expected)
    {
        throw new NotImplementedException("TODO: 取 ShellViewModel.SideSummaryVm 的 MonthlyTotalCount。");
    }

    [Then(@"SideSummaryViewModel\.TodayCount 應為 (\d+)")]
    public void Then_TodayCount(int expected)
    {
        throw new NotImplementedException("TODO: 同上 TodayCount。");
    }

    [Then(@"SideSummaryViewModel\.LastUpdatedAt 應為 ""(.*)""")]
    public void Then_LastUpdatedAt(string isoDateTime)
    {
        throw new NotImplementedException(
            "TODO: 取 SideSummaryVm.LastUpdatedAt（DateTimeOffset?），斷言等於 DateTimeOffset.Parse(isoDateTime)。");
    }

    [Then(@"SideSummaryViewModel\.LastUpdatedAt 應為 null（UI 顯示為「尚未更新」）")]
    public void Then_LastUpdatedAtNull()
    {
        throw new NotImplementedException("TODO: 斷言 SideSummaryVm.LastUpdatedAt 為 null。");
    }

    [Then(@"MonthlyCalendarViewModel\.Year 應為 (\d+)")]
    public void Then_CalendarVmYearOnly(int expected)
    {
        throw new NotImplementedException("TODO: 同 Then_CalendarVmYear，但作用於獨立的 MonthlyCalendarViewModel。");
    }

    [Then(@"MonthlyCalendarViewModel\.Month 應為 (\d+)")]
    public void Then_CalendarVmMonthOnly(int expected)
    {
        throw new NotImplementedException("TODO: 同上 Month。");
    }

    [Then(@"IDailySummaryRepository\.LoadAsync 應被呼叫至少一次")]
    public void Then_DailySummaryLoadCalled()
    {
        throw new NotImplementedException("TODO: 透過 spy 或 Mock.Verify 驗證 IDailySummaryRepository.LoadAsync 至少被呼叫一次。");
    }

    [Then(@"SpyTenderRepository\.LoadAsync 的呼叫次數應為 0")]
    public void Then_SpyTenderRepositoryNotCalled()
    {
        throw new NotImplementedException("TODO: 從 ScenarioContext 取得 SpyTenderRepository，斷言 LoadAsync 呼叫次數為 0。");
    }

    [Then(@"不應拋出例外")]
    public void Then_NoExceptionThrown()
    {
        throw new NotImplementedException("TODO: 從 ScenarioContext 取出 When 期間捕捉的例外，斷言為 null。");
    }

    [Then(@"errors\.log 應含一行 Severity 為 ""(.*)"" 的解析失敗紀錄")]
    public void Then_ErrorsLogContainsParseFailureWarning(string severity)
    {
        throw new NotImplementedException("TODO: 解析 errors.log 找對應 Severity + 解析失敗訊息的條目。");
    }

    [Then(@"其他日期的 Summary\.TotalCount 應正常顯示")]
    public void Then_OtherDaysSummaryShown()
    {
        throw new NotImplementedException("TODO: 取 MonthlyCalendarView.Days，排除 IsCorrupted 者後，其餘 Summary 不為 null。");
    }

    [Then(@"MonthlyCalendarView\.Days 中所有 Summary 應為 null")]
    public void Then_AllSummariesNull()
    {
        throw new NotImplementedException("TODO: Days.All(d => d.Summary == null)。");
    }

    [Then(@"IErrorSummaryDialog\.ShowAsync 應被呼叫一次")]
    public void Then_ErrorSummaryDialogShown()
    {
        throw new NotImplementedException("TODO: Mock<IErrorSummaryDialog>.Verify(x => x.ShowAsync(It.IsAny<...>(), ...), Times.Once)。");
    }

    [Then(@"呼叫時 errorMessage 參數應為 ""(.*)""")]
    public void Then_ErrorSummaryDialogMessageEquals(string message)
    {
        throw new NotImplementedException("TODO: 用 Moq 的 Capture 或 It.Is<string>(s => s == message) 驗證。");
    }
}
