# language: en
# Generated by sa-expert
# Source: pm/features/crawl_logging.feature
# Project scan date: 2026-05-08
# Module type: Storage (Tender.Storage) + Crawler (Tender.Crawler) + Desktop (Tender.Desktop)
# Architecture: ICrawlerOrchestrator → ICrawlRunLogRepository / IErrorLogWriter → JSON Lines
# Step Definitions: tests/Tender.AcceptanceTests/Steps/CrawlLoggingSteps.cs

Feature: 更新紀錄與錯誤日誌
  # 業務模組：Bounded Context 7 - Crawl Logging
  # 紀錄寫入：Tender.Storage.Repositories.ICrawlRunLogRepository / IErrorLogWriter
  # 紀錄呈現：Tender.Desktop.ViewModels.SideSummaryViewModel + IErrorSummaryDialog
  # errors.log 格式：JSON Lines（每行一筆 ErrorLogEntry，已決議）

  Background:
    Given 已在測試目錄下初始化資料根目錄 "${TEST_DATA_ROOT}/TenderSearch/data/"
    And IClock.Now 回傳 "2026-05-08T17:00:00+08:00"
    And 系統時區固定為 "Asia/Taipei"

  # ----------------------------------------------------------
  # 成功路徑
  # ----------------------------------------------------------
  Scenario: 每次成功執行皆寫入 crawl-runs.json
    Given 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/crawl-runs.json" 不存在
    And ICrawler Mock 回傳 5 筆有效標案
    When 執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate = 2026-05-08 })
    Then 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/crawl-runs.json" 應存在
    And 反序列化後 CrawlRunLog.Date 應為 "2026-05-08"
    And CrawlRunLog.Runs 應有 1 筆
    And Runs[0] 的欄位應齊全：RunId、TargetDate、TriggerSource、StartedAt、FinishedAt、Status、InsertedCount、UpdatedCount、SkippedCount、ErrorMessage
    And Runs[0].Status 應為 RunStatus.Success
    And Runs[0].ErrorMessage 應為 null

  Scenario: 同日多次執行皆累積於 crawl-runs.json
    Given 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/crawl-runs.json" 已含 1 筆 Status = Success 的 Run，RunId 為 "20260508-170000"
    And ICrawler Mock 回傳 3 筆有效標案
    When 執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Manual, TargetDate = 2026-05-08 })
    Then crawl-runs.json 反序列化後 Runs.Count 應為 2
    And Runs[1].RunId 應不等於 Runs[0].RunId
    And Runs[1].StartedAt 應晚於 Runs[0].StartedAt（時間順序遞增）
    And Runs[1].TriggerSource 應為 Manual

  Scenario: 摘要應呈現當次新增/更新/略過筆數
    Given 既有 tenders.json 含 SourcePk "PK001"~"PK003"
    And ICrawler Mock 回傳 10 筆標案：5 筆全新 SourcePk + 2 筆 SourcePk = "PK001"、"PK002"（更新內容）+ 3 筆 SourcePk = "PK003"~"PK003"（其中 1 筆完全相同無變更，視為 skipped；其餘 2 筆視為新 SourcePk）
    # 為避免 Examples 解讀模糊，直接以 MergeResult 期望值定義
    And 預期 ITenderRepository.MergeDailySnapshotAsync 回傳 MergeResult { Inserted = 5, Updated = 2, Skipped = 3 }
    When 執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Manual, TargetDate = 2026-05-08 })
    Then crawl-runs.json 最新一筆 Run 應記錄 InsertedCount = 5、UpdatedCount = 2、SkippedCount = 3
    And summary.json 的 InsertedCount、UpdatedCount、SkippedCount 應與最新 Run 相同
    And summary.json 的 TotalCount 應為合併後 tenders.json 的 Items.Count

  # ----------------------------------------------------------
  # 失敗路徑
  # ----------------------------------------------------------
  Scenario: 整批失敗時寫入 failed run 紀錄與錯誤日誌
    Given ICrawler Mock 在所有重試（maxRetries=3）皆拋 CrawlNetworkException(message = "Connection timeout")
    When 執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate = 2026-05-08 })
    Then crawl-runs.json 最新一筆 Run.Status 應為 RunStatus.Failed
    And Run.ErrorMessage 應包含子字串 "Connection timeout"
    And errors.log 應至少含一行 ErrorLogEntry，Severity = "error"，Source = "crawler"，Message 包含 "Connection timeout"

  Scenario: 部分頁面解析失敗仍保留錯誤紀錄
    Given ICrawler Mock 回傳 5 個 FetchedPage，第 3 頁的 Html 會觸發 ITenderParser.Parse 拋 ParseException
    When 執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate = 2026-05-08 })
    Then errors.log 應含一行 ErrorLogEntry，Severity = "warning"，Page = 3，Message 包含 "ParseException"
    And crawl-runs.json 最新一筆 Run.Status 應為 RunStatus.Success（部分失敗仍視為整體成功）
    And summary.json 的 ErrorMessage 應包含子字串 "部分頁面解析失敗"

  Scenario: 檔案寫入失敗時記錄錯誤
    Given IAtomicJsonWriter 模擬磁碟空間不足，寫 .tmp 即拋 IOException("No space left on device")
    When 執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate = 2026-05-08 })
    Then errors.log 應含 Severity = "error" 且 Message 包含 "No space left on device" 的 ErrorLogEntry
    And summary.json 寫入若可成功，LastRunStatus 應為 RunStatus.Failed

  # ----------------------------------------------------------
  # 介面呈現
  # ----------------------------------------------------------
  Scenario: 行事曆首頁側邊摘要顯示最近一次更新時間
    Given 全系統最近一次成功 Run 的 LastRunAt 為 "2026-05-08T17:05:30+08:00"（依所有 summary.json 取 LastRunStatus = Success 中的最大 LastRunAt）
    When 呼叫 ShellViewModel.LoadAsync()
    Then SideSummaryViewModel.LastUpdatedAt 應為 "2026-05-08T17:05:30+08:00"

  Scenario: 行事曆首頁側邊摘要顯示最近失敗紀錄
    Given 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-06/summary.json" 存在，LastRunStatus = Failed，LastRunAt = "2026-05-06T17:01:23+08:00"
    And 該日為近期最近一次失敗（其他較晚日期的 LastRunStatus 皆為 Success）
    When 呼叫 ShellViewModel.LoadAsync()
    Then SideSummaryViewModel.LastFailureDate 應為 DateOnly(2026, 5, 6)

  Scenario: 點擊行事曆失敗日的警示符號可查看錯誤摘要
    Given 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-06/summary.json" 存在，LastRunStatus = Failed，ErrorMessage = "政府電子採購網連線逾時"
    And 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-06/errors.log" 存在
    And IErrorSummaryDialog 已被 Mock
    When 呼叫 MonthlyCalendarViewModel.ShowFailedSummaryCommand.Execute(DateOnly(2026, 5, 6))
    Then IErrorSummaryDialog.ShowAsync 應被呼叫
    And 呼叫的 errorMessage 參數應為 "政府電子採購網連線逾時"
    And 呼叫的 errorsLogPath 參數應為 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-06/errors.log"

  # ----------------------------------------------------------
  # 邊界情境
  # ----------------------------------------------------------
  Scenario: 同日資料夾尚未存在時，第一次寫入紀錄需自動建立
    Given 目錄 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/" 不存在
    And ICrawler Mock 回傳 3 筆有效標案
    When 執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate = 2026-05-08 })
    Then 目錄 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/" 應存在
    And 目錄 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/" 應存在
    And 檔案 tenders.json、summary.json、crawl-runs.json 三者皆應存在於該目錄

  Scenario: errors.log 隨單日累積，跨日不互相覆蓋
    Given 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-07/errors.log" 已存在，內容為 "前日錯誤行 A\n前日錯誤行 B\n"
    When 呼叫 IErrorLogWriter.AppendAsync(DateOnly(2026, 5, 8), 任意 ErrorLogEntry)
    Then 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-07/errors.log" 內容應與寫入前完全相同
    And 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/errors.log" 應存在，含一行新 ErrorLogEntry
