// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tender.AcceptanceTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class 更新紀錄與錯誤日誌Feature : object, Xunit.IClassFixture<更新紀錄與錯誤日誌Feature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "更新紀錄與錯誤日誌", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "crawl_logging.feature"
#line hidden
        
        public 更新紀錄與錯誤日誌Feature(更新紀錄與錯誤日誌Feature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 15
  #line hidden
#line 16
    await testRunner.GivenAsync("已在測試目錄下初始化資料根目錄 \"${TEST_DATA_ROOT}/TenderSearch/data/\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 17
    await testRunner.AndAsync("IClock.Now 回傳 \"2026-05-08T17:00:00+08:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync("系統時區固定為 \"Asia/Taipei\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="每次成功執行皆寫入 crawl-runs.json")]
        [Xunit.TraitAttribute("FeatureTitle", "更新紀錄與錯誤日誌")]
        [Xunit.TraitAttribute("Description", "每次成功執行皆寫入 crawl-runs.json")]
        public async System.Threading.Tasks.Task 每次成功執行皆寫入Crawl_Runs_Json()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("每次成功執行皆寫入 crawl-runs.json", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 24
    await testRunner.GivenAsync("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/crawl-runs.json\" 不存在", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 25
    await testRunner.AndAsync("ICrawler Mock 回傳 5 筆有效標案", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
    await testRunner.WhenAsync(("執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate =" +
                        " 2026-05-08 })"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
    await testRunner.ThenAsync("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/crawl-runs.json\" 應存在", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 28
    await testRunner.AndAsync("反序列化後 CrawlRunLog.Date 應為 \"2026-05-08\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
    await testRunner.AndAsync("CrawlRunLog.Runs 應有 1 筆", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
    await testRunner.AndAsync(("Runs[0] 的欄位應齊全：RunId、TargetDate、TriggerSource、StartedAt、FinishedAt、Status、Inserte" +
                        "dCount、UpdatedCount、SkippedCount、ErrorMessage"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
    await testRunner.AndAsync("Runs[0].Status 應為 RunStatus.Success", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
    await testRunner.AndAsync("Runs[0].ErrorMessage 應為 null", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="同日多次執行皆累積於 crawl-runs.json")]
        [Xunit.TraitAttribute("FeatureTitle", "更新紀錄與錯誤日誌")]
        [Xunit.TraitAttribute("Description", "同日多次執行皆累積於 crawl-runs.json")]
        public async System.Threading.Tasks.Task 同日多次執行皆累積於Crawl_Runs_Json()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("同日多次執行皆累積於 crawl-runs.json", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 35
    await testRunner.GivenAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/crawl-runs.json\" 已含 1 " +
                        "筆 Status = Success 的 Run，RunId 為 \"20260508-170000\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
    await testRunner.AndAsync("ICrawler Mock 回傳 3 筆有效標案", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
    await testRunner.WhenAsync(("執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Manual, TargetDate = 20" +
                        "26-05-08 })"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
    await testRunner.ThenAsync("crawl-runs.json 反序列化後 Runs.Count 應為 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 39
    await testRunner.AndAsync("Runs[1].RunId 應不等於 Runs[0].RunId", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
    await testRunner.AndAsync("Runs[1].StartedAt 應晚於 Runs[0].StartedAt（時間順序遞增）", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
    await testRunner.AndAsync("Runs[1].TriggerSource 應為 Manual", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="摘要應呈現當次新增/更新/略過筆數")]
        [Xunit.TraitAttribute("FeatureTitle", "更新紀錄與錯誤日誌")]
        [Xunit.TraitAttribute("Description", "摘要應呈現當次新增/更新/略過筆數")]
        public async System.Threading.Tasks.Task 摘要應呈現當次新增更新略過筆數()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("摘要應呈現當次新增/更新/略過筆數", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 44
    await testRunner.GivenAsync("既有 tenders.json 含 SourcePk \"PK001\"~\"PK003\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 45
    await testRunner.AndAsync(("ICrawler Mock 回傳 10 筆標案：5 筆全新 SourcePk + 2 筆 SourcePk = \"PK001\"、\"PK002\"（更新內容）+ 3 " +
                        "筆 SourcePk = \"PK003\"~\"PK003\"（其中 1 筆完全相同無變更，視為 skipped；其餘 2 筆視為新 SourcePk）"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
    await testRunner.AndAsync(("預期 ITenderRepository.MergeDailySnapshotAsync 回傳 MergeResult { Inserted = 5, Updat" +
                        "ed = 2, Skipped = 3 }"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
    await testRunner.WhenAsync(("執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Manual, TargetDate = 20" +
                        "26-05-08 })"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
    await testRunner.ThenAsync("crawl-runs.json 最新一筆 Run 應記錄 InsertedCount = 5、UpdatedCount = 2、SkippedCount = 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
    await testRunner.AndAsync("summary.json 的 InsertedCount、UpdatedCount、SkippedCount 應與最新 Run 相同", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
    await testRunner.AndAsync("summary.json 的 TotalCount 應為合併後 tenders.json 的 Items.Count", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="整批失敗時寫入 failed run 紀錄與錯誤日誌")]
        [Xunit.TraitAttribute("FeatureTitle", "更新紀錄與錯誤日誌")]
        [Xunit.TraitAttribute("Description", "整批失敗時寫入 failed run 紀錄與錯誤日誌")]
        public async System.Threading.Tasks.Task 整批失敗時寫入FailedRun紀錄與錯誤日誌()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("整批失敗時寫入 failed run 紀錄與錯誤日誌", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 56
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 57
    await testRunner.GivenAsync(("ICrawler Mock 在所有重試（maxRetries=3）皆拋 CrawlNetworkException(message = \"Connection t" +
                        "imeout\")"), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 58
    await testRunner.WhenAsync(("執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate =" +
                        " 2026-05-08 })"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 59
    await testRunner.ThenAsync("crawl-runs.json 最新一筆 Run.Status 應為 RunStatus.Failed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 60
    await testRunner.AndAsync("Run.ErrorMessage 應包含子字串 \"Connection timeout\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
    await testRunner.AndAsync(("errors.log 應至少含一行 ErrorLogEntry，Severity = \"error\"，Source = \"crawler\"，Message 包含 " +
                        "\"Connection timeout\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="部分頁面解析失敗仍保留錯誤紀錄")]
        [Xunit.TraitAttribute("FeatureTitle", "更新紀錄與錯誤日誌")]
        [Xunit.TraitAttribute("Description", "部分頁面解析失敗仍保留錯誤紀錄")]
        public async System.Threading.Tasks.Task 部分頁面解析失敗仍保留錯誤紀錄()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("部分頁面解析失敗仍保留錯誤紀錄", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 63
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 64
    await testRunner.GivenAsync(("ICrawler Mock 回傳 5 個 FetchedPage，第 3 頁的 Html 會觸發 ITenderParser.Parse 拋 ParseExcep" +
                        "tion"), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 65
    await testRunner.WhenAsync(("執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate =" +
                        " 2026-05-08 })"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
    await testRunner.ThenAsync(("errors.log 應含一行 ErrorLogEntry，Severity = \"warning\"，Page = 3，Message 包含 \"ParseExce" +
                        "ption\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 67
    await testRunner.AndAsync("crawl-runs.json 最新一筆 Run.Status 應為 RunStatus.Success（部分失敗仍視為整體成功）", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
    await testRunner.AndAsync("summary.json 的 ErrorMessage 應包含子字串 \"部分頁面解析失敗\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="檔案寫入失敗時記錄錯誤")]
        [Xunit.TraitAttribute("FeatureTitle", "更新紀錄與錯誤日誌")]
        [Xunit.TraitAttribute("Description", "檔案寫入失敗時記錄錯誤")]
        public async System.Threading.Tasks.Task 檔案寫入失敗時記錄錯誤()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("檔案寫入失敗時記錄錯誤", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 71
    await testRunner.GivenAsync("IAtomicJsonWriter 模擬磁碟空間不足，寫 .tmp 即拋 IOException(\"No space left on device\")", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
    await testRunner.WhenAsync(("執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate =" +
                        " 2026-05-08 })"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
    await testRunner.ThenAsync(("errors.log 應含 Severity = \"error\" 且 Message 包含 \"No space left on device\" 的 ErrorLo" +
                        "gEntry"), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 74
    await testRunner.AndAsync("summary.json 寫入若可成功，LastRunStatus 應為 RunStatus.Failed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="行事曆首頁側邊摘要顯示最近一次更新時間")]
        [Xunit.TraitAttribute("FeatureTitle", "更新紀錄與錯誤日誌")]
        [Xunit.TraitAttribute("Description", "行事曆首頁側邊摘要顯示最近一次更新時間")]
        public async System.Threading.Tasks.Task 行事曆首頁側邊摘要顯示最近一次更新時間()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("行事曆首頁側邊摘要顯示最近一次更新時間", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 79
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 80
    await testRunner.GivenAsync(("全系統最近一次成功 Run 的 LastRunAt 為 \"2026-05-08T17:05:30+08:00\"（依所有 summary.json 取 LastRu" +
                        "nStatus = Success 中的最大 LastRunAt）"), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 81
    await testRunner.WhenAsync("呼叫 ShellViewModel.LoadAsync()", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 82
    await testRunner.ThenAsync("SideSummaryViewModel.LastUpdatedAt 應為 \"2026-05-08T17:05:30+08:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="行事曆首頁側邊摘要顯示最近失敗紀錄")]
        [Xunit.TraitAttribute("FeatureTitle", "更新紀錄與錯誤日誌")]
        [Xunit.TraitAttribute("Description", "行事曆首頁側邊摘要顯示最近失敗紀錄")]
        public async System.Threading.Tasks.Task 行事曆首頁側邊摘要顯示最近失敗紀錄()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("行事曆首頁側邊摘要顯示最近失敗紀錄", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 84
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 85
    await testRunner.GivenAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-06/summary.json\" 存在，LastR" +
                        "unStatus = Failed，LastRunAt = \"2026-05-06T17:01:23+08:00\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 86
    await testRunner.AndAsync("該日為近期最近一次失敗（其他較晚日期的 LastRunStatus 皆為 Success）", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 87
    await testRunner.WhenAsync("呼叫 ShellViewModel.LoadAsync()", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 88
    await testRunner.ThenAsync("SideSummaryViewModel.LastFailureDate 應為 DateOnly(2026, 5, 6)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="點擊行事曆失敗日的警示符號可查看錯誤摘要")]
        [Xunit.TraitAttribute("FeatureTitle", "更新紀錄與錯誤日誌")]
        [Xunit.TraitAttribute("Description", "點擊行事曆失敗日的警示符號可查看錯誤摘要")]
        public async System.Threading.Tasks.Task 點擊行事曆失敗日的警示符號可查看錯誤摘要()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("點擊行事曆失敗日的警示符號可查看錯誤摘要", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 90
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 91
    await testRunner.GivenAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-06/summary.json\" 存在，LastR" +
                        "unStatus = Failed，ErrorMessage = \"政府電子採購網連線逾時\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 92
    await testRunner.AndAsync("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-06/errors.log\" 存在", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 93
    await testRunner.AndAsync("IErrorSummaryDialog 已被 Mock", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 94
    await testRunner.WhenAsync(("呼叫 MonthlyCalendarViewModel.ShowFailedSummaryCommand.Execute(DateOnly(2026, 5, 6)" +
                        ")"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 95
    await testRunner.ThenAsync("IErrorSummaryDialog.ShowAsync 應被呼叫", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 96
    await testRunner.AndAsync("呼叫的 errorMessage 參數應為 \"政府電子採購網連線逾時\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
    await testRunner.AndAsync(("呼叫的 errorsLogPath 參數應為 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-06/er" +
                        "rors.log\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="同日資料夾尚未存在時，第一次寫入紀錄需自動建立")]
        [Xunit.TraitAttribute("FeatureTitle", "更新紀錄與錯誤日誌")]
        [Xunit.TraitAttribute("Description", "同日資料夾尚未存在時，第一次寫入紀錄需自動建立")]
        public async System.Threading.Tasks.Task 同日資料夾尚未存在時第一次寫入紀錄需自動建立()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("同日資料夾尚未存在時，第一次寫入紀錄需自動建立", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 102
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 103
    await testRunner.GivenAsync("目錄 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/\" 不存在", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 104
    await testRunner.AndAsync("ICrawler Mock 回傳 3 筆有效標案", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 105
    await testRunner.WhenAsync(("執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate =" +
                        " 2026-05-08 })"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 106
    await testRunner.ThenAsync("目錄 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/\" 應存在", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 107
    await testRunner.AndAsync("目錄 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/\" 應存在", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 108
    await testRunner.AndAsync("檔案 tenders.json、summary.json、crawl-runs.json 三者皆應存在於該目錄", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="errors.log 隨單日累積，跨日不互相覆蓋")]
        [Xunit.TraitAttribute("FeatureTitle", "更新紀錄與錯誤日誌")]
        [Xunit.TraitAttribute("Description", "errors.log 隨單日累積，跨日不互相覆蓋")]
        public async System.Threading.Tasks.Task Errors_Log隨單日累積跨日不互相覆蓋()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("errors.log 隨單日累積，跨日不互相覆蓋", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 110
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 111
    await testRunner.GivenAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-07/errors.log\" 已存在，內容為 \"前" +
                        "日錯誤行 A\\n前日錯誤行 B\\n\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 112
    await testRunner.WhenAsync("呼叫 IErrorLogWriter.AppendAsync(DateOnly(2026, 5, 8), 任意 ErrorLogEntry)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 113
    await testRunner.ThenAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-07/errors.log\" 內容應與寫入前完全相" +
                        "同"), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 114
    await testRunner.AndAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/errors.log\" 應存在，含一行新 E" +
                        "rrorLogEntry"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await 更新紀錄與錯誤日誌Feature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await 更新紀錄與錯誤日誌Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
