// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tender.AcceptanceTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class 每日標案爬蟲自動排程與手動更新Feature : object, Xunit.IClassFixture<每日標案爬蟲自動排程與手動更新Feature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "每日標案爬蟲（自動排程與手動更新）", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "daily_crawl.feature"
#line hidden
        
        public 每日標案爬蟲自動排程與手動更新Feature(每日標案爬蟲自動排程與手動更新Feature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 15
  #line hidden
#line 16
    await testRunner.GivenAsync("已在測試目錄下初始化資料根目錄 \"${TEST_DATA_ROOT}/TenderSearch/data/\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 17
    await testRunner.AndAsync("IDataPaths.DataRoot 指向 \"${TEST_DATA_ROOT}/TenderSearch/data/\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync(("IAppSettingsRepository.LoadAsync() 回傳預設值，targetTenderMethods 為 [\"公開招標\", \"公開取得報價單或" +
                    "企劃書\", \"經公開評選或公開徵求之限制性招標\"]"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.AndAsync("系統時區固定為 \"Asia/Taipei\" (UTC+8)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
    await testRunner.AndAsync("ICrawler 已被 Mock，可由測試控制回傳的 FetchedPage[]", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="每日 17:00 排程準時執行並成功擷取當天標案")]
        [Xunit.TraitAttribute("FeatureTitle", "每日標案爬蟲（自動排程與手動更新）")]
        [Xunit.TraitAttribute("Description", "每日 17:00 排程準時執行並成功擷取當天標案")]
        public async System.Threading.Tasks.Task 每日1700排程準時執行並成功擷取當天標案()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("每日 17:00 排程準時執行並成功擷取當天標案", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 27
    await testRunner.GivenAsync("IClock.Now 回傳 \"2026-05-08T17:00:00+08:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 28
    await testRunner.AndAsync("ICrawler Mock 回傳 5 筆標案，sourcePk 分別為 \"PK001\"~\"PK005\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
    await testRunner.WhenAsync(("執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate =" +
                        " 2026-05-08 })"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
    await testRunner.ThenAsync("ICrawler.FetchAsync 應被呼叫，targetDate 參數為 \"2026-05-08\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 31
    await testRunner.AndAsync(("ICrawler.FetchAsync 的 tenderMethods 參數應為 [\"公開招標\", \"公開取得報價單或企劃書\", \"經公開評選或公開徵求之限制性招" +
                        "標\"]"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
    await testRunner.AndAsync("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/tenders.json\" 應存在", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
    await testRunner.AndAsync("tenders.json 反序列化後 DailyTenderSnapshot.Date 應為 \"2026-05-08\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
    await testRunner.AndAsync(("tenders.json 的 Items 每筆都應包含非空的 SourcePk、AgencyName、TenderName、TenderMethod、Announ" +
                        "cementDate、DetailUrl"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
    await testRunner.AndAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/summary.json\" 應存在，Dail" +
                        "ySummary.LastRunStatus 應為 RunStatus.Success"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.AndAsync("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/crawl-runs.json\" 應存在", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
    await testRunner.AndAsync("CrawlRunLog.Runs 應包含 1 筆紀錄，TriggerSource 為 Scheduled，Status 為 Success", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="使用者按下「立即更新」按鈕成功擷取當天標案")]
        [Xunit.TraitAttribute("FeatureTitle", "每日標案爬蟲（自動排程與手動更新）")]
        [Xunit.TraitAttribute("Description", "使用者按下「立即更新」按鈕成功擷取當天標案")]
        public async System.Threading.Tasks.Task 使用者按下立即更新按鈕成功擷取當天標案()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("使用者按下「立即更新」按鈕成功擷取當天標案", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 44
    await testRunner.GivenAsync("IClock.Now 回傳 \"2026-05-08T10:30:00+08:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 45
    await testRunner.AndAsync("ICrawler Mock 回傳 3 筆標案", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
    await testRunner.WhenAsync(("執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Manual, TargetDate = 20" +
                        "26-05-08 })"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
    await testRunner.ThenAsync("summary.json 的 LastRunAt 應為 ICrawlerOrchestrator 完成時的 IClock.Now 值", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 48
    await testRunner.AndAsync("crawl-runs.json 最後一筆 Run 的 TriggerSource 應為 Manual", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="17:00 排程因關機未執行，開機後自動補跑一次")]
        [Xunit.TraitAttribute("FeatureTitle", "每日標案爬蟲（自動排程與手動更新）")]
        [Xunit.TraitAttribute("Description", "17:00 排程因關機未執行，開機後自動補跑一次")]
        public async System.Threading.Tasks.Task _1700排程因關機未執行開機後自動補跑一次()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("17:00 排程因關機未執行，開機後自動補跑一次", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 55
    await testRunner.GivenAsync("IClock.Now 回傳 \"2026-05-08T22:30:00+08:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 56
    await testRunner.AndAsync("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/summary.json\" 不存在", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
    await testRunner.AndAsync("ICrawlerLauncher 已被 Mock，呼叫時回傳 exit code 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
    await testRunner.WhenAsync("呼叫 IMissedRunDetector.CheckAndCatchupAsync()", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 59
    await testRunner.ThenAsync("ICrawlerLauncher.LaunchAsync 應被呼叫一次，CrawlerMode 為 Catchup，TargetDate 為 2026-05-08", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 60
    await testRunner.AndAsync("補跑完成後 ICrawlerOrchestrator 寫入的 CrawlRun.TriggerSource 應為 Catchup", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="17:00 排程已成功執行，使用者開機後不重複補跑")]
        [Xunit.TraitAttribute("FeatureTitle", "每日標案爬蟲（自動排程與手動更新）")]
        [Xunit.TraitAttribute("Description", "17:00 排程已成功執行，使用者開機後不重複補跑")]
        public async System.Threading.Tasks.Task _1700排程已成功執行使用者開機後不重複補跑()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("17:00 排程已成功執行，使用者開機後不重複補跑", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 62
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 63
    await testRunner.GivenAsync("IClock.Now 回傳 \"2026-05-08T22:30:00+08:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 64
    await testRunner.AndAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/summary.json\" 已存在，Last" +
                        "RunStatus 為 Success"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
    await testRunner.WhenAsync("呼叫 IMissedRunDetector.CheckAndCatchupAsync()", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
    await testRunner.ThenAsync("ICrawlerLauncher.LaunchAsync 不應被呼叫", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 67
    await testRunner.AndAsync("回傳的 MissedRunResult.WasMissed 應為 false", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="使用者對過去日期執行「重新抓取此日」")]
        [Xunit.TraitAttribute("FeatureTitle", "每日標案爬蟲（自動排程與手動更新）")]
        [Xunit.TraitAttribute("Description", "使用者對過去日期執行「重新抓取此日」")]
        public async System.Threading.Tasks.Task 使用者對過去日期執行重新抓取此日()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("使用者對過去日期執行「重新抓取此日」", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 72
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 73
    await testRunner.GivenAsync("IClock.Now 回傳 \"2026-05-08T14:00:00+08:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 74
    await testRunner.AndAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-05/tenders.json\" 已存在，Item" +
                        "s 含 sourcePk \"EXISTING-001\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
    await testRunner.AndAsync("ICrawler Mock 對 targetDate \"2026-05-05\" 回傳 4 筆標案，其中 1 筆 sourcePk 為 \"EXISTING-001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
    await testRunner.WhenAsync(("執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = ManualRedo, TargetDate " +
                        "= 2026-05-05 })"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 77
    await testRunner.ThenAsync("ICrawler.FetchAsync 的 targetDate 參數應為 \"2026-05-05\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 78
    await testRunner.AndAsync(("寫入路徑應為 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-05/tenders.json\"，非當天資" +
                        "料夾"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
    await testRunner.AndAsync("crawl-runs.json 最後一筆 Run 的 TriggerSource 應為 ManualRedo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
    await testRunner.AndAsync("tenders.json 中 sourcePk \"EXISTING-001\" 應只出現 1 次（不重複）", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="同一天內重複執行爬蟲不可產生重複標案")]
        [Xunit.TraitAttribute("FeatureTitle", "每日標案爬蟲（自動排程與手動更新）")]
        [Xunit.TraitAttribute("Description", "同一天內重複執行爬蟲不可產生重複標案")]
        public async System.Threading.Tasks.Task 同一天內重複執行爬蟲不可產生重複標案()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("同一天內重複執行爬蟲不可產生重複標案", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 85
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 87
    await testRunner.GivenAsync("IClock.Now 回傳 \"2026-05-08T18:30:00+08:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 88
    await testRunner.AndAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/tenders.json\" 已存在，含 50" +
                        " 筆標案 sourcePk \"PK001\"~\"PK050\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "sourcePk",
                            "是否新（既有檔案中存在）"});
                table1.AddRow(new string[] {
                            "PK001",
                            "是（既有，內容更新）"});
                table1.AddRow(new string[] {
                            "PK002",
                            "是（既有，內容更新）"});
                table1.AddRow(new string[] {
                            "PK051",
                            "否（全新）"});
                table1.AddRow(new string[] {
                            "PK052",
                            "否（全新）"});
                table1.AddRow(new string[] {
                            "PK053",
                            "否（全新）"});
                table1.AddRow(new string[] {
                            "PK048",
                            "是（既有，無變更）"});
                table1.AddRow(new string[] {
                            "PK049",
                            "是（既有，無變更）"});
#line 89
    await testRunner.AndAsync("ICrawler Mock 回傳 7 筆標案：", ((string)(null)), table1, "And ");
#line hidden
#line 98
    await testRunner.WhenAsync(("執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Manual, TargetDate = 20" +
                        "26-05-08 })"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 99
    await testRunner.ThenAsync("tenders.json 的 Items 總筆數應為 53", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 100
    await testRunner.AndAsync("同一個 SourcePk 在 Items 中只能出現一次", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 101
    await testRunner.AndAsync("SourcePk 為 \"PK001\"、\"PK002\" 的兩筆 LastSeenAt 應為本次 IClock.Now 值，CreatedAt 不變", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 102
    await testRunner.AndAsync("crawl-runs.json 最後一筆 Run 應記錄 InsertedCount=3、UpdatedCount=2、SkippedCount=2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="同一標案在連續兩天的查詢結果都出現，應分別保留於兩日的快照")]
        [Xunit.TraitAttribute("FeatureTitle", "每日標案爬蟲（自動排程與手動更新）")]
        [Xunit.TraitAttribute("Description", "同一標案在連續兩天的查詢結果都出現，應分別保留於兩日的快照")]
        public async System.Threading.Tasks.Task 同一標案在連續兩天的查詢結果都出現應分別保留於兩日的快照()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("同一標案在連續兩天的查詢結果都出現，應分別保留於兩日的快照", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 107
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 108
    await testRunner.GivenAsync("ICrawler Mock 對 targetDate \"2026-05-07\" 回傳含 sourcePk \"ABC123\" 的標案", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 109
    await testRunner.AndAsync("ICrawler Mock 對 targetDate \"2026-05-08\" 同樣回傳含 sourcePk \"ABC123\" 的標案", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 110
    await testRunner.WhenAsync(("依序執行 ICrawlerOrchestrator.RunAsync(Scheduled, 2026-05-07) 與 ICrawlerOrchestrator." +
                        "RunAsync(Scheduled, 2026-05-08)"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 111
    await testRunner.ThenAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-07/tenders.json\" 的 Items " +
                        "應含 SourcePk \"ABC123\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 112
    await testRunner.AndAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/tenders.json\" 的 Items " +
                        "應含 SourcePk \"ABC123\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 113
    await testRunner.AndAsync("兩日的資料夾各自獨立保存，互不影響", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="政府電子採購網無法連線時，爬蟲執行失敗並記錄錯誤")]
        [Xunit.TraitAttribute("FeatureTitle", "每日標案爬蟲（自動排程與手動更新）")]
        [Xunit.TraitAttribute("Description", "政府電子採購網無法連線時，爬蟲執行失敗並記錄錯誤")]
        public async System.Threading.Tasks.Task 政府電子採購網無法連線時爬蟲執行失敗並記錄錯誤()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("政府電子採購網無法連線時，爬蟲執行失敗並記錄錯誤", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 118
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 119
    await testRunner.GivenAsync("IClock.Now 回傳 \"2026-05-08T17:00:00+08:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 120
    await testRunner.AndAsync("ICrawler Mock 在所有重試（含預設 maxRetries=3）皆拋 CrawlNetworkException", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 121
    await testRunner.WhenAsync(("執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate =" +
                        " 2026-05-08 })"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 122
    await testRunner.ThenAsync("summary.json 的 LastRunStatus 應為 RunStatus.Failed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 123
    await testRunner.AndAsync("summary.json 的 ErrorMessage 應包含子字串 \"CrawlNetworkException\" 或網路錯誤摘要", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
    await testRunner.AndAsync("crawl-runs.json 最後一筆 Run 的 Status 應為 Failed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
    await testRunner.AndAsync("errors.log 應至少含一行 ErrorLogEntry，Severity 為 \"error\"，Source 為 \"crawler\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="政府電子採購網單頁解析失敗，整批任務不應中斷")]
        [Xunit.TraitAttribute("FeatureTitle", "每日標案爬蟲（自動排程與手動更新）")]
        [Xunit.TraitAttribute("Description", "政府電子採購網單頁解析失敗，整批任務不應中斷")]
        public async System.Threading.Tasks.Task 政府電子採購網單頁解析失敗整批任務不應中斷()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("政府電子採購網單頁解析失敗，整批任務不應中斷", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 127
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "PageNumber",
                            "Html 是否有效"});
                table2.AddRow(new string[] {
                            "1",
                            "是"});
                table2.AddRow(new string[] {
                            "2",
                            "是"});
                table2.AddRow(new string[] {
                            "3",
                            "否（觸發 ITenderParser 拋 ParseException）"});
                table2.AddRow(new string[] {
                            "4",
                            "是"});
                table2.AddRow(new string[] {
                            "5",
                            "是"});
#line 128
    await testRunner.GivenAsync("ICrawler Mock 回傳 5 個 FetchedPage：", ((string)(null)), table2, "Given ");
#line hidden
#line 135
    await testRunner.AndAsync("第 1、2、4、5 頁各回傳 4 筆標案", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 136
    await testRunner.WhenAsync(("執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate =" +
                        " 2026-05-08 })"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 137
    await testRunner.ThenAsync("tenders.json 的 Items 筆數應為 16（4 頁 × 4 筆，第 3 頁略過）", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 138
    await testRunner.AndAsync("errors.log 應含一行 Severity 為 \"warning\"、Page 為 3 的 ErrorLogEntry", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 139
    await testRunner.AndAsync("summary.json 的 LastRunStatus 應為 RunStatus.Success", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 140
    await testRunner.AndAsync("summary.json 的 ErrorMessage 應包含子字串 \"部分頁面解析失敗\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="JSON 寫入過程中斷，既有檔案不可被破壞")]
        [Xunit.TraitAttribute("FeatureTitle", "每日標案爬蟲（自動排程與手動更新）")]
        [Xunit.TraitAttribute("Description", "JSON 寫入過程中斷，既有檔案不可被破壞")]
        public async System.Threading.Tasks.Task JSON寫入過程中斷既有檔案不可被破壞()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("JSON 寫入過程中斷，既有檔案不可被破壞", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 142
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 144
    await testRunner.GivenAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/tenders.json\" 已存在且內容完整" +
                        "可解析"), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 145
    await testRunner.AndAsync("將 IAtomicJsonWriter 換為 FaultyAtomicJsonWriter，於 File.Move 前拋 IOException", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 146
    await testRunner.WhenAsync(("執行 ITenderRepository.MergeDailySnapshotAsync(2026-05-08, 任意 incomingItems, IClock" +
                        ".Now)"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 147
    await testRunner.ThenAsync("應拋出 IOException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 148
    await testRunner.AndAsync("既有 tenders.json 檔案大小與內容應與寫入前一致（hash 相同）", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 149
    await testRunner.AndAsync("errors.log 應記錄該次 IOException", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="寫入磁碟失敗（例如磁碟已滿）時應記錄錯誤")]
        [Xunit.TraitAttribute("FeatureTitle", "每日標案爬蟲（自動排程與手動更新）")]
        [Xunit.TraitAttribute("Description", "寫入磁碟失敗（例如磁碟已滿）時應記錄錯誤")]
        public async System.Threading.Tasks.Task 寫入磁碟失敗例如磁碟已滿時應記錄錯誤()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("寫入磁碟失敗（例如磁碟已滿）時應記錄錯誤", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 151
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 152
    await testRunner.GivenAsync("IAtomicJsonWriter 模擬磁碟已滿，寫入 .tmp 即拋 IOException", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 153
    await testRunner.WhenAsync(("執行 ICrawlerOrchestrator.RunAsync(new CrawlerArgs { Mode = Scheduled, TargetDate =" +
                        " 2026-05-08 })"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 154
    await testRunner.ThenAsync("errors.log 應含 Severity 為 \"error\" 的 IOException 紀錄", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 155
    await testRunner.AndAsync(("summary.json 若能寫入則 LastRunStatus 應為 Failed；若 summary.json 寫入也失敗則應在 errors.log 額外記" +
                        "錄"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 156
    await testRunner.AndAsync("crawl-runs.json 最後一筆 Run 的 Status 應為 Failed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await 每日標案爬蟲自動排程與手動更新Feature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await 每日標案爬蟲自動排程與手動更新Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
