# language: en
# Generated by sa-expert
# Source: pm/features/daily_query.feature
# Project scan date: 2026-05-08
# Module type: WPF Desktop (Tender.Desktop) + Core Search (Tender.Core)
# Architecture: DailyQueryViewModel → ITenderRepository（讀 tenders.json）→ ISearchService（過濾 + 排序）
# Step Definitions: tests/Tender.AcceptanceTests/Steps/DailyQuerySteps.cs

Feature: 指定日期標案資料查詢
  # 業務模組：Bounded Context 3 - Daily Query
  # 主要協調者：Tender.Desktop.ViewModels.DailyQueryViewModel
  # 搜尋邏輯：Tender.Core.Search.ISearchService
  # 資料來源：Tender.Storage.Repositories.ITenderRepository
  # 瀏覽器啟動：Tender.Desktop.Services.IBrowserLauncher

  Background:
    Given IClock.Now 回傳 "2026-05-08T09:00:00+08:00"
    And 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/tenders.json" 存在，Items 共 55 筆
    And 已透過 ShellViewModel.NavigateToDayCommand 載入 DailyQueryViewModel，Date = DateOnly(2026, 5, 8)

  # ----------------------------------------------------------
  # Happy path
  # ----------------------------------------------------------
  Scenario: 進入查詢頁預設顯示該日所有標案
    # 對應 Step Definition：When_LoadDailyQueryViewModel
    When DailyQueryViewModel.LoadCommand 執行完成
    Then DailyQueryViewModel.Date 應為 DateOnly(2026, 5, 8)
    And DailyQueryViewModel.Items.Count 應為 55
    And DailyQueryViewModel.Criteria.KeywordQuery 應為 null 或空字串
    # UI 欄位驗證在 Tender.Desktop.Tests 中以 DataGrid binding 驗證

  Scenario: 使用者輸入單一關鍵字搜尋標案名稱
    Given Items 中 TenderName 含 "AI" 的筆數為 8
    When DailyQueryViewModel.Criteria 設定 KeywordQuery = "AI"，並呼叫 ApplySearchCommand
    Then DailyQueryViewModel.FilteredItems.Count 應為 8
    And FilteredItems 每筆的 TenderName 應包含子字串 "AI"

  Scenario: 使用者輸入關鍵字搜尋機關名稱
    Given Items 中 AgencyName 含 "經濟部水利署" 的筆數為 3
    When DailyQueryViewModel.Criteria 設定 KeywordQuery = "經濟部水利署"，並呼叫 ApplySearchCommand
    Then FilteredItems.Count 應為 3
    And FilteredItems 每筆的 AgencyName 應包含 "經濟部水利署"

  Scenario: 使用者輸入標案案號搜尋
    Given Items 中存在 TenderNo 為 "1140508-A001" 的標案 1 筆
    When DailyQueryViewModel.Criteria 設定 KeywordQuery = "1140508-A001"，並呼叫 ApplySearchCommand
    Then FilteredItems.Count 應為 1
    And FilteredItems[0].TenderNo 應為 "1140508-A001"

  # ----------------------------------------------------------
  # 篩選條件
  # ----------------------------------------------------------
  Scenario Outline: 套用單一篩選條件
    When 設定 DailyQueryViewModel.Criteria 的屬性 "<Criteria屬性>" 為 "<篩選值>"，並呼叫 ApplySearchCommand
    Then FilteredItems 每筆應符合 "<驗證描述>"

    Examples:
      | Criteria屬性     | 篩選值              | 驗證描述                              |
      | TenderMethod     | 公開招標            | TenderItem.TenderMethod == "公開招標" |
      | TenderMethod     | 公開取得報價單或企劃書  | TenderItem.TenderMethod == "公開取得報價單或企劃書" |
      | ProcurementType  | 財物類              | TenderItem.ProcurementType == "財物類" |
      | ShowActiveOnly   | true                | ITaiwanDateConverter.RocToDateOnly(BidDeadline) >= IClock.Today |

  Scenario: 套用預算金額區間
    Given Items 中 BudgetAmount 介於 1000000 與 5000000 的筆數為 12
    When 設定 Criteria.BudgetMin = 1000000、BudgetMax = 5000000，並呼叫 ApplySearchCommand
    Then FilteredItems.Count 應為 12
    And FilteredItems 每筆的 BudgetAmount 應介於 [1000000, 5000000]（含端點）

  Scenario: 套用公告日期區間（補抓多日資料時使用）
    Given Items 中 AnnouncementDate 介於 "115/05/06" 與 "115/05/08"（含）的筆數為 30
    When 設定 Criteria.AnnouncementDateFrom = "115/05/06"、AnnouncementDateTo = "115/05/08"，並呼叫 ApplySearchCommand
    Then FilteredItems.Count 應為 30

  Scenario: 套用截止投標日期區間
    Given Items 中 BidDeadline 介於 "115/05/12" 與 "115/05/20"（含）的筆數為 18
    When 設定 Criteria.BidDeadlineFrom = "115/05/12"、BidDeadlineTo = "115/05/20"，並呼叫 ApplySearchCommand
    Then FilteredItems.Count 應為 18

  Scenario: 同時套用多個篩選條件（AND 邏輯）
    When 設定 Criteria.TenderMethod = "公開招標"、ProcurementType = "勞務類"、ShowActiveOnly = true，並呼叫 ApplySearchCommand
    Then FilteredItems 每筆應同時符合：
      | 條件                                              |
      | TenderMethod == "公開招標"                        |
      | ProcurementType == "勞務類"                       |
      | RocToDateOnly(BidDeadline) >= IClock.Today        |

  # ----------------------------------------------------------
  # 排序
  # ----------------------------------------------------------
  Scenario Outline: 點擊欄位標題進行排序
    When 設定 DailyQueryViewModel.SortKey = <SortKey>、SortDirection = <Direction>，並呼叫 ApplySearchCommand
    Then FilteredItems 應依 <SortKey> 以 <Direction> 排序（null 值排於最後）

    Examples:
      | SortKey           | Direction  |
      | BudgetAmount      | Ascending  |
      | BudgetAmount      | Descending |
      | AnnouncementDate  | Ascending  |
      | BidDeadline       | Ascending  |
      | AgencyName        | Ascending  |

  # ----------------------------------------------------------
  # 開啟詳情連結
  # ----------------------------------------------------------
  Scenario: 點擊「檢視」以預設瀏覽器開啟政府電子採購網標案頁
    Given FilteredItems[0].DetailUrl 為 "https://web.pcc.gov.tw/prkms/urlSelector/common/tpam?pk=NzEyMTUxODc="
    And IBrowserLauncher 已被 Mock
    When 呼叫 DailyQueryViewModel.OpenDetailCommand.Execute(FilteredItems[0])
    Then IBrowserLauncher.Open 應被呼叫一次，url 參數為 "https://web.pcc.gov.tw/prkms/urlSelector/common/tpam?pk=NzEyMTUxODc="

  # ----------------------------------------------------------
  # 日期切換
  # ----------------------------------------------------------
  Scenario: 切換到前一天的查詢頁
    Given DailyQueryViewModel.Date 為 DateOnly(2026, 5, 8)
    And 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-07/tenders.json" 存在，Items 共 42 筆
    When 呼叫 DailyQueryViewModel.GoPreviousDayCommand.Execute(null)
    Then DailyQueryViewModel.Date 應為 DateOnly(2026, 5, 7)
    And DailyQueryViewModel.Items.Count 應為 42

  Scenario: 切換到後一天但該日尚無資料
    Given DailyQueryViewModel.Date 為 DateOnly(2026, 5, 8)
    And 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-09/tenders.json" 不存在
    When 呼叫 DailyQueryViewModel.GoNextDayCommand.Execute(null)
    Then DailyQueryViewModel.Date 應為 DateOnly(2026, 5, 9)
    And DailyQueryViewModel.Items.Count 應為 0
    And DailyQueryViewModel.IsEmpty 應為 true（UI 顯示「該日尚無標案資料」）
    And 不應拋出任何例外

  Scenario: 從查詢頁返回月份行事曆
    Given DailyQueryViewModel.Date 為 DateOnly(2026, 5, 8)
    When 呼叫 ShellViewModel.NavigateBackToCalendarCommand.Execute(null)
    Then ShellViewModel.CurrentDailyQueryVm 應為 null
    And ShellViewModel.CalendarVm.Year 應為 2026，Month 應為 5

  # ----------------------------------------------------------
  # 錯誤情境
  # ----------------------------------------------------------
  Scenario: 進入查詢頁時 tenders.json 損毀
    Given 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/tenders.json" 內容為 "{ broken"
    When 建立 DailyQueryViewModel(date = 2026-05-08) 並呼叫 LoadCommand
    Then 不應拋出例外
    And DailyQueryViewModel.LoadError 應不為 null，訊息包含「資料檔案損毀」
    And errors.log 應記錄 CorruptedDataException

  Scenario: 搜尋無命中結果
    When 設定 Criteria.KeywordQuery = "找不到的關鍵字XYZ"，並呼叫 ApplySearchCommand
    Then FilteredItems.Count 應為 0
    And DailyQueryViewModel.IsEmpty 應為 true
    And DailyQueryViewModel.LoadError 應為 null（這不是錯誤情境）
