// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tender.AcceptanceTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class 指定日期標案資料查詢Feature : object, Xunit.IClassFixture<指定日期標案資料查詢Feature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "指定日期標案資料查詢", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "daily_query.feature"
#line hidden
        
        public 指定日期標案資料查詢Feature(指定日期標案資料查詢Feature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 16
  #line hidden
#line 17
    await testRunner.GivenAsync("IClock.Now 回傳 \"2026-05-08T09:00:00+08:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
    await testRunner.AndAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/tenders.json\" 存在，Items" +
                    " 共 55 筆"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.AndAsync(("已透過 ShellViewModel.NavigateToDayCommand 載入 DailyQueryViewModel，Date = DateOnly(20" +
                    "26, 5, 8)"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="進入查詢頁預設顯示該日所有標案")]
        [Xunit.TraitAttribute("FeatureTitle", "指定日期標案資料查詢")]
        [Xunit.TraitAttribute("Description", "進入查詢頁預設顯示該日所有標案")]
        public async System.Threading.Tasks.Task 進入查詢頁預設顯示該日所有標案()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("進入查詢頁預設顯示該日所有標案", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 26
    await testRunner.WhenAsync("DailyQueryViewModel.LoadCommand 執行完成", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
    await testRunner.ThenAsync("DailyQueryViewModel.Date 應為 DateOnly(2026, 5, 8)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 28
    await testRunner.AndAsync("DailyQueryViewModel.Items.Count 應為 55", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
    await testRunner.AndAsync("DailyQueryViewModel.Criteria.KeywordQuery 應為 null 或空字串", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="使用者輸入單一關鍵字搜尋標案名稱")]
        [Xunit.TraitAttribute("FeatureTitle", "指定日期標案資料查詢")]
        [Xunit.TraitAttribute("Description", "使用者輸入單一關鍵字搜尋標案名稱")]
        public async System.Threading.Tasks.Task 使用者輸入單一關鍵字搜尋標案名稱()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("使用者輸入單一關鍵字搜尋標案名稱", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 33
    await testRunner.GivenAsync("Items 中 TenderName 含 \"AI\" 的筆數為 8", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 34
    await testRunner.WhenAsync("DailyQueryViewModel.Criteria 設定 KeywordQuery = \"AI\"，並呼叫 ApplySearchCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
    await testRunner.ThenAsync("DailyQueryViewModel.FilteredItems.Count 應為 8", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 36
    await testRunner.AndAsync("FilteredItems 每筆的 TenderName 應包含子字串 \"AI\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="使用者輸入關鍵字搜尋機關名稱")]
        [Xunit.TraitAttribute("FeatureTitle", "指定日期標案資料查詢")]
        [Xunit.TraitAttribute("Description", "使用者輸入關鍵字搜尋機關名稱")]
        public async System.Threading.Tasks.Task 使用者輸入關鍵字搜尋機關名稱()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("使用者輸入關鍵字搜尋機關名稱", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 39
    await testRunner.GivenAsync("Items 中 AgencyName 含 \"經濟部水利署\" 的筆數為 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
    await testRunner.WhenAsync("DailyQueryViewModel.Criteria 設定 KeywordQuery = \"經濟部水利署\"，並呼叫 ApplySearchCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
    await testRunner.ThenAsync("FilteredItems.Count 應為 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
    await testRunner.AndAsync("FilteredItems 每筆的 AgencyName 應包含 \"經濟部水利署\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="使用者輸入標案案號搜尋")]
        [Xunit.TraitAttribute("FeatureTitle", "指定日期標案資料查詢")]
        [Xunit.TraitAttribute("Description", "使用者輸入標案案號搜尋")]
        public async System.Threading.Tasks.Task 使用者輸入標案案號搜尋()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("使用者輸入標案案號搜尋", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 45
    await testRunner.GivenAsync("Items 中存在 TenderNo 為 \"1140508-A001\" 的標案 1 筆", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 46
    await testRunner.WhenAsync(("DailyQueryViewModel.Criteria 設定 KeywordQuery = \"1140508-A001\"，並呼叫 ApplySearchComm" +
                        "and"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
    await testRunner.ThenAsync("FilteredItems.Count 應為 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 48
    await testRunner.AndAsync("FilteredItems[0].TenderNo 應為 \"1140508-A001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="套用單一篩選條件")]
        [Xunit.TraitAttribute("FeatureTitle", "指定日期標案資料查詢")]
        [Xunit.TraitAttribute("Description", "套用單一篩選條件")]
        [Xunit.InlineDataAttribute("TenderMethod", "公開招標", "TenderItem.TenderMethod == \"公開招標\"", new string[0])]
        [Xunit.InlineDataAttribute("TenderMethod", "公開取得報價單或企劃書", "TenderItem.TenderMethod == \"公開取得報價單或企劃書\"", new string[0])]
        [Xunit.InlineDataAttribute("ProcurementType", "財物類", "TenderItem.ProcurementType == \"財物類\"", new string[0])]
        [Xunit.InlineDataAttribute("ShowActiveOnly", "true", "ITaiwanDateConverter.RocToDateOnly(BidDeadline) >= IClock.Today", new string[0])]
        public async System.Threading.Tasks.Task 套用單一篩選條件(string criteria屬性, string 篩選值, string 驗證描述, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Criteria屬性", criteria屬性);
            argumentsOfScenario.Add("篩選值", 篩選值);
            argumentsOfScenario.Add("驗證描述", 驗證描述);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("套用單一篩選條件", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 54
    await testRunner.WhenAsync(string.Format("設定 DailyQueryViewModel.Criteria 的屬性 \"{0}\" 為 \"{1}\"，並呼叫 ApplySearchCommand", criteria屬性, 篩選值), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
    await testRunner.ThenAsync(string.Format("FilteredItems 每筆應符合 \"{0}\"", 驗證描述), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="套用預算金額區間")]
        [Xunit.TraitAttribute("FeatureTitle", "指定日期標案資料查詢")]
        [Xunit.TraitAttribute("Description", "套用預算金額區間")]
        public async System.Threading.Tasks.Task 套用預算金額區間()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("套用預算金額區間", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 64
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 65
    await testRunner.GivenAsync("Items 中 BudgetAmount 介於 1000000 與 5000000 的筆數為 12", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 66
    await testRunner.WhenAsync("設定 Criteria.BudgetMin = 1000000、BudgetMax = 5000000，並呼叫 ApplySearchCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
    await testRunner.ThenAsync("FilteredItems.Count 應為 12", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 68
    await testRunner.AndAsync("FilteredItems 每筆的 BudgetAmount 應介於 [1000000, 5000000]（含端點）", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="套用公告日期區間（補抓多日資料時使用）")]
        [Xunit.TraitAttribute("FeatureTitle", "指定日期標案資料查詢")]
        [Xunit.TraitAttribute("Description", "套用公告日期區間（補抓多日資料時使用）")]
        public async System.Threading.Tasks.Task 套用公告日期區間補抓多日資料時使用()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("套用公告日期區間（補抓多日資料時使用）", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 71
    await testRunner.GivenAsync("Items 中 AnnouncementDate 介於 \"115/05/06\" 與 \"115/05/08\"（含）的筆數為 30", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
    await testRunner.WhenAsync(("設定 Criteria.AnnouncementDateFrom = \"115/05/06\"、AnnouncementDateTo = \"115/05/08\"，並" +
                        "呼叫 ApplySearchCommand"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
    await testRunner.ThenAsync("FilteredItems.Count 應為 30", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="套用截止投標日期區間")]
        [Xunit.TraitAttribute("FeatureTitle", "指定日期標案資料查詢")]
        [Xunit.TraitAttribute("Description", "套用截止投標日期區間")]
        public async System.Threading.Tasks.Task 套用截止投標日期區間()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("套用截止投標日期區間", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 75
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 76
    await testRunner.GivenAsync("Items 中 BidDeadline 介於 \"115/05/12\" 與 \"115/05/20\"（含）的筆數為 18", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 77
    await testRunner.WhenAsync(("設定 Criteria.BidDeadlineFrom = \"115/05/12\"、BidDeadlineTo = \"115/05/20\"，並呼叫 ApplySe" +
                        "archCommand"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 78
    await testRunner.ThenAsync("FilteredItems.Count 應為 18", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="同時套用多個篩選條件（AND 邏輯）")]
        [Xunit.TraitAttribute("FeatureTitle", "指定日期標案資料查詢")]
        [Xunit.TraitAttribute("Description", "同時套用多個篩選條件（AND 邏輯）")]
        public async System.Threading.Tasks.Task 同時套用多個篩選條件AND邏輯()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("同時套用多個篩選條件（AND 邏輯）", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 80
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 81
    await testRunner.WhenAsync(("設定 Criteria.TenderMethod = \"公開招標\"、ProcurementType = \"勞務類\"、ShowActiveOnly = true，並" +
                        "呼叫 ApplySearchCommand"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "條件"});
                table3.AddRow(new string[] {
                            "TenderMethod == \"公開招標\""});
                table3.AddRow(new string[] {
                            "ProcurementType == \"勞務類\""});
                table3.AddRow(new string[] {
                            "RocToDateOnly(BidDeadline) >= IClock.Today"});
#line 82
    await testRunner.ThenAsync("FilteredItems 每筆應同時符合：", ((string)(null)), table3, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="點擊欄位標題進行排序")]
        [Xunit.TraitAttribute("FeatureTitle", "指定日期標案資料查詢")]
        [Xunit.TraitAttribute("Description", "點擊欄位標題進行排序")]
        [Xunit.InlineDataAttribute("BudgetAmount", "Ascending", new string[0])]
        [Xunit.InlineDataAttribute("BudgetAmount", "Descending", new string[0])]
        [Xunit.InlineDataAttribute("AnnouncementDate", "Ascending", new string[0])]
        [Xunit.InlineDataAttribute("BidDeadline", "Ascending", new string[0])]
        [Xunit.InlineDataAttribute("AgencyName", "Ascending", new string[0])]
        public async System.Threading.Tasks.Task 點擊欄位標題進行排序(string sortKey, string direction, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("SortKey", sortKey);
            argumentsOfScenario.Add("Direction", direction);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("點擊欄位標題進行排序", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 91
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 92
    await testRunner.WhenAsync(string.Format("設定 DailyQueryViewModel.SortKey = {0}、SortDirection = {1}，並呼叫 ApplySearchCommand", sortKey, direction), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 93
    await testRunner.ThenAsync(string.Format("FilteredItems 應依 {0} 以 {1} 排序（null 值排於最後）", sortKey, direction), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="點擊「檢視」以預設瀏覽器開啟政府電子採購網標案頁")]
        [Xunit.TraitAttribute("FeatureTitle", "指定日期標案資料查詢")]
        [Xunit.TraitAttribute("Description", "點擊「檢視」以預設瀏覽器開啟政府電子採購網標案頁")]
        public async System.Threading.Tasks.Task 點擊檢視以預設瀏覽器開啟政府電子採購網標案頁()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("點擊「檢視」以預設瀏覽器開啟政府電子採購網標案頁", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 106
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 107
    await testRunner.GivenAsync(("FilteredItems[0].DetailUrl 為 \"https://web.pcc.gov.tw/prkms/urlSelector/common/tpa" +
                        "m?pk=NzEyMTUxODc=\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 108
    await testRunner.AndAsync("IBrowserLauncher 已被 Mock", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
    await testRunner.WhenAsync("呼叫 DailyQueryViewModel.OpenDetailCommand.Execute(FilteredItems[0])", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 110
    await testRunner.ThenAsync(("IBrowserLauncher.Open 應被呼叫一次，url 參數為 \"https://web.pcc.gov.tw/prkms/urlSelector/co" +
                        "mmon/tpam?pk=NzEyMTUxODc=\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="切換到前一天的查詢頁")]
        [Xunit.TraitAttribute("FeatureTitle", "指定日期標案資料查詢")]
        [Xunit.TraitAttribute("Description", "切換到前一天的查詢頁")]
        public async System.Threading.Tasks.Task 切換到前一天的查詢頁()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("切換到前一天的查詢頁", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 115
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 116
    await testRunner.GivenAsync("DailyQueryViewModel.Date 為 DateOnly(2026, 5, 8)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 117
    await testRunner.AndAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-07/tenders.json\" 存在，Items" +
                        " 共 42 筆"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 118
    await testRunner.WhenAsync("呼叫 DailyQueryViewModel.GoPreviousDayCommand.Execute(null)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 119
    await testRunner.ThenAsync("DailyQueryViewModel.Date 應為 DateOnly(2026, 5, 7)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 120
    await testRunner.AndAsync("DailyQueryViewModel.Items.Count 應為 42", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="切換到後一天但該日尚無資料")]
        [Xunit.TraitAttribute("FeatureTitle", "指定日期標案資料查詢")]
        [Xunit.TraitAttribute("Description", "切換到後一天但該日尚無資料")]
        public async System.Threading.Tasks.Task 切換到後一天但該日尚無資料()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("切換到後一天但該日尚無資料", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 122
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 123
    await testRunner.GivenAsync("DailyQueryViewModel.Date 為 DateOnly(2026, 5, 8)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 124
    await testRunner.AndAsync("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-09/tenders.json\" 不存在", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
    await testRunner.WhenAsync("呼叫 DailyQueryViewModel.GoNextDayCommand.Execute(null)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 126
    await testRunner.ThenAsync("DailyQueryViewModel.Date 應為 DateOnly(2026, 5, 9)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 127
    await testRunner.AndAsync("DailyQueryViewModel.Items.Count 應為 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 128
    await testRunner.AndAsync("DailyQueryViewModel.IsEmpty 應為 true（UI 顯示「該日尚無標案資料」）", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 129
    await testRunner.AndAsync("不應拋出任何例外", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="從查詢頁返回月份行事曆")]
        [Xunit.TraitAttribute("FeatureTitle", "指定日期標案資料查詢")]
        [Xunit.TraitAttribute("Description", "從查詢頁返回月份行事曆")]
        public async System.Threading.Tasks.Task 從查詢頁返回月份行事曆()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("從查詢頁返回月份行事曆", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 131
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 132
    await testRunner.GivenAsync("DailyQueryViewModel.Date 為 DateOnly(2026, 5, 8)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 133
    await testRunner.WhenAsync("呼叫 ShellViewModel.NavigateBackToCalendarCommand.Execute(null)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 134
    await testRunner.ThenAsync("ShellViewModel.CurrentDailyQueryVm 應為 null", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 135
    await testRunner.AndAsync("ShellViewModel.CalendarVm.Year 應為 2026，Month 應為 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="進入查詢頁時 tenders.json 損毀")]
        [Xunit.TraitAttribute("FeatureTitle", "指定日期標案資料查詢")]
        [Xunit.TraitAttribute("Description", "進入查詢頁時 tenders.json 損毀")]
        public async System.Threading.Tasks.Task 進入查詢頁時Tenders_Json損毀()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("進入查詢頁時 tenders.json 損毀", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 140
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 141
    await testRunner.GivenAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/tenders.json\" 內容為 \"{ b" +
                        "roken\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 142
    await testRunner.WhenAsync("建立 DailyQueryViewModel(date = 2026-05-08) 並呼叫 LoadCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 143
    await testRunner.ThenAsync("不應拋出例外", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 144
    await testRunner.AndAsync("DailyQueryViewModel.LoadError 應不為 null，訊息包含「資料檔案損毀」", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 145
    await testRunner.AndAsync("errors.log 應記錄 CorruptedDataException", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="搜尋無命中結果")]
        [Xunit.TraitAttribute("FeatureTitle", "指定日期標案資料查詢")]
        [Xunit.TraitAttribute("Description", "搜尋無命中結果")]
        public async System.Threading.Tasks.Task 搜尋無命中結果()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("搜尋無命中結果", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 147
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 148
    await testRunner.WhenAsync("設定 Criteria.KeywordQuery = \"找不到的關鍵字XYZ\"，並呼叫 ApplySearchCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 149
    await testRunner.ThenAsync("FilteredItems.Count 應為 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 150
    await testRunner.AndAsync("DailyQueryViewModel.IsEmpty 應為 true", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 151
    await testRunner.AndAsync("DailyQueryViewModel.LoadError 應為 null（這不是錯誤情境）", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await 指定日期標案資料查詢Feature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await 指定日期標案資料查詢Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
