// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tender.AcceptanceTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class 匯出ExcelFeature : object, Xunit.IClassFixture<匯出ExcelFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "匯出 Excel", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "export_excel.feature"
#line hidden
        
        public 匯出ExcelFeature(匯出ExcelFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 15
  #line hidden
#line 16
    await testRunner.GivenAsync("IClock.Now 回傳 \"2026-05-08T09:00:00+08:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 17
    await testRunner.AndAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/tenders.json\" 存在，Items" +
                    " 共 55 筆"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync("DailyQueryViewModel 已載入 Date = 2026-05-08", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.AndAsync("ISaveFileDialogService 已被 Mock", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="匯出當前日期的全部標案")]
        [Xunit.TraitAttribute("FeatureTitle", "匯出 Excel")]
        [Xunit.TraitAttribute("Description", "匯出當前日期的全部標案")]
        public async System.Threading.Tasks.Task 匯出當前日期的全部標案()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("匯出當前日期的全部標案", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 25
    await testRunner.GivenAsync("DailyQueryViewModel.FilteredItems.Count 為 55（未套用任何篩選）", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
    await testRunner.AndAsync("ISaveFileDialogService.ShowSaveAsXlsx 回傳 \"${TEST_OUTPUT}/標案_20260508.xlsx\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
    await testRunner.WhenAsync("呼叫 DailyQueryViewModel.ExportCommand.Execute(null)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
    await testRunner.ThenAsync("檔案 \"${TEST_OUTPUT}/標案_20260508.xlsx\" 應存在", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 29
    await testRunner.AndAsync("用 ClosedXML 開啟該檔案，第一張工作表的資料列數（不含表頭）應為 55", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
    await testRunner.AndAsync("第一張工作表的表頭（第 1 列）應至少包含：標案名稱、招標方式、採購性質、公告日期、截止投標、預算金額、機關名稱、檢視連結", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
    await testRunner.AndAsync("「標案名稱」或「檢視連結」欄的儲存格應具備可點擊超連結（IXLCell.HasHyperlink == true）", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="匯出套用篩選後的結果")]
        [Xunit.TraitAttribute("FeatureTitle", "匯出 Excel")]
        [Xunit.TraitAttribute("Description", "匯出套用篩選後的結果")]
        public async System.Threading.Tasks.Task 匯出套用篩選後的結果()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("匯出套用篩選後的結果", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 34
    await testRunner.GivenAsync("已呼叫 ToggleKeywordButtonCommand.Execute(\"AI\")，FilteredItems.Count 為 8", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
    await testRunner.AndAsync("ISaveFileDialogService.ShowSaveAsXlsx 回傳 \"${TEST_OUTPUT}/標案_20260508_AI.xlsx\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.WhenAsync("呼叫 ExportCommand.Execute(null)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
    await testRunner.ThenAsync("匯出檔案的資料列數（不含表頭）應為 8", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 38
    await testRunner.AndAsync("每筆「標案名稱」或「檢視連結」欄的超連結應指向對應 TenderItem.DetailUrl", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="匯出檔案格式適合再用 Excel 篩選")]
        [Xunit.TraitAttribute("FeatureTitle", "匯出 Excel")]
        [Xunit.TraitAttribute("Description", "匯出檔案格式適合再用 Excel 篩選")]
        public async System.Threading.Tasks.Task 匯出檔案格式適合再用Excel篩選()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("匯出檔案格式適合再用 Excel 篩選", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 40
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 41
    await testRunner.WhenAsync("呼叫 ExportCommand.Execute(null) 並完成匯出", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
    await testRunner.ThenAsync("匯出檔案副檔名應為 .xlsx", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 43
    await testRunner.AndAsync("表頭列應在第 1 列", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
    await testRunner.AndAsync("「預算金額」欄的儲存格資料型別應為 XLDataType.Number", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
    await testRunner.AndAsync("「公告日期」與「截止投標」欄的儲存格應為文字格式（保留民國年原文，例 \"115/05/08\"）", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="匯出結果具備「機關名稱：標案名稱」合併文字以取代 Excel 篩選工作表")]
        [Xunit.TraitAttribute("FeatureTitle", "匯出 Excel")]
        [Xunit.TraitAttribute("Description", "匯出結果具備「機關名稱：標案名稱」合併文字以取代 Excel 篩選工作表")]
        public async System.Threading.Tasks.Task 匯出結果具備機關名稱標案名稱合併文字以取代Excel篩選工作表()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("匯出結果具備「機關名稱：標案名稱」合併文字以取代 Excel 篩選工作表", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 50
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 51
    await testRunner.GivenAsync("FilteredItems[0].AgencyName 為 \"經濟部水利署\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 52
    await testRunner.AndAsync("FilteredItems[0].TenderName 為 \"智慧水利監測系統建置案\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
    await testRunner.AndAsync(("FilteredItems[0].DetailUrl 為 \"https://web.pcc.gov.tw/prkms/urlSelector/common/tpa" +
                        "m?pk=ABC\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
    await testRunner.WhenAsync("呼叫 ExportCommand.Execute(null) 並完成匯出", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
    await testRunner.ThenAsync("匯出檔案應包含一欄表頭為「機關名稱：標案名稱」", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 56
    await testRunner.AndAsync("該欄第一筆資料儲存格的文字應為 \"經濟部水利署：智慧水利監測系統建置案\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
    await testRunner.AndAsync(("該儲存格的 Hyperlink.ExternalAddress 應為 \"https://web.pcc.gov.tw/prkms/urlSelector/comm" +
                        "on/tpam?pk=ABC\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="匯出時沒有任何資料")]
        [Xunit.TraitAttribute("FeatureTitle", "匯出 Excel")]
        [Xunit.TraitAttribute("Description", "匯出時沒有任何資料")]
        public async System.Threading.Tasks.Task 匯出時沒有任何資料()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("匯出時沒有任何資料", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 62
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 63
    await testRunner.GivenAsync("DailyQueryViewModel.FilteredItems.Count 為 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 64
    await testRunner.WhenAsync("呼叫 ExportCommand.Execute(null)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
    await testRunner.ThenAsync("ISaveFileDialogService.ShowSaveAsXlsx 不應被呼叫", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 66
    await testRunner.AndAsync("IExcelExporter.ExportAsync 不應被呼叫", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 67
    await testRunner.AndAsync("DailyQueryViewModel.LastUserMessage 應包含「目前沒有可匯出的資料」", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
    await testRunner.AndAsync("不應產生任何 .xlsx 檔案", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="匯出包含特殊字元的標案資料")]
        [Xunit.TraitAttribute("FeatureTitle", "匯出 Excel")]
        [Xunit.TraitAttribute("Description", "匯出包含特殊字元的標案資料")]
        public async System.Threading.Tasks.Task 匯出包含特殊字元的標案資料()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("匯出包含特殊字元的標案資料", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 71
    await testRunner.GivenAsync("FilteredItems 中某筆 TenderName 為 \"「智慧」（永續）＆ESG％專案\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
    await testRunner.AndAsync("ISaveFileDialogService.ShowSaveAsXlsx 回傳 \"${TEST_OUTPUT}/special.xlsx\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
    await testRunner.WhenAsync("呼叫 ExportCommand.Execute(null)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 74
    await testRunner.ThenAsync("用 ClosedXML 重新讀回該儲存格的字串應完全等於 \"「智慧」（永續）＆ESG％專案\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="寫入匯出檔失敗（檔案被使用者開啟中）")]
        [Xunit.TraitAttribute("FeatureTitle", "匯出 Excel")]
        [Xunit.TraitAttribute("Description", "寫入匯出檔失敗（檔案被使用者開啟中）")]
        public async System.Threading.Tasks.Task 寫入匯出檔失敗檔案被使用者開啟中()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("寫入匯出檔失敗（檔案被使用者開啟中）", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 79
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 80
    await testRunner.GivenAsync("ISaveFileDialogService.ShowSaveAsXlsx 回傳 \"${TEST_OUTPUT}/locked.xlsx\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 81
    await testRunner.AndAsync("檔案 \"${TEST_OUTPUT}/locked.xlsx\" 已被另一個程序以獨佔模式開啟", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
    await testRunner.WhenAsync("呼叫 ExportCommand.Execute(null)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 83
    await testRunner.ThenAsync("不應拋出未處理例外", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 84
    await testRunner.AndAsync("DailyQueryViewModel.LastUserMessage 應包含「目標檔案正被其他程式使用」", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
    await testRunner.AndAsync("errors.log 應記錄該次 IOException", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="匯出過程被使用者取消")]
        [Xunit.TraitAttribute("FeatureTitle", "匯出 Excel")]
        [Xunit.TraitAttribute("Description", "匯出過程被使用者取消")]
        public async System.Threading.Tasks.Task 匯出過程被使用者取消()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("匯出過程被使用者取消", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 87
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
  await this.FeatureBackgroundAsync();
#line hidden
#line 88
    await testRunner.GivenAsync("ISaveFileDialogService.ShowSaveAsXlsx 回傳 null（使用者取消）", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 89
    await testRunner.WhenAsync("呼叫 ExportCommand.Execute(null)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 90
    await testRunner.ThenAsync("IExcelExporter.ExportAsync 不應被呼叫", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 91
    await testRunner.AndAsync("不應產生任何 .xlsx 檔案", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
    await testRunner.AndAsync("DailyQueryViewModel 狀態應與匯出前相同", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await 匯出ExcelFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await 匯出ExcelFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
