// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tender.AcceptanceTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class 安裝與排程任務建立Feature : object, Xunit.IClassFixture<安裝與排程任務建立Feature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "安裝與排程任務建立", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "installation.feature"
#line hidden
        
        public 安裝與排程任務建立Feature(安裝與排程任務建立Feature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 21
  #line hidden
#line 22
    await testRunner.GivenAsync("測試環境變數 ${TEST_LOCAL_APP_DATA} 指向臨時目錄取代 %LocalAppData%", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 23
    await testRunner.AndAsync("測試使用 ITaskSchedulerAdapter 的 InMemory Mock 取代真實 Windows Task Scheduler", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="全新安裝完成，建立資料根目錄、捷徑與排程任務")]
        [Xunit.TraitAttribute("FeatureTitle", "安裝與排程任務建立")]
        [Xunit.TraitAttribute("Description", "全新安裝完成，建立資料根目錄、捷徑與排程任務")]
        public async System.Threading.Tasks.Task 全新安裝完成建立資料根目錄捷徑與排程任務()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("全新安裝完成，建立資料根目錄、捷徑與排程任務", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 30
    await testRunner.GivenAsync("${TEST_LOCAL_APP_DATA}/TenderSearch/ 目錄不存在", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
    await testRunner.AndAsync("ITaskSchedulerAdapter 中沒有名為 \"TenderSearch.DailyCrawl\" 的任務", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
    await testRunner.WhenAsync("執行 DataDirectoryActions.EnsureDataRoot()", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
    await testRunner.AndAsync("執行 TaskSchedulerActions.CreateDailyTask()", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
    await testRunner.ThenAsync("目錄 \"${TEST_LOCAL_APP_DATA}/TenderSearch/data/\" 應存在", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 35
    await testRunner.AndAsync("目錄 \"${TEST_LOCAL_APP_DATA}/TenderSearch/data/settings/\" 應存在", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.AndAsync(("檔案 \"${TEST_LOCAL_APP_DATA}/TenderSearch/data/settings/keywords.json\" 應存在，且可被反序列化為" +
                        " KeywordSet"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
    await testRunner.AndAsync("ITaskSchedulerAdapter 應含名為 \"TenderSearch.DailyCrawl\" 的任務", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
    await testRunner.AndAsync("該任務的 ScheduledTime 應為 \"17:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
    await testRunner.AndAsync("該任務的 StartWhenAvailable 旗標應為 true", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
    await testRunner.AndAsync("該任務的 RunLevel 應為 LeastPrivilege（per-user）", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="安裝完成後排程可實際執行")]
        [Xunit.TraitAttribute("FeatureTitle", "安裝與排程任務建立")]
        [Xunit.TraitAttribute("Description", "安裝完成後排程可實際執行")]
        public async System.Threading.Tasks.Task 安裝完成後排程可實際執行()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("安裝完成後排程可實際執行", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 45
    await testRunner.GivenAsync("已成功執行 EnsureDataRoot 與 CreateDailyTask", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 46
    await testRunner.AndAsync("ITaskSchedulerAdapter Mock 設定為「在指定時間立即觸發 Action」", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
    await testRunner.AndAsync("IClock.Now 設定為 \"2026-05-08T17:00:00+08:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
    await testRunner.WhenAsync("ITaskSchedulerAdapter 觸發 \"TenderSearch.DailyCrawl\" 對應的 Action", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
    await testRunner.ThenAsync("ICrawlerLauncher 應接收到 (Mode = Scheduled, TargetDate = 2026-05-08) 的呼叫", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
    await testRunner.AndAsync(("桌面程式可未開啟，仍應在 \"${TEST_LOCAL_APP_DATA}/TenderSearch/data/2026-05/2026-05-08/\" 產生 te" +
                        "nders.json"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="重新安裝時不可覆蓋已存在的資料目錄")]
        [Xunit.TraitAttribute("FeatureTitle", "安裝與排程任務建立")]
        [Xunit.TraitAttribute("Description", "重新安裝時不可覆蓋已存在的資料目錄")]
        public async System.Threading.Tasks.Task 重新安裝時不可覆蓋已存在的資料目錄()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("重新安裝時不可覆蓋已存在的資料目錄", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 55
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 56
    await testRunner.GivenAsync(("目錄 \"${TEST_LOCAL_APP_DATA}/TenderSearch/data/2026-04-15/\" 已存在，含 tenders.json 與 su" +
                        "mmary.json"), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 57
    await testRunner.WhenAsync("再次執行 DataDirectoryActions.EnsureDataRoot()", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
    await testRunner.ThenAsync(("既有檔案 \"${TEST_LOCAL_APP_DATA}/TenderSearch/data/2026-04-15/tenders.json\" 內容與時間戳應與安" +
                        "裝前一致"), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 59
    await testRunner.AndAsync("不應有任何既有檔案被刪除或覆寫", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="重新安裝時若排程任務已存在不應重複建立")]
        [Xunit.TraitAttribute("FeatureTitle", "安裝與排程任務建立")]
        [Xunit.TraitAttribute("Description", "重新安裝時若排程任務已存在不應重複建立")]
        public async System.Threading.Tasks.Task 重新安裝時若排程任務已存在不應重複建立()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("重新安裝時若排程任務已存在不應重複建立", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 61
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 62
    await testRunner.GivenAsync("ITaskSchedulerAdapter 已含名為 \"TenderSearch.DailyCrawl\" 的任務，ScheduledTime 為 \"17:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 63
    await testRunner.WhenAsync("再次執行 TaskSchedulerActions.CreateDailyTask()", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
    await testRunner.ThenAsync("ITaskSchedulerAdapter 中名為 \"TenderSearch.DailyCrawl\" 的任務只應有 1 個", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 65
    await testRunner.AndAsync("該任務的 ScheduledTime 應仍為 \"17:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="沒有權限建立排程任務")]
        [Xunit.TraitAttribute("FeatureTitle", "安裝與排程任務建立")]
        [Xunit.TraitAttribute("Description", "沒有權限建立排程任務")]
        public async System.Threading.Tasks.Task 沒有權限建立排程任務()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("沒有權限建立排程任務", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 71
    await testRunner.GivenAsync(("ITaskSchedulerAdapter Mock 設定為「呼叫 RegisterTaskAsync 時拋 UnauthorizedAccessExceptio" +
                        "n」"), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
    await testRunner.WhenAsync("執行 TaskSchedulerActions.CreateDailyTask()", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
    await testRunner.ThenAsync("回傳的 ActionResult 應為 ActionResult.NotExecuted（或自訂 PartialSuccess）", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 74
    await testRunner.AndAsync("InstallationOutcome.ScheduledTaskCreated 應為 false", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
    await testRunner.AndAsync("安裝結果摘要應包含「排程任務未建立，請手動於 Task Scheduler 設定每日 17:00」字樣", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="資料根目錄無法建立")]
        [Xunit.TraitAttribute("FeatureTitle", "安裝與排程任務建立")]
        [Xunit.TraitAttribute("Description", "資料根目錄無法建立")]
        public async System.Threading.Tasks.Task 資料根目錄無法建立()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("資料根目錄無法建立", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 78
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 79
    await testRunner.GivenAsync("${TEST_LOCAL_APP_DATA}/TenderSearch/ 路徑被測試環境設為無寫入權限", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 80
    await testRunner.WhenAsync("執行 DataDirectoryActions.EnsureDataRoot()", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
    await testRunner.ThenAsync("回傳的 ActionResult 應為 ActionResult.Failure", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 82
    await testRunner.AndAsync("不應呼叫後續的 TaskSchedulerActions.CreateDailyTask", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
    await testRunner.AndAsync("安裝程序應中止，不應留下任何捷徑或排程任務", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="安裝過程中使用者取消")]
        [Xunit.TraitAttribute("FeatureTitle", "安裝與排程任務建立")]
        [Xunit.TraitAttribute("Description", "安裝過程中使用者取消")]
        public async System.Threading.Tasks.Task 安裝過程中使用者取消()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("安裝過程中使用者取消", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 85
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 87
    await testRunner.GivenAsync("已執行 EnsureDataRoot（資料目錄已建立）", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 88
    await testRunner.WhenAsync("使用者於安裝精靈點選「取消」", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
    await testRunner.ThenAsync("WiX Rollback 應移除本次安裝建立的捷徑檔案", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 90
    await testRunner.AndAsync("ITaskSchedulerAdapter 不應含名為 \"TenderSearch.DailyCrawl\" 的任務", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
    await testRunner.AndAsync("既有的資料根目錄（若安裝前已存在）應保留", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="解除安裝時保留使用者既有資料")]
        [Xunit.TraitAttribute("FeatureTitle", "安裝與排程任務建立")]
        [Xunit.TraitAttribute("Description", "解除安裝時保留使用者既有資料")]
        public async System.Threading.Tasks.Task 解除安裝時保留使用者既有資料()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("解除安裝時保留使用者既有資料", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 97
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
  await this.FeatureBackgroundAsync();
#line hidden
#line 98
    await testRunner.GivenAsync("目錄 \"${TEST_LOCAL_APP_DATA}/TenderSearch/data/2026-04-15/\" 含使用者歷史資料", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 99
    await testRunner.AndAsync("ITaskSchedulerAdapter 含名為 \"TenderSearch.DailyCrawl\" 的任務", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 100
    await testRunner.WhenAsync("執行 TaskSchedulerActions.RemoveDailyTask()", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 101
    await testRunner.AndAsync("執行 WiX 的 Uninstall 流程（移除捷徑與安裝目錄程式檔）", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 102
    await testRunner.ThenAsync("ITaskSchedulerAdapter 不應含名為 \"TenderSearch.DailyCrawl\" 的任務", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 103
    await testRunner.AndAsync("目錄 \"${TEST_LOCAL_APP_DATA}/TenderSearch/data/\" 與其下的歷史資料應完整保留", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await 安裝與排程任務建立Feature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await 安裝與排程任務建立Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
