# language: en
# Generated by sa-expert
# Source: pm/features/keyword_filter.feature
# Project scan date: 2026-05-08
# Module type: WPF Desktop (Tender.Desktop) + Core Keywords (Tender.Core)
# Architecture: DailyQueryViewModel.ToggleKeywordButton → IKeywordMatcher → ISearchService
# Step Definitions: tests/Tender.AcceptanceTests/Steps/KeywordFilterSteps.cs

Feature: 關鍵字快速篩選（沿用 Excel 既有關鍵字）
  # 業務模組：Bounded Context 4 - Keyword Filter
  # 關鍵字命中：Tender.Core.Keywords.IKeywordMatcher
  # 搜尋整合：Tender.Core.Search.ISearchService（透過 SearchCriteria.ActiveKeywordButtons）
  # 關鍵字資料源：Tender.Storage.Repositories.IKeywordsRepository → settings/keywords.json

  # 關鍵字行為差異備註（依使用者決議與 PM 文件）：
  # - 搜尋框（KeywordQuery）：以空白分割多關鍵字，採 AND 命中 + 模糊查詢（已決議）
  # - 關鍵字按鈕（ActiveKeywordButtons）：多按鈕同時啟用採 OR 命中（沿用 Excel 既有行為，PM Gherkin 明確指定）
  # - 兩者疊加：搜尋框 AND 關鍵字按鈕（AND 邏輯）

  Background:
    Given IClock.Now 回傳 "2026-05-08T09:00:00+08:00"
    And IKeywordsRepository.LoadAsync() 回傳預設 KeywordSet（含資訊系統、XR/AI、資安/無障礙、ESG/碳管理、業務雜項、智慧管考、倉儲自動化、地區、指定機關共 9 個 Group）
    And 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/tenders.json" 存在，Items 共 55 筆
    And DailyQueryViewModel 已載入 Date = 2026-05-08

  # ----------------------------------------------------------
  # Happy path（標案名稱方向）
  # ----------------------------------------------------------
  Scenario Outline: 點擊資訊系統類關鍵字按鈕，於標案名稱命中
    Given Items 中 TenderName 含 "<關鍵字>" 的筆數為 <筆數>
    When 呼叫 DailyQueryViewModel.ToggleKeywordButtonCommand.Execute("<關鍵字>")
    Then DailyQueryViewModel.Criteria.ActiveKeywordButtons 應包含 "<關鍵字>"
    And FilteredItems.Count 應為 <筆數>
    And FilteredItems 每筆的 MatchedKeywords 應包含 "<關鍵字>"

    Examples:
      | 關鍵字   | 筆數 |
      | 系統     | 12   |
      | 數位     | 9    |
      | 平台     | 5    |
      | AI       | 8    |
      | 人工智慧 | 4    |
      | 永續     | 3    |
      | 倉儲     | 2    |

  # ----------------------------------------------------------
  # 機關方向
  # ----------------------------------------------------------
  Scenario: 點擊指定機關按鈕，於機關名稱命中
    Given Items 中 AgencyName 含 "經濟部水利署" 的筆數為 3
    And KeywordSet 中 "經濟部水利署" 的 TargetField 為 "agencyName"
    When 呼叫 DailyQueryViewModel.ToggleKeywordButtonCommand.Execute("經濟部水利署")
    Then FilteredItems.Count 應為 3
    And FilteredItems 每筆的 AgencyName 應包含 "經濟部水利署"

  # ----------------------------------------------------------
  # 地區方向
  # ----------------------------------------------------------
  Scenario: 點擊地區按鈕，於機關名稱或標案名稱命中
    Given Items 中 (AgencyName 含 "高雄") 或 (TenderName 含 "高雄") 的筆數為 7
    And KeywordSet 中 "高雄" 的 TargetField 為 "any"
    When 呼叫 DailyQueryViewModel.ToggleKeywordButtonCommand.Execute("高雄")
    Then FilteredItems.Count 應為 7
    And FilteredItems 每筆應符合 (AgencyName 含 "高雄") 或 (TenderName 含 "高雄")

  # ----------------------------------------------------------
  # 多關鍵字按鈕並用（OR 命中，沿用 Excel 既有行為）
  # ----------------------------------------------------------
  Scenario: 同時套用多個關鍵字按鈕（OR 命中，沿用 Excel 既有行為）
    Given Items 中 TenderName 含 "AI" 的標案有 8 筆
    And Items 中 TenderName 含 "雲端" 的標案有 5 筆
    And 上述兩組之中重疊（同時含 AI 與 雲端）的標案有 1 筆
    When 呼叫 ToggleKeywordButtonCommand.Execute("AI")
    And 呼叫 ToggleKeywordButtonCommand.Execute("雲端")
    Then DailyQueryViewModel.Criteria.ActiveKeywordButtons 應為 ["AI", "雲端"]
    And FilteredItems.Count 應為 12（8 + 5 - 1）
    And 同時包含兩個關鍵字的那 1 筆，其 MatchedKeywords 應同時包含 "AI" 與 "雲端"

  # ----------------------------------------------------------
  # 命中關鍵字標註（爬蟲端寫入時的測試）
  # ----------------------------------------------------------
  Scenario: 命中關鍵字應寫入 matchedKeywords 欄位
    # 對應 Step Definition：直接呼叫 IKeywordMatcher.Match 驗證寫入端邏輯
    Given 一個 TenderItem，TenderName = "智慧倉儲管理系統建置案"
    When 呼叫 IKeywordMatcher.Match(item, predefinedKeywordSet)
    Then 回傳的命中清單應包含 "智慧"、"倉儲"、"管理"、"系統"、"建置"
    And 該 TenderItem 經 ICrawlerOrchestrator 處理後，寫入 tenders.json 的 MatchedKeywords 應包含上述項目

  # ----------------------------------------------------------
  # 清除篩選
  # ----------------------------------------------------------
  Scenario: 清除關鍵字篩選後恢復顯示全部該日標案
    Given 已呼叫 ToggleKeywordButtonCommand.Execute("AI")，FilteredItems.Count 為 8
    When 呼叫 DailyQueryViewModel.ClearKeywordFilterCommand.Execute(null)
    Then DailyQueryViewModel.Criteria.ActiveKeywordButtons 應為空陣列
    And FilteredItems.Count 應為 55

  # ----------------------------------------------------------
  # 搜尋與關鍵字按鈕並用（AND 邏輯）
  # ----------------------------------------------------------
  Scenario: 關鍵字按鈕與搜尋框可疊加使用（AND 邏輯）
    Given 已呼叫 ToggleKeywordButtonCommand.Execute("AI")，FilteredItems.Count 為 8
    When 設定 Criteria.KeywordQuery = "教育"，並呼叫 ApplySearchCommand
    Then FilteredItems 每筆應同時符合：
      | 條件                                            |
      | 命中關鍵字按鈕 "AI"（即 MatchedKeywords 含 "AI" 或 TenderName 含 "AI"） |
      | TenderName 或 AgencyName 或 TenderNo 含 "教育"  |

  # ----------------------------------------------------------
  # 搜尋框多關鍵字 AND 命中 + 模糊查詢（依使用者決議）
  # ----------------------------------------------------------
  Scenario: 搜尋框多關鍵字採 AND 命中（已決議）
    # 此 Scenario 為 SA 補充，對應使用者於 2026-05-08 的決議
    Given Items 中 TenderName 含 "智慧" 且也含 "倉儲" 的筆數為 2
    When 設定 Criteria.KeywordQuery = "智慧 倉儲"，並呼叫 ApplySearchCommand
    Then FilteredItems.Count 應為 2
    And FilteredItems 每筆的 TenderName 或 AgencyName 或 TenderNo 應同時包含子字串 "智慧" 與 "倉儲"

  # ----------------------------------------------------------
  # 邊界情境
  # ----------------------------------------------------------
  Scenario: 該日無任何標案命中所選關鍵字
    Given Items 中無任何 TenderName 含 "AVG" 的標案
    When 呼叫 ToggleKeywordButtonCommand.Execute("AVG")
    Then FilteredItems.Count 應為 0
    And DailyQueryViewModel.IsEmpty 應為 true
    And DailyQueryViewModel.LoadError 應為 null
