// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tender.AcceptanceTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class 關鍵字快速篩選沿用Excel既有關鍵字Feature : object, Xunit.IClassFixture<關鍵字快速篩選沿用Excel既有關鍵字Feature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "關鍵字快速篩選（沿用 Excel 既有關鍵字）", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "keyword_filter.feature"
#line hidden
        
        public 關鍵字快速篩選沿用Excel既有關鍵字Feature(關鍵字快速篩選沿用Excel既有關鍵字Feature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 20
  #line hidden
#line 21
    await testRunner.GivenAsync("IClock.Now 回傳 \"2026-05-08T09:00:00+08:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
    await testRunner.AndAsync(("IKeywordsRepository.LoadAsync() 回傳預設 KeywordSet（含資訊系統、XR/AI、資安/無障礙、ESG/碳管理、業務雜項、智" +
                    "慧管考、倉儲自動化、地區、指定機關共 9 個 Group）"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
    await testRunner.AndAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/tenders.json\" 存在，Items" +
                    " 共 55 筆"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
    await testRunner.AndAsync("DailyQueryViewModel 已載入 Date = 2026-05-08", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="點擊資訊系統類關鍵字按鈕，於標案名稱命中")]
        [Xunit.TraitAttribute("FeatureTitle", "關鍵字快速篩選（沿用 Excel 既有關鍵字）")]
        [Xunit.TraitAttribute("Description", "點擊資訊系統類關鍵字按鈕，於標案名稱命中")]
        [Xunit.InlineDataAttribute("系統", "12", new string[0])]
        [Xunit.InlineDataAttribute("數位", "9", new string[0])]
        [Xunit.InlineDataAttribute("平台", "5", new string[0])]
        [Xunit.InlineDataAttribute("AI", "8", new string[0])]
        [Xunit.InlineDataAttribute("人工智慧", "4", new string[0])]
        [Xunit.InlineDataAttribute("永續", "3", new string[0])]
        [Xunit.InlineDataAttribute("倉儲", "2", new string[0])]
        public async System.Threading.Tasks.Task 點擊資訊系統類關鍵字按鈕於標案名稱命中(string 關鍵字, string 筆數, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("關鍵字", 關鍵字);
            argumentsOfScenario.Add("筆數", 筆數);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("點擊資訊系統類關鍵字按鈕，於標案名稱命中", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
  await this.FeatureBackgroundAsync();
#line hidden
#line 30
    await testRunner.GivenAsync(string.Format("Items 中 TenderName 含 \"{0}\" 的筆數為 {1}", 關鍵字, 筆數), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
    await testRunner.WhenAsync(string.Format("呼叫 DailyQueryViewModel.ToggleKeywordButtonCommand.Execute(\"{0}\")", 關鍵字), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
    await testRunner.ThenAsync(string.Format("DailyQueryViewModel.Criteria.ActiveKeywordButtons 應包含 \"{0}\"", 關鍵字), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 33
    await testRunner.AndAsync(string.Format("FilteredItems.Count 應為 {0}", 筆數), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
    await testRunner.AndAsync(string.Format("FilteredItems 每筆的 MatchedKeywords 應包含 \"{0}\"", 關鍵字), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="點擊指定機關按鈕，於機關名稱命中")]
        [Xunit.TraitAttribute("FeatureTitle", "關鍵字快速篩選（沿用 Excel 既有關鍵字）")]
        [Xunit.TraitAttribute("Description", "點擊指定機關按鈕，於機關名稱命中")]
        public async System.Threading.Tasks.Task 點擊指定機關按鈕於機關名稱命中()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("點擊指定機關按鈕，於機關名稱命中", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 49
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
  await this.FeatureBackgroundAsync();
#line hidden
#line 50
    await testRunner.GivenAsync("Items 中 AgencyName 含 \"經濟部水利署\" 的筆數為 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 51
    await testRunner.AndAsync("KeywordSet 中 \"經濟部水利署\" 的 TargetField 為 \"agencyName\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
    await testRunner.WhenAsync("呼叫 DailyQueryViewModel.ToggleKeywordButtonCommand.Execute(\"經濟部水利署\")", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
    await testRunner.ThenAsync("FilteredItems.Count 應為 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 54
    await testRunner.AndAsync("FilteredItems 每筆的 AgencyName 應包含 \"經濟部水利署\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="點擊地區按鈕，於機關名稱或標案名稱命中")]
        [Xunit.TraitAttribute("FeatureTitle", "關鍵字快速篩選（沿用 Excel 既有關鍵字）")]
        [Xunit.TraitAttribute("Description", "點擊地區按鈕，於機關名稱或標案名稱命中")]
        public async System.Threading.Tasks.Task 點擊地區按鈕於機關名稱或標案名稱命中()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("點擊地區按鈕，於機關名稱或標案名稱命中", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 59
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
  await this.FeatureBackgroundAsync();
#line hidden
#line 60
    await testRunner.GivenAsync("Items 中 (AgencyName 含 \"高雄\") 或 (TenderName 含 \"高雄\") 的筆數為 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 61
    await testRunner.AndAsync("KeywordSet 中 \"高雄\" 的 TargetField 為 \"any\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
    await testRunner.WhenAsync("呼叫 DailyQueryViewModel.ToggleKeywordButtonCommand.Execute(\"高雄\")", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
    await testRunner.ThenAsync("FilteredItems.Count 應為 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 64
    await testRunner.AndAsync("FilteredItems 每筆應符合 (AgencyName 含 \"高雄\") 或 (TenderName 含 \"高雄\")", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="同時套用多個關鍵字按鈕（OR 命中，沿用 Excel 既有行為）")]
        [Xunit.TraitAttribute("FeatureTitle", "關鍵字快速篩選（沿用 Excel 既有關鍵字）")]
        [Xunit.TraitAttribute("Description", "同時套用多個關鍵字按鈕（OR 命中，沿用 Excel 既有行為）")]
        public async System.Threading.Tasks.Task 同時套用多個關鍵字按鈕OR命中沿用Excel既有行為()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("同時套用多個關鍵字按鈕（OR 命中，沿用 Excel 既有行為）", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 69
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
  await this.FeatureBackgroundAsync();
#line hidden
#line 70
    await testRunner.GivenAsync("Items 中 TenderName 含 \"AI\" 的標案有 8 筆", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 71
    await testRunner.AndAsync("Items 中 TenderName 含 \"雲端\" 的標案有 5 筆", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
    await testRunner.AndAsync("上述兩組之中重疊（同時含 AI 與 雲端）的標案有 1 筆", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
    await testRunner.WhenAsync("呼叫 ToggleKeywordButtonCommand.Execute(\"AI\")", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 74
    await testRunner.AndAsync("呼叫 ToggleKeywordButtonCommand.Execute(\"雲端\")", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
    await testRunner.ThenAsync("DailyQueryViewModel.Criteria.ActiveKeywordButtons 應為 [\"AI\", \"雲端\"]", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 76
    await testRunner.AndAsync("FilteredItems.Count 應為 12（8 + 5 - 1）", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
    await testRunner.AndAsync("同時包含兩個關鍵字的那 1 筆，其 MatchedKeywords 應同時包含 \"AI\" 與 \"雲端\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="命中關鍵字應寫入 matchedKeywords 欄位")]
        [Xunit.TraitAttribute("FeatureTitle", "關鍵字快速篩選（沿用 Excel 既有關鍵字）")]
        [Xunit.TraitAttribute("Description", "命中關鍵字應寫入 matchedKeywords 欄位")]
        public async System.Threading.Tasks.Task 命中關鍵字應寫入MatchedKeywords欄位()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("命中關鍵字應寫入 matchedKeywords 欄位", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 82
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
  await this.FeatureBackgroundAsync();
#line hidden
#line 84
    await testRunner.GivenAsync("一個 TenderItem，TenderName = \"智慧倉儲管理系統建置案\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 85
    await testRunner.WhenAsync("呼叫 IKeywordMatcher.Match(item, predefinedKeywordSet)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 86
    await testRunner.ThenAsync("回傳的命中清單應包含 \"智慧\"、\"倉儲\"、\"管理\"、\"系統\"、\"建置\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 87
    await testRunner.AndAsync("該 TenderItem 經 ICrawlerOrchestrator 處理後，寫入 tenders.json 的 MatchedKeywords 應包含上述項目", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="清除關鍵字篩選後恢復顯示全部該日標案")]
        [Xunit.TraitAttribute("FeatureTitle", "關鍵字快速篩選（沿用 Excel 既有關鍵字）")]
        [Xunit.TraitAttribute("Description", "清除關鍵字篩選後恢復顯示全部該日標案")]
        public async System.Threading.Tasks.Task 清除關鍵字篩選後恢復顯示全部該日標案()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("清除關鍵字篩選後恢復顯示全部該日標案", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 92
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
  await this.FeatureBackgroundAsync();
#line hidden
#line 93
    await testRunner.GivenAsync("已呼叫 ToggleKeywordButtonCommand.Execute(\"AI\")，FilteredItems.Count 為 8", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 94
    await testRunner.WhenAsync("呼叫 DailyQueryViewModel.ClearKeywordFilterCommand.Execute(null)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 95
    await testRunner.ThenAsync("DailyQueryViewModel.Criteria.ActiveKeywordButtons 應為空陣列", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 96
    await testRunner.AndAsync("FilteredItems.Count 應為 55", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="關鍵字按鈕與搜尋框可疊加使用（AND 邏輯）")]
        [Xunit.TraitAttribute("FeatureTitle", "關鍵字快速篩選（沿用 Excel 既有關鍵字）")]
        [Xunit.TraitAttribute("Description", "關鍵字按鈕與搜尋框可疊加使用（AND 邏輯）")]
        public async System.Threading.Tasks.Task 關鍵字按鈕與搜尋框可疊加使用AND邏輯()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("關鍵字按鈕與搜尋框可疊加使用（AND 邏輯）", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 101
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
  await this.FeatureBackgroundAsync();
#line hidden
#line 102
    await testRunner.GivenAsync("已呼叫 ToggleKeywordButtonCommand.Execute(\"AI\")，FilteredItems.Count 為 8", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 103
    await testRunner.WhenAsync("設定 Criteria.KeywordQuery = \"教育\"，並呼叫 ApplySearchCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "條件"});
                table4.AddRow(new string[] {
                            "命中關鍵字按鈕 \"AI\"（即 MatchedKeywords 含 \"AI\" 或 TenderName 含 \"AI\"）"});
                table4.AddRow(new string[] {
                            "TenderName 或 AgencyName 或 TenderNo 含 \"教育\""});
#line 104
    await testRunner.ThenAsync("FilteredItems 每筆應同時符合：", ((string)(null)), table4, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="搜尋框多關鍵字採 AND 命中（已決議）")]
        [Xunit.TraitAttribute("FeatureTitle", "關鍵字快速篩選（沿用 Excel 既有關鍵字）")]
        [Xunit.TraitAttribute("Description", "搜尋框多關鍵字採 AND 命中（已決議）")]
        public async System.Threading.Tasks.Task 搜尋框多關鍵字採AND命中已決議()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("搜尋框多關鍵字採 AND 命中（已決議）", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 112
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
  await this.FeatureBackgroundAsync();
#line hidden
#line 114
    await testRunner.GivenAsync("Items 中 TenderName 含 \"智慧\" 且也含 \"倉儲\" 的筆數為 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 115
    await testRunner.WhenAsync("設定 Criteria.KeywordQuery = \"智慧 倉儲\"，並呼叫 ApplySearchCommand", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 116
    await testRunner.ThenAsync("FilteredItems.Count 應為 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 117
    await testRunner.AndAsync("FilteredItems 每筆的 TenderName 或 AgencyName 或 TenderNo 應同時包含子字串 \"智慧\" 與 \"倉儲\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="該日無任何標案命中所選關鍵字")]
        [Xunit.TraitAttribute("FeatureTitle", "關鍵字快速篩選（沿用 Excel 既有關鍵字）")]
        [Xunit.TraitAttribute("Description", "該日無任何標案命中所選關鍵字")]
        public async System.Threading.Tasks.Task 該日無任何標案命中所選關鍵字()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("該日無任何標案命中所選關鍵字", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 122
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
  await this.FeatureBackgroundAsync();
#line hidden
#line 123
    await testRunner.GivenAsync("Items 中無任何 TenderName 含 \"AVG\" 的標案", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 124
    await testRunner.WhenAsync("呼叫 ToggleKeywordButtonCommand.Execute(\"AVG\")", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 125
    await testRunner.ThenAsync("FilteredItems.Count 應為 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 126
    await testRunner.AndAsync("DailyQueryViewModel.IsEmpty 應為 true", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 127
    await testRunner.AndAsync("DailyQueryViewModel.LoadError 應為 null", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await 關鍵字快速篩選沿用Excel既有關鍵字Feature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await 關鍵字快速篩選沿用Excel既有關鍵字Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
