# language: en
# Generated by sa-expert
# Source: pm/features/monthly_calendar.feature
# Project scan date: 2026-05-08
# Module type: WPF Desktop (Tender.Desktop) + Storage (Tender.Storage)
# Architecture: ShellViewModel → IMonthlyCalendarService → IDailySummaryRepository → summary.json
# Step Definitions: tests/Tender.AcceptanceTests/Steps/MonthlyCalendarSteps.cs

Feature: 月份行事曆首頁
  # 業務模組：Bounded Context 2 - Monthly Calendar
  # 主要協調者：Tender.Desktop.Services.IMonthlyCalendarService
  # 讀取端：Tender.Storage.Repositories.IDailySummaryRepository
  # ViewModel：Tender.Desktop.ViewModels.MonthlyCalendarViewModel + ShellViewModel.SideSummaryVm
  # 錯誤呈現：Tender.Desktop.Services.IErrorSummaryDialog

  Background:
    Given 已在測試目錄下初始化資料根目錄 "${TEST_DATA_ROOT}/TenderSearch/data/"
    And IClock.Now 回傳 "2026-05-08T09:00:00+08:00"
    And IDailySummaryRepository 已被注入，讀取真實檔案系統

  # ----------------------------------------------------------
  # Happy path
  # ----------------------------------------------------------
  Scenario: 開啟程式時預設顯示當月行事曆
    # 對應 Step Definition：When_啟動桌面程式 / Then_驗證MonthlyCalendarViewModel
    When 建立 ShellViewModel 並呼叫 LoadAsync()
    Then ShellViewModel.CalendarVm.Year 應為 2026
    And ShellViewModel.CalendarVm.Month 應為 5
    And ShellViewModel.CalendarVm.View.Days 中 Date 為 2026-05-08 的項目應被標示為今日（測試透過 ViewModel 屬性或 IsToday 判斷）

  Scenario: 行事曆每格顯示該日標案筆數
    Given 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-07/summary.json" 存在，TotalCount 為 42，LastRunStatus 為 Success
    And 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/summary.json" 存在，TotalCount 為 55，LastRunStatus 為 Success
    When 呼叫 IMonthlyCalendarService.LoadMonthAsync(2026, 5)
    Then 回傳的 MonthlyCalendarView.Days 中 Date 為 2026-05-07 的 Summary.TotalCount 應為 42
    And Days 中 Date 為 2026-05-08 的 Summary.TotalCount 應為 55

  Scenario: 沒有資料的日期視覺上明顯區分
    Given 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-03/summary.json" 不存在
    When 呼叫 IMonthlyCalendarService.LoadMonthAsync(2026, 5)
    Then Days 中 Date 為 2026-05-03 的 Summary 應為 null
    And MonthlyCalendarViewModel 對該日的可點擊狀態應為 false

  Scenario: 點擊有資料的日期進入該日資料查詢頁
    Given MonthlyCalendarView 已載入，Date 為 2026-05-07 的 Summary.TotalCount 為 42
    When 呼叫 ShellViewModel.NavigateToDayCommand.Execute(DateOnly(2026, 5, 7))
    Then ShellViewModel.CurrentDailyQueryVm 應不為 null
    And CurrentDailyQueryVm.Date 應為 DateOnly(2026, 5, 7)

  Scenario: 行事曆側邊摘要顯示月度統計與最近一次更新時間
    Given 2026 年 5 月所有日期的 summary.json 加總 TotalCount 為 1234
    And 全系統最近一次成功爬蟲完成於 2026-05-08T17:05:30+08:00（透過所有 summary.json 的 LastRunAt 取最大值且 LastRunStatus = Success）
    And 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/summary.json" 的 TotalCount 為 55
    When 呼叫 ShellViewModel.LoadAsync()
    Then SideSummaryViewModel.MonthlyTotalCount 應為 1234
    And SideSummaryViewModel.TodayCount 應為 55
    And SideSummaryViewModel.LastUpdatedAt 應為 "2026-05-08T17:05:30+08:00"

  # ----------------------------------------------------------
  # 月份切換
  # ----------------------------------------------------------
  Scenario Outline: 切換月份功能
    Given MonthlyCalendarViewModel 目前 Year = <起始年>，Month = <起始月>
    When 呼叫 <Command>.Execute(null)
    Then MonthlyCalendarViewModel.Year 應為 <目標年>
    And MonthlyCalendarViewModel.Month 應為 <目標月>

    Examples:
      | 起始年 | 起始月 | Command                | 目標年 | 目標月 |
      | 2026   | 5      | GoPreviousMonthCommand | 2026   | 4      |
      | 2026   | 5      | GoNextMonthCommand     | 2026   | 6      |
      | 2026   | 4      | GoToCurrentMonthCommand| 2026   | 5      |
      | 2026   | 12     | GoNextMonthCommand     | 2027   | 1      |
      | 2026   | 1      | GoPreviousMonthCommand | 2025   | 12     |

  # ----------------------------------------------------------
  # 失敗日警示
  # ----------------------------------------------------------
  Scenario: 排程失敗的日期顯示警示符號
    Given 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-06/summary.json" 存在，LastRunStatus 為 Failed
    When 呼叫 IMonthlyCalendarService.LoadMonthAsync(2026, 5)
    Then Days 中 Date 為 2026-05-06 的 Summary.LastRunStatus 應為 RunStatus.Failed
    And MonthlyCalendarViewModel 對該日的 IsFailed 屬性應為 true

  Scenario: 點擊失敗日期可查看錯誤摘要
    Given 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-06/summary.json" 存在，LastRunStatus 為 Failed，ErrorMessage 為 "政府電子採購網連線逾時"
    And IErrorSummaryDialog 已被 Mock
    When 呼叫 MonthlyCalendarViewModel.ShowFailedSummaryCommand.Execute(DateOnly(2026, 5, 6))
    Then IErrorSummaryDialog.ShowAsync 應被呼叫一次
    And 呼叫時 errorMessage 參數應為 "政府電子採購網連線逾時"

  # ----------------------------------------------------------
  # 邊界與錯誤情境
  # ----------------------------------------------------------
  Scenario: 行事曆載入時優先讀取每日 summary.json，不解析完整標案
    # 對應 Step Definition：用 spy 監控 ITenderRepository.LoadAsync 是否被呼叫
    Given 2026 年 5 月所有日期皆有 summary.json 與 tenders.json
    And ITenderRepository 被替換為 SpyTenderRepository（記錄 LoadAsync 呼叫次數）
    When 呼叫 IMonthlyCalendarService.LoadMonthAsync(2026, 5)
    Then IDailySummaryRepository.LoadAsync 應被呼叫至少一次
    And SpyTenderRepository.LoadAsync 的呼叫次數應為 0

  Scenario: 某日 summary.json 損毀，行事曆仍可顯示其他日期
    Given 檔案 "${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-04/summary.json" 內容為 "{ broken json"
    And 其他日期的 summary.json 皆正常
    When 呼叫 IMonthlyCalendarService.LoadMonthAsync(2026, 5)
    Then 不應拋出例外
    And Days 中 Date 為 2026-05-04 的 IsCorrupted 應為 true
    And 其他日期的 Summary.TotalCount 應正常顯示
    And errors.log 應含一行 Severity 為 "warning" 的解析失敗紀錄

  Scenario: 完全沒有任何資料的全新安裝狀態
    Given 資料根目錄 "${TEST_DATA_ROOT}/TenderSearch/data/" 為空，無任何月份資料夾
    When 呼叫 ShellViewModel.LoadAsync()
    Then MonthlyCalendarViewModel.Year 應為 2026，Month 應為 5
    And MonthlyCalendarView.Days 中所有 Summary 應為 null
    And SideSummaryViewModel.LastUpdatedAt 應為 null（UI 顯示為「尚未更新」）
