// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tender.AcceptanceTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class 月份行事曆首頁Feature : object, Xunit.IClassFixture<月份行事曆首頁Feature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en"), "Features", "月份行事曆首頁", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "monthly_calendar.feature"
#line hidden
        
        public 月份行事曆首頁Feature(月份行事曆首頁Feature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 16
  #line hidden
#line 17
    await testRunner.GivenAsync("已在測試目錄下初始化資料根目錄 \"${TEST_DATA_ROOT}/TenderSearch/data/\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
    await testRunner.AndAsync("IClock.Now 回傳 \"2026-05-08T09:00:00+08:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.AndAsync("IDailySummaryRepository 已被注入，讀取真實檔案系統", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="開啟程式時預設顯示當月行事曆")]
        [Xunit.TraitAttribute("FeatureTitle", "月份行事曆首頁")]
        [Xunit.TraitAttribute("Description", "開啟程式時預設顯示當月行事曆")]
        public async System.Threading.Tasks.Task 開啟程式時預設顯示當月行事曆()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("開啟程式時預設顯示當月行事曆", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 26
    await testRunner.WhenAsync("建立 ShellViewModel 並呼叫 LoadAsync()", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
    await testRunner.ThenAsync("ShellViewModel.CalendarVm.Year 應為 2026", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 28
    await testRunner.AndAsync("ShellViewModel.CalendarVm.Month 應為 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
    await testRunner.AndAsync(("ShellViewModel.CalendarVm.View.Days 中 Date 為 2026-05-08 的項目應被標示為今日（測試透過 ViewModel" +
                        " 屬性或 IsToday 判斷）"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="行事曆每格顯示該日標案筆數")]
        [Xunit.TraitAttribute("FeatureTitle", "月份行事曆首頁")]
        [Xunit.TraitAttribute("Description", "行事曆每格顯示該日標案筆數")]
        public async System.Threading.Tasks.Task 行事曆每格顯示該日標案筆數()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("行事曆每格顯示該日標案筆數", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 32
    await testRunner.GivenAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-07/summary.json\" 存在，Total" +
                        "Count 為 42，LastRunStatus 為 Success"), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 33
    await testRunner.AndAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/summary.json\" 存在，Total" +
                        "Count 為 55，LastRunStatus 為 Success"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
    await testRunner.WhenAsync("呼叫 IMonthlyCalendarService.LoadMonthAsync(2026, 5)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
    await testRunner.ThenAsync("回傳的 MonthlyCalendarView.Days 中 Date 為 2026-05-07 的 Summary.TotalCount 應為 42", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 36
    await testRunner.AndAsync("Days 中 Date 為 2026-05-08 的 Summary.TotalCount 應為 55", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="沒有資料的日期視覺上明顯區分")]
        [Xunit.TraitAttribute("FeatureTitle", "月份行事曆首頁")]
        [Xunit.TraitAttribute("Description", "沒有資料的日期視覺上明顯區分")]
        public async System.Threading.Tasks.Task 沒有資料的日期視覺上明顯區分()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("沒有資料的日期視覺上明顯區分", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 38
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 39
    await testRunner.GivenAsync("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-03/summary.json\" 不存在", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
    await testRunner.WhenAsync("呼叫 IMonthlyCalendarService.LoadMonthAsync(2026, 5)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
    await testRunner.ThenAsync("Days 中 Date 為 2026-05-03 的 Summary 應為 null", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
    await testRunner.AndAsync("MonthlyCalendarViewModel 對該日的可點擊狀態應為 false", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="點擊有資料的日期進入該日資料查詢頁")]
        [Xunit.TraitAttribute("FeatureTitle", "月份行事曆首頁")]
        [Xunit.TraitAttribute("Description", "點擊有資料的日期進入該日資料查詢頁")]
        public async System.Threading.Tasks.Task 點擊有資料的日期進入該日資料查詢頁()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("點擊有資料的日期進入該日資料查詢頁", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 45
    await testRunner.GivenAsync("MonthlyCalendarView 已載入，Date 為 2026-05-07 的 Summary.TotalCount 為 42", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 46
    await testRunner.WhenAsync("呼叫 ShellViewModel.NavigateToDayCommand.Execute(DateOnly(2026, 5, 7))", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
    await testRunner.ThenAsync("ShellViewModel.CurrentDailyQueryVm 應不為 null", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 48
    await testRunner.AndAsync("CurrentDailyQueryVm.Date 應為 DateOnly(2026, 5, 7)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="行事曆側邊摘要顯示月度統計與最近一次更新時間")]
        [Xunit.TraitAttribute("FeatureTitle", "月份行事曆首頁")]
        [Xunit.TraitAttribute("Description", "行事曆側邊摘要顯示月度統計與最近一次更新時間")]
        public async System.Threading.Tasks.Task 行事曆側邊摘要顯示月度統計與最近一次更新時間()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("行事曆側邊摘要顯示月度統計與最近一次更新時間", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 50
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 51
    await testRunner.GivenAsync("2026 年 5 月所有日期的 summary.json 加總 TotalCount 為 1234", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 52
    await testRunner.AndAsync(("全系統最近一次成功爬蟲完成於 2026-05-08T17:05:30+08:00（透過所有 summary.json 的 LastRunAt 取最大值且 Last" +
                        "RunStatus = Success）"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
    await testRunner.AndAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-08/summary.json\" 的 TotalC" +
                        "ount 為 55"), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
    await testRunner.WhenAsync("呼叫 ShellViewModel.LoadAsync()", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
    await testRunner.ThenAsync("SideSummaryViewModel.MonthlyTotalCount 應為 1234", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 56
    await testRunner.AndAsync("SideSummaryViewModel.TodayCount 應為 55", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
    await testRunner.AndAsync("SideSummaryViewModel.LastUpdatedAt 應為 \"2026-05-08T17:05:30+08:00\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="切換月份功能")]
        [Xunit.TraitAttribute("FeatureTitle", "月份行事曆首頁")]
        [Xunit.TraitAttribute("Description", "切換月份功能")]
        [Xunit.InlineDataAttribute("2026", "5", "GoPreviousMonthCommand", "2026", "4", new string[0])]
        [Xunit.InlineDataAttribute("2026", "5", "GoNextMonthCommand", "2026", "6", new string[0])]
        [Xunit.InlineDataAttribute("2026", "4", "GoToCurrentMonthCommand", "2026", "5", new string[0])]
        [Xunit.InlineDataAttribute("2026", "12", "GoNextMonthCommand", "2027", "1", new string[0])]
        [Xunit.InlineDataAttribute("2026", "1", "GoPreviousMonthCommand", "2025", "12", new string[0])]
        public async System.Threading.Tasks.Task 切換月份功能(string 起始年, string 起始月, string command, string 目標年, string 目標月, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("起始年", 起始年);
            argumentsOfScenario.Add("起始月", 起始月);
            argumentsOfScenario.Add("Command", command);
            argumentsOfScenario.Add("目標年", 目標年);
            argumentsOfScenario.Add("目標月", 目標月);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("切換月份功能", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 62
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 63
    await testRunner.GivenAsync(string.Format("MonthlyCalendarViewModel 目前 Year = {0}，Month = {1}", 起始年, 起始月), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 64
    await testRunner.WhenAsync(string.Format("呼叫 {0}.Execute(null)", command), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
    await testRunner.ThenAsync(string.Format("MonthlyCalendarViewModel.Year 應為 {0}", 目標年), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 66
    await testRunner.AndAsync(string.Format("MonthlyCalendarViewModel.Month 應為 {0}", 目標月), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="排程失敗的日期顯示警示符號")]
        [Xunit.TraitAttribute("FeatureTitle", "月份行事曆首頁")]
        [Xunit.TraitAttribute("Description", "排程失敗的日期顯示警示符號")]
        public async System.Threading.Tasks.Task 排程失敗的日期顯示警示符號()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("排程失敗的日期顯示警示符號", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 79
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 80
    await testRunner.GivenAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-06/summary.json\" 存在，LastR" +
                        "unStatus 為 Failed"), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 81
    await testRunner.WhenAsync("呼叫 IMonthlyCalendarService.LoadMonthAsync(2026, 5)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 82
    await testRunner.ThenAsync("Days 中 Date 為 2026-05-06 的 Summary.LastRunStatus 應為 RunStatus.Failed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 83
    await testRunner.AndAsync("MonthlyCalendarViewModel 對該日的 IsFailed 屬性應為 true", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="點擊失敗日期可查看錯誤摘要")]
        [Xunit.TraitAttribute("FeatureTitle", "月份行事曆首頁")]
        [Xunit.TraitAttribute("Description", "點擊失敗日期可查看錯誤摘要")]
        public async System.Threading.Tasks.Task 點擊失敗日期可查看錯誤摘要()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("點擊失敗日期可查看錯誤摘要", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 85
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 86
    await testRunner.GivenAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-06/summary.json\" 存在，LastR" +
                        "unStatus 為 Failed，ErrorMessage 為 \"政府電子採購網連線逾時\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 87
    await testRunner.AndAsync("IErrorSummaryDialog 已被 Mock", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 88
    await testRunner.WhenAsync(("呼叫 MonthlyCalendarViewModel.ShowFailedSummaryCommand.Execute(DateOnly(2026, 5, 6)" +
                        ")"), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
    await testRunner.ThenAsync("IErrorSummaryDialog.ShowAsync 應被呼叫一次", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 90
    await testRunner.AndAsync("呼叫時 errorMessage 參數應為 \"政府電子採購網連線逾時\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="行事曆載入時優先讀取每日 summary.json，不解析完整標案")]
        [Xunit.TraitAttribute("FeatureTitle", "月份行事曆首頁")]
        [Xunit.TraitAttribute("Description", "行事曆載入時優先讀取每日 summary.json，不解析完整標案")]
        public async System.Threading.Tasks.Task 行事曆載入時優先讀取每日Summary_Json不解析完整標案()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("行事曆載入時優先讀取每日 summary.json，不解析完整標案", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 95
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 97
    await testRunner.GivenAsync("2026 年 5 月所有日期皆有 summary.json 與 tenders.json", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 98
    await testRunner.AndAsync("ITenderRepository 被替換為 SpyTenderRepository（記錄 LoadAsync 呼叫次數）", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 99
    await testRunner.WhenAsync("呼叫 IMonthlyCalendarService.LoadMonthAsync(2026, 5)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 100
    await testRunner.ThenAsync("IDailySummaryRepository.LoadAsync 應被呼叫至少一次", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 101
    await testRunner.AndAsync("SpyTenderRepository.LoadAsync 的呼叫次數應為 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="某日 summary.json 損毀，行事曆仍可顯示其他日期")]
        [Xunit.TraitAttribute("FeatureTitle", "月份行事曆首頁")]
        [Xunit.TraitAttribute("Description", "某日 summary.json 損毀，行事曆仍可顯示其他日期")]
        public async System.Threading.Tasks.Task 某日Summary_Json損毀行事曆仍可顯示其他日期()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("某日 summary.json 損毀，行事曆仍可顯示其他日期", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 103
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 104
    await testRunner.GivenAsync(("檔案 \"${TEST_DATA_ROOT}/TenderSearch/data/2026-05/2026-05-04/summary.json\" 內容為 \"{ b" +
                        "roken json\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 105
    await testRunner.AndAsync("其他日期的 summary.json 皆正常", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
    await testRunner.WhenAsync("呼叫 IMonthlyCalendarService.LoadMonthAsync(2026, 5)", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 107
    await testRunner.ThenAsync("不應拋出例外", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 108
    await testRunner.AndAsync("Days 中 Date 為 2026-05-04 的 IsCorrupted 應為 true", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
    await testRunner.AndAsync("其他日期的 Summary.TotalCount 應正常顯示", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 110
    await testRunner.AndAsync("errors.log 應含一行 Severity 為 \"warning\" 的解析失敗紀錄", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="完全沒有任何資料的全新安裝狀態")]
        [Xunit.TraitAttribute("FeatureTitle", "月份行事曆首頁")]
        [Xunit.TraitAttribute("Description", "完全沒有任何資料的全新安裝狀態")]
        public async System.Threading.Tasks.Task 完全沒有任何資料的全新安裝狀態()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("完全沒有任何資料的全新安裝狀態", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 112
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
  await this.FeatureBackgroundAsync();
#line hidden
#line 113
    await testRunner.GivenAsync("資料根目錄 \"${TEST_DATA_ROOT}/TenderSearch/data/\" 為空，無任何月份資料夾", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 114
    await testRunner.WhenAsync("呼叫 ShellViewModel.LoadAsync()", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 115
    await testRunner.ThenAsync("MonthlyCalendarViewModel.Year 應為 2026，Month 應為 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 116
    await testRunner.AndAsync("MonthlyCalendarView.Days 中所有 Summary 應為 null", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 117
    await testRunner.AndAsync("SideSummaryViewModel.LastUpdatedAt 應為 null（UI 顯示為「尚未更新」）", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await 月份行事曆首頁Feature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await 月份行事曆首頁Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
