// Auto-generated by sa-expert
// Feature: 更新紀錄與錯誤日誌
// Source: sa/engineer_features/crawl_logging.feature
// Module type: Storage + Crawler + Desktop（CrawlRunLog / ErrorLog）
// BDD Framework: Reqnroll

using System;
using System.Threading.Tasks;
using Reqnroll;

namespace Tender.AcceptanceTests.Steps;

[Binding]
public sealed class CrawlLoggingSteps
{
    private readonly ScenarioContext _scenarioContext;

    public CrawlLoggingSteps(ScenarioContext scenarioContext)
    {
        _scenarioContext = scenarioContext;
    }

    // -------------------------------------------------------------
    // Given
    // -------------------------------------------------------------

    [Given(@"ICrawler Mock 回傳 (\d+) 筆有效標案")]
    public void Given_CrawlerReturnsValidItems(int count)
    {
        throw new NotImplementedException("TODO: 同 DailyCrawlSteps，但保證所有 TenderItem 內容皆有效（不觸發 ParseException）。");
    }

    [Given(@"檔案 ""(.*)"" 已含 (\d+) 筆 Status = Success 的 Run，RunId 為 ""(.*)""")]
    public void Given_CrawlRunsFileExistsWithRun(string filePath, int count, string runId)
    {
        throw new NotImplementedException(
            "TODO: 寫入 CrawlRunLog JSON，含 count 筆 CrawlRun，第一筆 RunId = runId、Status = Success。");
    }

    [Given(@"既有 tenders\.json 含 SourcePk ""(.*)""~""(.*)""")]
    public void Given_TendersFileExistsWithPkRange(string fromPk, string toPk)
    {
        throw new NotImplementedException(
            "TODO: 寫入 tenders.json 含 SourcePk 從 fromPk 到 toPk 的 TenderItem 集合。");
    }

    [Given(@"預期 ITenderRepository\.MergeDailySnapshotAsync 回傳 MergeResult \{ Inserted = (\d+), Updated = (\d+), Skipped = (\d+) \}")]
    public void Given_ExpectedMergeResult(int inserted, int updated, int skipped)
    {
        throw new NotImplementedException(
            "TODO: 此為對 ICrawlerOrchestrator 流程的期望說明。實作時可在 ScenarioContext 記錄期望值，後續 Then 步驟驗證 ICrawlerOrchestrator 寫入的 CrawlRun 與 summary 是否符合。");
    }

    [Given(@"ICrawler Mock 在所有重試（maxRetries=3）皆拋 CrawlNetworkException\(message = ""(.*)""\)")]
    public void Given_CrawlerThrowsWithMessage(string message)
    {
        throw new NotImplementedException("TODO: Mock<ICrawler>.Setup(...).ThrowsAsync(new CrawlNetworkException(message))。");
    }

    [Given(@"ICrawler Mock 回傳 (\d+) 個 FetchedPage，第 (\d+) 頁的 Html 會觸發 ITenderParser\.Parse 拋 ParseException")]
    public void Given_CrawlerReturnsPagesWithFailingPage(int totalPages, int failingPage)
    {
        throw new NotImplementedException(
            "TODO: ICrawler 回傳 totalPages 個 FetchedPage；ITenderParser 對失敗頁的 Html 拋 ParseException(failingPage, ...)。");
    }

    [Given(@"IAtomicJsonWriter 模擬磁碟空間不足，寫 \.tmp 即拋 IOException\(""(.*)""\)")]
    public void Given_DiskFullIOException(string message)
    {
        throw new NotImplementedException("TODO: 註冊測試專用 writer，寫 .tmp 拋 IOException(message)。");
    }

    [Given(@"全系統最近一次成功 Run 的 LastRunAt 為 ""(.*)""（依所有 summary\.json 取 LastRunStatus = Success 中的最大 LastRunAt）")]
    public void Given_GlobalLatestSuccessRunAt(string isoDateTime)
    {
        throw new NotImplementedException("TODO: 在資料目錄中為某一日寫入 summary.json，LastRunStatus = Success、LastRunAt = isoDateTime。");
    }

    [Given(@"檔案 ""(.*)"" 存在，LastRunStatus = (\w+)，LastRunAt = ""(.*)""")]
    public void Given_SummaryFileWithStatusAndTime(string filePath, string status, string isoDateTime)
    {
        throw new NotImplementedException("TODO: 寫入 summary.json，LastRunStatus + LastRunAt 設為對應值。");
    }

    [Given(@"該日為近期最近一次失敗（其他較晚日期的 LastRunStatus 皆為 Success）")]
    public void Given_LatestFailureDay()
    {
        throw new NotImplementedException(
            "TODO: 為更晚的日期寫入 LastRunStatus = Success 的 summary.json，確保此日為最近一次 Failed。");
    }

    [Given(@"檔案 ""(.*)"" 存在，LastRunStatus = (\w+)，ErrorMessage = ""(.*)""")]
    public void Given_SummaryFileWithStatusAndError(string filePath, string status, string errorMessage)
    {
        throw new NotImplementedException("TODO: 寫入 summary.json 含 ErrorMessage。");
    }

    [Given(@"檔案 ""(.*)"" 存在")]
    public void Given_FileExists(string filePath)
    {
        throw new NotImplementedException("TODO: ResolvePath，建立檔案（內容可為空字串）。");
    }

    [Given(@"IErrorSummaryDialog 已被 Mock")]
    public void Given_ErrorSummaryDialogMocked()
    {
        throw new NotImplementedException("TODO: 確認 ServiceProvider 中的 IErrorSummaryDialog 為 Mock 實例。");
    }

    [Given(@"目錄 ""(.*)"" 不存在")]
    public void Given_DirNotExists(string pathTemplate)
    {
        throw new NotImplementedException("TODO: ResolvePath，遞迴刪除該目錄。");
    }

    [Given(@"檔案 ""(.*)"" 已存在，內容為 ""(.*)""")]
    public void Given_FileExistsWithContent(string pathTemplate, string content)
    {
        throw new NotImplementedException(
            "TODO: ResolvePath；File.WriteAllText(path, content)。注意 content 中的 \\n 應正確反逸成換行。");
    }

    // -------------------------------------------------------------
    // When
    // -------------------------------------------------------------

    [When(@"執行 ICrawlerOrchestrator\.RunAsync\(new CrawlerArgs \{ Mode = (\w+), TargetDate = (\d{4}-\d{2}-\d{2}) \}\)")]
    public async Task When_RunOrchestrator(string mode, string targetDate)
    {
        throw new NotImplementedException("TODO: 同 DailyCrawlSteps.When_RunCrawlerOrchestrator。");
    }

    [When(@"呼叫 ShellViewModel\.LoadAsync\(\)")]
    public async Task When_ShellLoad()
    {
        throw new NotImplementedException("TODO: 同 MonthlyCalendarSteps.When_CallShellViewModelLoad。");
    }

    [When(@"呼叫 MonthlyCalendarViewModel\.ShowFailedSummaryCommand\.Execute\(DateOnly\((\d+), (\d+), (\d+)\)\)")]
    public async Task When_ShowFailedSummary(int year, int month, int day)
    {
        throw new NotImplementedException("TODO: 同 MonthlyCalendarSteps 對應 When。");
    }

    [When(@"呼叫 IErrorLogWriter\.AppendAsync\(DateOnly\((\d+), (\d+), (\d+)\), 任意 ErrorLogEntry\)")]
    public async Task When_AppendErrorLog(int year, int month, int day)
    {
        throw new NotImplementedException(
            "TODO: 從 DI 取 IErrorLogWriter；建立任意 ErrorLogEntry（Severity=warning, Source=test, Message=\"test\"）；" +
            "await AppendAsync(new DateOnly(...), entry)。");
    }

    // -------------------------------------------------------------
    // Then
    // -------------------------------------------------------------

    [Then(@"反序列化後 CrawlRunLog\.Date 應為 ""(.*)""")]
    public void Then_CrawlRunLogDateEquals(string expected)
    {
        throw new NotImplementedException("TODO: 反序列化 crawl-runs.json，斷言 Date == expected。");
    }

    [Then(@"CrawlRunLog\.Runs 應有 (\d+) 筆")]
    public void Then_CrawlRunLogRunsCount(int count)
    {
        throw new NotImplementedException("TODO: 反序列化後斷言 Runs.Count == count。");
    }

    [Then(@"Runs\[(\d+)\] 的欄位應齊全：(.+)")]
    public void Then_RunFieldsPresent(int index, string fieldsCsv)
    {
        throw new NotImplementedException(
            "TODO: 取 Runs[index]，遍歷 fieldsCsv 列出的欄位名稱，用反射或手動斷言每個欄位非 null（ErrorMessage 可為 null）。");
    }

    [Then(@"Runs\[(\d+)\]\.Status 應為 RunStatus\.(\w+)")]
    public void Then_RunStatus(int index, string status)
    {
        throw new NotImplementedException("TODO: 斷言 Runs[index].Status 等於對應 RunStatus enum。");
    }

    [Then(@"Runs\[(\d+)\]\.ErrorMessage 應為 null")]
    public void Then_RunErrorMessageNull(int index)
    {
        throw new NotImplementedException("TODO: 斷言 Runs[index].ErrorMessage == null。");
    }

    [Then(@"crawl-runs\.json 反序列化後 Runs\.Count 應為 (\d+)")]
    public void Then_RunsCountAfterDeser(int count)
    {
        throw new NotImplementedException("TODO: 同 Then_CrawlRunLogRunsCount。");
    }

    [Then(@"Runs\[(\d+)\]\.RunId 應不等於 Runs\[(\d+)\]\.RunId")]
    public void Then_RunIdsDiffer(int a, int b)
    {
        throw new NotImplementedException("TODO: 斷言 Runs[a].RunId != Runs[b].RunId。");
    }

    [Then(@"Runs\[(\d+)\]\.StartedAt 應晚於 Runs\[(\d+)\]\.StartedAt（時間順序遞增）")]
    public void Then_RunStartedAtOrder(int later, int earlier)
    {
        throw new NotImplementedException("TODO: 斷言 Runs[later].StartedAt > Runs[earlier].StartedAt。");
    }

    [Then(@"Runs\[(\d+)\]\.TriggerSource 應為 (\w+)")]
    public void Then_RunTriggerSource(int index, string trigger)
    {
        throw new NotImplementedException("TODO: 斷言 Runs[index].TriggerSource 等於對應 enum。");
    }

    [Then(@"crawl-runs\.json 最新一筆 Run 應記錄 InsertedCount = (\d+)、UpdatedCount = (\d+)、SkippedCount = (\d+)")]
    public void Then_LastRunCounts(int inserted, int updated, int skipped)
    {
        throw new NotImplementedException("TODO: 取 Runs.Last()，斷言計數欄位。");
    }

    [Then(@"summary\.json 的 InsertedCount、UpdatedCount、SkippedCount 應與最新 Run 相同")]
    public void Then_SummaryCountsMatchLastRun()
    {
        throw new NotImplementedException(
            "TODO: 反序列化 summary.json 與 crawl-runs.json，比對三項計數相同。");
    }

    [Then(@"summary\.json 的 TotalCount 應為合併後 tenders\.json 的 Items\.Count")]
    public void Then_SummaryTotalCountMatchesTenders()
    {
        throw new NotImplementedException(
            "TODO: 反序列化 summary.json 與 tenders.json，斷言 summary.TotalCount == tenders.Items.Count。");
    }

    [Then(@"crawl-runs\.json 最新一筆 Run\.Status 應為 RunStatus\.(\w+)")]
    public void Then_LastRunStatus(string status)
    {
        throw new NotImplementedException("TODO: 取 Runs.Last().Status，斷言。");
    }

    [Then(@"Run\.ErrorMessage 應包含子字串 ""(.*)""")]
    public void Then_RunErrorMessageContains(string substring)
    {
        throw new NotImplementedException("TODO: 取 Runs.Last().ErrorMessage，斷言 .Contains(substring)。");
    }

    [Then(@"errors\.log 應至少含一行 ErrorLogEntry，Severity = ""(.*)""，Source = ""(.*)""，Message 包含 ""(.*)""")]
    public void Then_ErrorsLogContainsEntryWithMessage(string severity, string source, string messagePart)
    {
        throw new NotImplementedException(
            "TODO: 解析 errors.log（每行一個 JSON），找符合 Severity + Source 且 Message.Contains(messagePart) 的條目。");
    }

    [Then(@"errors\.log 應含一行 ErrorLogEntry，Severity = ""(.*)""，Page = (\d+)，Message 包含 ""(.*)""")]
    public void Then_ErrorsLogContainsPageEntry(string severity, int page, string messagePart)
    {
        throw new NotImplementedException("TODO: 同上但限定 Page。");
    }

    [Then(@"summary\.json 的 ErrorMessage 應包含子字串 ""(.*)""")]
    public void Then_SummaryErrorMessageContains(string substring)
    {
        throw new NotImplementedException("TODO: 反序列化 summary.json，斷言 ErrorMessage.Contains(substring)。");
    }

    [Then(@"errors\.log 應含 Severity = ""(.*)"" 且 Message 包含 ""(.*)"" 的 ErrorLogEntry")]
    public void Then_ErrorsLogSeverityMessage(string severity, string messagePart)
    {
        throw new NotImplementedException("TODO: 解析 errors.log 找符合條件的條目。");
    }

    [Then(@"summary\.json 寫入若可成功，LastRunStatus 應為 RunStatus\.(\w+)")]
    public void Then_SummaryFailedIfWritable(string status)
    {
        throw new NotImplementedException(
            "TODO: 若 summary.json 存在 → 反序列化驗證 LastRunStatus；不存在則此 Then 通過。");
    }

    [Then(@"SideSummaryViewModel\.LastUpdatedAt 應為 ""(.*)""")]
    public void Then_LastUpdatedAt(string isoDateTime)
    {
        throw new NotImplementedException("TODO: 同 MonthlyCalendarSteps.Then_LastUpdatedAt。");
    }

    [Then(@"SideSummaryViewModel\.LastFailureDate 應為 DateOnly\((\d+), (\d+), (\d+)\)")]
    public void Then_LastFailureDate(int year, int month, int day)
    {
        throw new NotImplementedException("TODO: 取 SideSummaryVm.LastFailureDate，斷言等於 new DateOnly(...)。");
    }

    [Then(@"IErrorSummaryDialog\.ShowAsync 應被呼叫")]
    public void Then_ErrorSummaryDialogShown()
    {
        throw new NotImplementedException("TODO: Mock<IErrorSummaryDialog>.Verify(..., Times.AtLeastOnce)。");
    }

    [Then(@"呼叫的 errorMessage 參數應為 ""(.*)""")]
    public void Then_DialogErrorMessageArg(string expected)
    {
        throw new NotImplementedException("TODO: 用 Moq 的 Capture.In 或 It.Is 驗證參數。");
    }

    [Then(@"呼叫的 errorsLogPath 參數應為 ""(.*)""")]
    public void Then_DialogErrorsLogPathArg(string pathTemplate)
    {
        throw new NotImplementedException("TODO: ResolvePath 後 Verify 該參數。");
    }

    [Then(@"目錄 ""(.*)"" 應存在")]
    public void Then_DirShouldExist(string pathTemplate)
    {
        throw new NotImplementedException("TODO: ResolvePath，Directory.Exists 應為 true。");
    }

    [Then(@"檔案 tenders\.json、summary\.json、crawl-runs\.json 三者皆應存在於該目錄")]
    public void Then_ThreeJsonFilesExist()
    {
        throw new NotImplementedException(
            "TODO: 取 ScenarioContext 中的目標日期目錄，驗證 tenders.json、summary.json、crawl-runs.json 三檔存在。");
    }

    [Then(@"檔案 ""(.*)"" 內容應與寫入前完全相同")]
    public void Then_FileContentUnchanged(string pathTemplate)
    {
        throw new NotImplementedException(
            "TODO: 在 Given 階段記錄檔案 hash；此處重算比對。");
    }

    [Then(@"檔案 ""(.*)"" 應存在，含一行新 ErrorLogEntry")]
    public void Then_ErrorsLogContainsNewEntry(string pathTemplate)
    {
        throw new NotImplementedException(
            "TODO: ResolvePath，File.Exists；逐行解析為 ErrorLogEntry，斷言至少有一行為合法 JSON。");
    }
}
