// Auto-generated by sa-expert
// Feature: 匯出 Excel
// Source: sa/engineer_features/export_excel.feature
// Module type: WPF Desktop - Excel Export (ClosedXML)
// BDD Framework: Reqnroll

using System;
using System.Threading.Tasks;
using Reqnroll;

namespace Tender.AcceptanceTests.Steps;

[Binding]
public sealed class ExportExcelSteps
{
    private readonly ScenarioContext _scenarioContext;

    public ExportExcelSteps(ScenarioContext scenarioContext)
    {
        _scenarioContext = scenarioContext;
    }

    // -------------------------------------------------------------
    // Given
    // -------------------------------------------------------------

    [Given(@"ISaveFileDialogService 已被 Mock")]
    public void Given_SaveFileDialogServiceMocked()
    {
        throw new NotImplementedException("TODO: 確認 ServiceProvider 中的 ISaveFileDialogService 為 Mock 實例。");
    }

    [Given(@"DailyQueryViewModel\.FilteredItems\.Count 為 (\d+)（未套用任何篩選）")]
    public void Given_FilteredItemsCountUnfiltered(int count)
    {
        throw new NotImplementedException(
            "TODO: 確認 DailyQueryViewModel.FilteredItems.Count == count，且 Criteria 為預設值（KeywordQuery=null、ActiveKeywordButtons=空）。");
    }

    [Given(@"DailyQueryViewModel\.FilteredItems\.Count 為 (\d+)")]
    public void Given_FilteredItemsCount(int count)
    {
        throw new NotImplementedException("TODO: 確認 FilteredItems.Count == count，必要時透過 Criteria 套用篩選達成。");
    }

    [Given(@"ISaveFileDialogService\.ShowSaveAsXlsx 回傳 ""(.*)""")]
    public void Given_SaveDialogReturnsPath(string pathTemplate)
    {
        throw new NotImplementedException(
            "TODO: ResolvePath（${TEST_OUTPUT}）→ Mock<ISaveFileDialogService>.Setup(x => x.ShowSaveAsXlsx(It.IsAny<string>())).Returns(resolvedPath)。");
    }

    [Given(@"ISaveFileDialogService\.ShowSaveAsXlsx 回傳 null（使用者取消）")]
    public void Given_SaveDialogReturnsNull()
    {
        throw new NotImplementedException("TODO: Mock<ISaveFileDialogService>.Setup(...).Returns((string?)null)。");
    }

    [Given(@"已呼叫 ToggleKeywordButtonCommand\.Execute\(""(.*)""\)，FilteredItems\.Count 為 (\d+)")]
    public void Given_ToggleKeywordButtonAndCount(string keyword, int expectedCount)
    {
        throw new NotImplementedException(
            "TODO: 呼叫 ToggleKeywordButtonCommand.Execute(keyword)，斷言 FilteredItems.Count == expectedCount。");
    }

    [Given(@"FilteredItems\[(\d+)\]\.AgencyName 為 ""(.*)""")]
    public void Given_FilteredItemAgencyName(int index, string agencyName)
    {
        throw new NotImplementedException("TODO: 確保 FilteredItems[index].AgencyName == agencyName，必要時調整測試資料。");
    }

    [Given(@"FilteredItems\[(\d+)\]\.TenderName 為 ""(.*)""")]
    public void Given_FilteredItemTenderName(int index, string tenderName)
    {
        throw new NotImplementedException("TODO: 同上但作用於 TenderName。");
    }

    [Given(@"FilteredItems\[(\d+)\]\.DetailUrl 為 ""(.*)""")]
    public void Given_FilteredItemDetailUrl(int index, string url)
    {
        throw new NotImplementedException("TODO: 同上但作用於 DetailUrl。");
    }

    [Given(@"FilteredItems 中某筆 TenderName 為 ""(.*)""")]
    public void Given_SomeItemTenderName(string tenderName)
    {
        throw new NotImplementedException("TODO: 在 FilteredItems 中保證至少一筆的 TenderName 為 tenderName。");
    }

    [Given(@"檔案 ""(.*)"" 已被另一個程序以獨佔模式開啟")]
    public void Given_FileLockedByOtherProcess(string pathTemplate)
    {
        throw new NotImplementedException(
            "TODO: ResolvePath，用 FileStream(path, FileMode.Create, FileAccess.Write, FileShare.None) 開啟並存入 ScenarioContext，待 AfterScenario 關閉。");
    }

    // -------------------------------------------------------------
    // When
    // -------------------------------------------------------------

    [When(@"呼叫 DailyQueryViewModel\.ExportCommand\.Execute\(null\)")]
    public async Task When_Export()
    {
        throw new NotImplementedException("TODO: await DailyQueryViewModel.ExportCommand.ExecuteAsync(null)。");
    }

    [When(@"呼叫 ExportCommand\.Execute\(null\)")]
    public async Task When_ExportShort()
    {
        throw new NotImplementedException("TODO: 同上。");
    }

    [When(@"呼叫 ExportCommand\.Execute\(null\) 並完成匯出")]
    public async Task When_ExportAndComplete()
    {
        throw new NotImplementedException("TODO: await ExportCommand 執行；確保檔案實際寫入完成。");
    }

    // -------------------------------------------------------------
    // Then
    // -------------------------------------------------------------

    [Then(@"檔案 ""(.*)"" 應存在")]
    public void Then_FileExists(string pathTemplate)
    {
        throw new NotImplementedException("TODO: ResolvePath → File.Exists 應為 true。");
    }

    [Then(@"用 ClosedXML 開啟該檔案，第一張工作表的資料列數（不含表頭）應為 (\d+)")]
    public void Then_DataRowCount(int expected)
    {
        throw new NotImplementedException(
            "TODO: 用 new XLWorkbook(path) 開啟，取 Worksheet(1)，計算 RangeUsed().RowCount() - 1（扣表頭），斷言。");
    }

    [Then(@"第一張工作表的表頭（第 1 列）應至少包含：(.+)")]
    public void Then_HeaderContains(string columnsCsv)
    {
        throw new NotImplementedException(
            "TODO: 解析 columnsCsv，取 Worksheet(1).Row(1).CellsUsed() 取得各欄表頭文字，斷言全部 expected 欄位都存在。");
    }

    [Then(@"「標案名稱」或「檢視連結」欄的儲存格應具備可點擊超連結（IXLCell\.HasHyperlink == true）")]
    public void Then_TenderNameOrViewColumnHasHyperlink()
    {
        throw new NotImplementedException(
            "TODO: 找 TenderName 與 ViewLink 對應的欄位 index，斷言該欄資料列至少其中一欄 cell.HasHyperlink == true。");
    }

    [Then(@"匯出檔案的資料列數（不含表頭）應為 (\d+)")]
    public void Then_ExportedRowCount(int expected)
    {
        throw new NotImplementedException("TODO: 同 Then_DataRowCount。");
    }

    [Then(@"每筆「標案名稱」或「檢視連結」欄的超連結應指向對應 TenderItem\.DetailUrl")]
    public void Then_HyperlinkPointsToDetailUrl()
    {
        throw new NotImplementedException(
            "TODO: 對每一筆資料列，取得 TenderName 與 ViewLink 欄位的 cell，斷言 cell.GetHyperlink().ExternalAddress 等於對應 TenderItem.DetailUrl。");
    }

    [Then(@"匯出檔案副檔名應為 \.xlsx")]
    public void Then_FileExtensionXlsx()
    {
        throw new NotImplementedException(
            "TODO: 從 ISaveFileDialogService Mock 接收到的 path，斷言 Path.GetExtension(path) == \".xlsx\"。");
    }

    [Then(@"表頭列應在第 (\d+) 列")]
    public void Then_HeaderRowAt(int rowNumber)
    {
        throw new NotImplementedException(
            "TODO: 斷言 Worksheet.Row(rowNumber) 含表頭文字，且 Worksheet.Row(rowNumber - 1) 不含資料。");
    }

    [Then(@"「預算金額」欄的儲存格資料型別應為 XLDataType\.Number")]
    public void Then_BudgetColumnIsNumber()
    {
        throw new NotImplementedException(
            "TODO: 取「預算金額」欄的 cell.DataType，斷言等於 XLDataType.Number。");
    }

    [Then(@"「公告日期」與「截止投標」欄的儲存格應為文字格式（保留民國年原文，例 ""(.*)""）")]
    public void Then_DateColumnsAreText(string sample)
    {
        throw new NotImplementedException(
            "TODO: 取對應欄第一筆，cell.DataType == XLDataType.Text，內容符合 \\d+/\\d{2}/\\d{2} 格式（如 sample）。");
    }

    [Then(@"匯出檔案應包含一欄表頭為「機關名稱：標案名稱」")]
    public void Then_ContainsCombinedColumn()
    {
        throw new NotImplementedException("TODO: 表頭列中應含 '機關名稱：標案名稱' 字串。");
    }

    [Then(@"該欄第一筆資料儲存格的文字應為 ""(.*)""")]
    public void Then_CombinedColumnFirstRow(string expected)
    {
        throw new NotImplementedException("TODO: 取該欄第一筆 cell.GetString()，斷言 == expected。");
    }

    [Then(@"該儲存格的 Hyperlink\.ExternalAddress 應為 ""(.*)""")]
    public void Then_CombinedColumnHyperlink(string expectedUrl)
    {
        throw new NotImplementedException("TODO: 取該儲存格 cell.GetHyperlink().ExternalAddress.ToString()，斷言 == expectedUrl。");
    }

    [Then(@"ISaveFileDialogService\.ShowSaveAsXlsx 不應被呼叫")]
    public void Then_SaveFileDialogNotCalled()
    {
        throw new NotImplementedException("TODO: Mock<ISaveFileDialogService>.Verify(..., Times.Never)。");
    }

    [Then(@"IExcelExporter\.ExportAsync 不應被呼叫")]
    public void Then_ExcelExporterNotCalled()
    {
        throw new NotImplementedException("TODO: Mock<IExcelExporter>.Verify(..., Times.Never)。");
    }

    [Then(@"DailyQueryViewModel\.LastUserMessage 應包含「(.*)」")]
    public void Then_LastUserMessageContains(string substring)
    {
        throw new NotImplementedException("TODO: 取 DailyQueryViewModel.LastUserMessage，斷言 .Contains(substring)。");
    }

    [Then(@"不應產生任何 \.xlsx 檔案")]
    public void Then_NoXlsxProduced()
    {
        throw new NotImplementedException("TODO: 列出 ${TEST_OUTPUT} 內所有 *.xlsx，斷言為空。");
    }

    [Then(@"用 ClosedXML 重新讀回該儲存格的字串應完全等於 ""(.*)""")]
    public void Then_CellStringEquals(string expected)
    {
        throw new NotImplementedException(
            "TODO: 重新開啟匯出檔，搜尋 TenderName 欄找含特殊字元的 cell，斷言 cell.GetString() == expected。");
    }

    [Then(@"errors\.log 應記錄該次 IOException")]
    public void Then_ErrorsLogContainsIOException()
    {
        throw new NotImplementedException("TODO: 解析 errors.log 找 IOException 條目（注意此處應寫入桌面端對應日的 errors.log）。");
    }

    [Then(@"DailyQueryViewModel 狀態應與匯出前相同")]
    public void Then_ViewModelStateUnchanged()
    {
        throw new NotImplementedException(
            "TODO: 在 When 之前 snapshot DailyQueryViewModel 重要屬性（FilteredItems、Criteria、SortKey），" +
            "When 之後比對應相同。");
    }
}
