// Auto-generated by sa-expert
// Feature: 安裝與排程任務建立
// Source: sa/engineer_features/installation.feature
// Module type: WiX MSI Installer + Custom Actions
// BDD Framework: Reqnroll

using System;
using System.Threading.Tasks;
using Reqnroll;

namespace Tender.AcceptanceTests.Steps;

[Binding]
public sealed class InstallationSteps
{
    private readonly ScenarioContext _scenarioContext;

    public InstallationSteps(ScenarioContext scenarioContext)
    {
        _scenarioContext = scenarioContext;
    }

    // -------------------------------------------------------------
    // Given
    // -------------------------------------------------------------

    [Given(@"測試環境變數 \$\{TEST_LOCAL_APP_DATA\} 指向臨時目錄取代 %LocalAppData%")]
    public void Given_TestLocalAppDataInitialized()
    {
        throw new NotImplementedException(
            "TODO: Path.Combine(Path.GetTempPath(), \"tender-install-tests\", Guid.NewGuid().ToString()) 建立臨時目錄；" +
            "存入 ScenarioContext[\"TestLocalAppData\"]；" +
            "把 IDataPaths 切換為以此 root 計算路徑的測試實作。");
    }

    [Given(@"測試使用 ITaskSchedulerAdapter 的 InMemory Mock 取代真實 Windows Task Scheduler")]
    public void Given_TaskSchedulerAdapterMocked()
    {
        throw new NotImplementedException(
            "TODO: 註冊 InMemoryTaskSchedulerAdapter 取代真實實作；該 adapter 應提供 GetTask、RegisterTask、RemoveTask 介面，" +
            "用 Dictionary<string, ScheduledTask> 模擬。");
    }

    [Given(@"\$\{TEST_LOCAL_APP_DATA\}/TenderSearch/ 目錄不存在")]
    public void Given_TenderSearchDirNotExists()
    {
        throw new NotImplementedException("TODO: 從 ScenarioContext 取 TestLocalAppData，刪除其下 TenderSearch 目錄（若存在）。");
    }

    [Given(@"ITaskSchedulerAdapter 中沒有名為 ""(.*)"" 的任務")]
    public void Given_NoTaskNamed(string taskName)
    {
        throw new NotImplementedException("TODO: InMemoryTaskSchedulerAdapter.RemoveTask(taskName)。");
    }

    [Given(@"ITaskSchedulerAdapter 已含名為 ""(.*)"" 的任務，ScheduledTime 為 ""(.*)""")]
    public void Given_TaskExists(string taskName, string scheduledTime)
    {
        throw new NotImplementedException(
            "TODO: 在 InMemoryTaskSchedulerAdapter 預先註冊一個 task，name = taskName，scheduledTime = scheduledTime。");
    }

    [Given(@"ITaskSchedulerAdapter 已含名為 ""(.*)"" 的任務")]
    public void Given_TaskExistsBasic(string taskName)
    {
        throw new NotImplementedException("TODO: 同上但僅含 name。");
    }

    [Given(@"目錄 ""(.*)"" 已存在，含 tenders\.json 與 summary\.json")]
    public void Given_DirExistsWithFiles(string pathTemplate)
    {
        throw new NotImplementedException(
            "TODO: ResolvePath（${TEST_LOCAL_APP_DATA}），Directory.CreateDirectory，並寫入 tenders.json 與 summary.json 的測試內容。");
    }

    [Given(@"目錄 ""(.*)"" 含使用者歷史資料")]
    public void Given_DirContainsHistoricalData(string pathTemplate)
    {
        throw new NotImplementedException("TODO: 同上但寫入多筆歷史檔案。");
    }

    [Given(@"已成功執行 EnsureDataRoot 與 CreateDailyTask")]
    public void Given_PreviouslySucceeded()
    {
        throw new NotImplementedException(
            "TODO: 直接呼叫 DataDirectoryActions.EnsureDataRoot() 與 TaskSchedulerActions.CreateDailyTask()，斷言成功。");
    }

    [Given(@"ITaskSchedulerAdapter Mock 設定為「在指定時間立即觸發 Action」")]
    public void Given_TaskTriggerImmediate()
    {
        throw new NotImplementedException(
            "TODO: 在 InMemoryTaskSchedulerAdapter 提供 SimulateTrigger(taskName) 方法，呼叫時直接執行對應 Action。");
    }

    [Given(@"IClock\.Now 設定為 ""(.*)""")]
    public void Given_ClockNow(string isoDateTime)
    {
        throw new NotImplementedException("TODO: FakeClock.Now = DateTimeOffset.Parse(isoDateTime)。");
    }

    [Given(@"ITaskSchedulerAdapter Mock 設定為「呼叫 RegisterTaskAsync 時拋 UnauthorizedAccessException」")]
    public void Given_TaskSchedulerThrowsUnauthorized()
    {
        throw new NotImplementedException(
            "TODO: Mock<ITaskSchedulerAdapter>.Setup(x => x.RegisterTaskAsync(...)).ThrowsAsync(new UnauthorizedAccessException())。");
    }

    [Given(@"\$\{TEST_LOCAL_APP_DATA\}/TenderSearch/ 路徑被測試環境設為無寫入權限")]
    public void Given_PathReadOnly()
    {
        throw new NotImplementedException(
            "TODO: 用 DirectoryInfo.SetAccessControl 或測試專用 IFileSystem mock 模擬無寫入權限。" +
            "Windows 上實作可能需額外注意；建議改用 IFileSystem 抽象，注入會拋 UnauthorizedAccessException 的 mock。");
    }

    [Given(@"已執行 EnsureDataRoot（資料目錄已建立）")]
    public void Given_EnsureDataRootDone()
    {
        throw new NotImplementedException("TODO: 直接呼叫 DataDirectoryActions.EnsureDataRoot()。");
    }

    // -------------------------------------------------------------
    // When
    // -------------------------------------------------------------

    [When(@"執行 DataDirectoryActions\.EnsureDataRoot\(\)")]
    public void When_EnsureDataRoot()
    {
        throw new NotImplementedException(
            "TODO: 從 DI 取 DataDirectoryActions（或直接 static call），呼叫 EnsureDataRoot；" +
            "ActionResult 與例外存入 ScenarioContext。");
    }

    [When(@"執行 TaskSchedulerActions\.CreateDailyTask\(\)")]
    public void When_CreateDailyTask()
    {
        throw new NotImplementedException("TODO: 同上呼叫 TaskSchedulerActions.CreateDailyTask。");
    }

    [When(@"執行 TaskSchedulerActions\.RemoveDailyTask\(\)")]
    public void When_RemoveDailyTask()
    {
        throw new NotImplementedException("TODO: 同上呼叫 TaskSchedulerActions.RemoveDailyTask。");
    }

    [When(@"再次執行 DataDirectoryActions\.EnsureDataRoot\(\)")]
    public void When_EnsureDataRootAgain()
    {
        throw new NotImplementedException("TODO: 第二次呼叫，驗證冪等性。");
    }

    [When(@"再次執行 TaskSchedulerActions\.CreateDailyTask\(\)")]
    public void When_CreateDailyTaskAgain()
    {
        throw new NotImplementedException("TODO: 第二次呼叫，驗證冪等性。");
    }

    [When(@"ITaskSchedulerAdapter 觸發 ""(.*)"" 對應的 Action")]
    public async Task When_SimulateTaskTrigger(string taskName)
    {
        throw new NotImplementedException("TODO: InMemoryTaskSchedulerAdapter.SimulateTrigger(taskName)。");
    }

    [When(@"使用者於安裝精靈點選「取消」")]
    public void When_UserCancelsInstaller()
    {
        throw new NotImplementedException(
            "TODO: 呼叫測試專用的 InstallerSimulator.Cancel()，觸發已執行 Custom Action 的 Rollback 對應方法。");
    }

    [When(@"執行 WiX 的 Uninstall 流程（移除捷徑與安裝目錄程式檔）")]
    public void When_RunUninstall()
    {
        throw new NotImplementedException(
            "TODO: 呼叫 InstallerSimulator.Uninstall()，模擬 WiX 移除程式檔；" +
            "捷徑與排程任務移除由 RemoveDailyTask 與 WiX File element 處理。");
    }

    // -------------------------------------------------------------
    // Then
    // -------------------------------------------------------------

    [Then(@"目錄 ""(.*)"" 應存在")]
    public void Then_DirExists(string pathTemplate)
    {
        throw new NotImplementedException("TODO: ResolvePath，Directory.Exists 應為 true。");
    }

    [Then(@"檔案 ""(.*)"" 應存在，且可被反序列化為 KeywordSet")]
    public void Then_KeywordsFileValid(string pathTemplate)
    {
        throw new NotImplementedException(
            "TODO: ResolvePath，File.Exists；用 System.Text.Json 反序列化為 KeywordSet 不應拋例外，且 Groups.Count > 0。");
    }

    [Then(@"ITaskSchedulerAdapter 應含名為 ""(.*)"" 的任務")]
    public void Then_TaskExists(string taskName)
    {
        throw new NotImplementedException("TODO: InMemoryTaskSchedulerAdapter.GetTask(taskName) 應不為 null。");
    }

    [Then(@"該任務的 ScheduledTime 應為 ""(.*)""")]
    public void Then_TaskScheduledTime(string expected)
    {
        throw new NotImplementedException("TODO: 取 task.ScheduledTime，斷言等於 expected。");
    }

    [Then(@"該任務的 StartWhenAvailable 旗標應為 true")]
    public void Then_StartWhenAvailableTrue()
    {
        throw new NotImplementedException("TODO: 斷言 task.StartWhenAvailable == true。");
    }

    [Then(@"該任務的 RunLevel 應為 LeastPrivilege（per-user）")]
    public void Then_RunLevelLeastPrivilege()
    {
        throw new NotImplementedException("TODO: 斷言 task.RunLevel 對應 per-user 設定。");
    }

    [Then(@"ICrawlerLauncher 應接收到 \(Mode = (\w+), TargetDate = (\d{4}-\d{2}-\d{2})\) 的呼叫")]
    public void Then_CrawlerLauncherReceivedCall(string mode, string date)
    {
        throw new NotImplementedException(
            "TODO: Mock<ICrawlerLauncher>.Verify with Times.Once 與參數比對。" +
            "或在 InMemoryTaskSchedulerAdapter 內部記錄 Action 呼叫並驗證。");
    }

    [Then(@"桌面程式可未開啟，仍應在 ""(.*)"" 產生 tenders\.json")]
    public void Then_TendersFileGeneratedDirectoryWithoutDesktop(string pathTemplate)
    {
        throw new NotImplementedException("TODO: ResolvePath，斷言 tenders.json 存在於該目錄。");
    }

    [Then(@"既有檔案 ""(.*)"" 內容與時間戳應與安裝前一致")]
    public void Then_FileUnchanged(string pathTemplate)
    {
        throw new NotImplementedException(
            "TODO: 在 Given 步驟記錄初始 SHA256 與 LastWriteTimeUtc，此處重算比對。");
    }

    [Then(@"不應有任何既有檔案被刪除或覆寫")]
    public void Then_NoFilesModified()
    {
        throw new NotImplementedException("TODO: 列舉資料目錄所有檔案，比對 Given 階段記錄的 hash 與 mtime。");
    }

    [Then(@"ITaskSchedulerAdapter 中名為 ""(.*)"" 的任務只應有 1 個")]
    public void Then_TaskCountIsOne(string taskName)
    {
        throw new NotImplementedException("TODO: InMemoryTaskSchedulerAdapter.CountByName(taskName) == 1。");
    }

    [Then(@"該任務的 ScheduledTime 應仍為 ""(.*)""")]
    public void Then_TaskScheduledTimeUnchanged(string expected)
    {
        throw new NotImplementedException("TODO: 同 Then_TaskScheduledTime。");
    }

    [Then(@"回傳的 ActionResult 應為 ActionResult\.NotExecuted（或自訂 PartialSuccess）")]
    public void Then_ActionResultPartialSuccess()
    {
        throw new NotImplementedException(
            "TODO: 從 ScenarioContext 取得 When 期間的 ActionResult，斷言 == NotExecuted 或 PartialSuccess。");
    }

    [Then(@"InstallationOutcome\.ScheduledTaskCreated 應為 (true|false)")]
    public void Then_InstallationOutcomeScheduledTaskCreated(bool expected)
    {
        throw new NotImplementedException("TODO: 取 InstallationOutcome（透過 ScenarioContext 或全域 state），斷言 ScheduledTaskCreated。");
    }

    [Then(@"安裝結果摘要應包含「(.*)」字樣")]
    public void Then_OutcomeSummaryContains(string substring)
    {
        throw new NotImplementedException("TODO: 取 InstallationOutcome.SummaryText，斷言 .Contains(substring)。");
    }

    [Then(@"回傳的 ActionResult 應為 ActionResult\.Failure")]
    public void Then_ActionResultFailure()
    {
        throw new NotImplementedException("TODO: 斷言 ActionResult == Failure。");
    }

    [Then(@"不應呼叫後續的 TaskSchedulerActions\.CreateDailyTask")]
    public void Then_CreateDailyTaskNotCalled()
    {
        throw new NotImplementedException(
            "TODO: 確認 InstallerSimulator 在 EnsureDataRoot 失敗時應停止後續 actions；" +
            "驗證 InMemoryTaskSchedulerAdapter 不含任務。");
    }

    [Then(@"安裝程序應中止，不應留下任何捷徑或排程任務")]
    public void Then_InstallationAborted()
    {
        throw new NotImplementedException(
            "TODO: 斷言 InMemoryTaskSchedulerAdapter 為空，且模擬的桌面/開始選單捷徑路徑不存在。");
    }

    [Then(@"WiX Rollback 應移除本次安裝建立的捷徑檔案")]
    public void Then_WixRollbackRemovesShortcuts()
    {
        throw new NotImplementedException(
            "TODO: InstallerSimulator.WasShortcutsCreated == true 時，Cancel 後應呼叫 Rollback；驗證捷徑路徑已不存在。");
    }

    [Then(@"ITaskSchedulerAdapter 不應含名為 ""(.*)"" 的任務")]
    public void Then_TaskNotExists(string taskName)
    {
        throw new NotImplementedException("TODO: InMemoryTaskSchedulerAdapter.GetTask(taskName) 應為 null。");
    }

    [Then(@"既有的資料根目錄（若安裝前已存在）應保留")]
    public void Then_PreexistingDataRootPreserved()
    {
        throw new NotImplementedException(
            "TODO: 若 Given 階段記錄了既有資料目錄，此處驗證仍然存在且內容未變。");
    }

    [Then(@"目錄 ""(.*)"" 與其下的歷史資料應完整保留")]
    public void Then_HistoricalDataPreserved(string pathTemplate)
    {
        throw new NotImplementedException(
            "TODO: ResolvePath，斷言 Directory.Exists；遍歷子檔案比對 Given 階段記錄的 hash。");
    }
}
